rpm-software-management/rpm

lib/rpmscript.c, tests/Makefile.am, tests/data/SPECS/scripts-nice-ionice.spec, tests/rpmscript.at
Sometimes you may consider running an entire yum upgrade wrapped on nice and
ionice to soften the effect of the upcoming I/O and CPU storm on the system.
The side effect of that is that restarted services and anything else executed
from the pre- and post- rm and installation scripts will be niced and ioniced as
well, defeating the whole idea.  If e.g. sshd is in such state, anything that you install and restart while connected through ssh will be also nice'd and ionice'd.
With this, you are safe to run it, because we will reset nice and ionice values
right after fork() to the default values.
=> Reset nice and ionice priorities when executing scripts.

system.h
NetBSD and OS X aren't the only BSD derivatives with support for `setprogname()` and `getprogname()`, so this PR adds the definitions for the rest of them.
=> Add all the BSDs that support setprogname() and getprogname()

rpm.pc.in
The reference in `rpm.pc.in` is invalid and never gets filled in. By changing it to the correct reference for `configure.ac` substitution, it should work as expected.
=> Fix pkgconfig reference to Lua in Libs.private

lib/rpmrc.c
This pull request adds support for x86_64 for Darwin (Mac OS X) and adjusts the logic slightly so that in the event an architecture is not defined, it throws a warning.
Depending on how the architecture is set up, RPM may or may not properly detect it, which is why this is a warning instead of an error.
=> Add x86_64 for Darwin (Mac OS X) in rpmrc.c, enabling x86_64 target

rpmio/base64.c
There's an off-by-one error in base64_decode_value which results in undefined behaviour:
void* out;
size_t len;
rpmBase64Decode("\x7b", &out, &len);
=> Fix off-by-one error

python/rpm/transaction.py
```python
*** Error compiling '/builddir/build/BUILDROOT/rpm-4.13.0_alpha-239g190fa42.fc24.x86_64/usr/lib64/python3.5/site-packages/rpm/transaction.py'...
File "/usr/lib64/python3.5/transaction.py", line 9
SyntaxError: from __future__ imports must occur at the beginning of the file
```
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> rpm/transaction: move from __future__ to the top

lib/rpmplugins.c
For example, in simple docer container there is no systemd, so
systemd_inhibit plugin returns RPMRC_NOTFOUND in _init() which
automatically disables plugin (!= RPMRC_OK).
So let's say that if plugin returns RPMRC_NOTFOUND during init()
it's just signal to disable plugin and not show error.
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> rpmplugins: don't print error if return code is RPMRC_NOTFOUND

fileattrs/Makefile.am, fileattrs/debuginfo.attr, macros.in, scripts/Makefile.am, scripts/debuginfo.prov
This patch lets debuginfo packages provide build-id like follows:
debuginfo(build-id) = c63cb23876c5fa85f36beaff58f8557e1bf22517
Originally this patch was written by Jan Blunck <jblunck@suse.de>.
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> let debuginfo packages provide the build-id

installplatform, lib/rpmrc.c, rpmrc.in
These patches add support for the RISC-V architecture.
For further information, see https://fedoraproject.org/wiki/Architectures/RISC-V
=> Add support for RISC-V

configure.ac
The logic that tests whether gcc supports or not certain flags uses
AC_COMPILE_IFELSE(). However, when checking for stack smashing
protection support, an AC_LINK_IFELSE() test is needed, since the
build might work but not the link stage if certain libraries are
missing for proper stack smashing protection support.
Therefore, this commit switches to use AC_LINK_IFELSE().
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: James Knight <james.d.knight@live.com>
=> configure.ac: use link instead of compile for gcc flags test

build/parseFiles.c
Background story is in rhbz#1374138, having the warning better
spelled before would simplify macro debugging a lot in that case.
=> build: better warning for non-unique %files section

build/build.c, macros.in
Alternative implementation for #141 
It sets the environment variable during the build stage and not while parsing the spec which should be free from side effects.
=> set SOURCE_DATE_EPOCH from changelog

plugins/selinux.c
SELinux recommends to use string_to_security_class() instead of referencing
class IDs directly. This also fixes a build issue for systems that don't
include flask.h by default.
References:
https://selinuxproject.org/page/NB_Imp_SELinux-aware_Apps#Implementing_SELinux-aware_Applications_2
https://github.com/SELinuxProject/selinux/commit/76913d8adb61b5afe28fd3b4ce91feab29e284dd
=> selinux: use string_to_security_class() instead of class ID

scripts/pythondistdeps.py
As Python wheels do not contain targetted Python version in the directory/file
name of their metadata like Python eggs do, and since the Python version is not
contained in the metadata either, it is necessary to get it from elsewhere.
Here it is parsed from the path the metadata resides at
(e.g. /usr/lib/pythonX.Y/site-packages/...)
For more information, [bugzilla report for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1421776).
=> Fix pythondistdeps.py --provides for Python wheels

build/files.c, macros.in
Limit the maximum date to SOURCE_DATE_EPOCH, if defined
similar to the tar --clamp-mtime option
based on a patch by `Nicolas Vigier <boklm at torproject.org>`
together with previously merged
#143 
b8a54d6a1e9bb6140b6b47e23dc707e4b967537e from @boklm
22588250baa1bfa5c00f57d39329d0c144fc8112
This allows rpmbuild to produce bit-by-bit identical rpms on different hosts when setting rpmmacros to
```
%_buildhost reproducible
%source_date_epoch_from_changelog Y
%clamp_mtime_to_source_date_epoch Y
```
macro is needed, because not everyone might want it, as it is known to affect python packages that include .pyc files which reference the original timestamp. Those will still work but re-compile on demand.
=> Allow SOURCE_DATE_EPOCH to override file timestamps

macros.in, rpmrc.in
This patch adds support for `armv5tl`, which we have been using in Mageia to support an ARM port for a while now, and is an officially supported architecture for Mageia 6.
=> Add armv5tl support

scripts/find-debuginfo.sh
In case that binary compiled from source generated in /tmp, a
/usr/src/debug/tmp directory will be created with the same mode as
/tmp, a.k.a 777, which should be avoided.
Fixes: RhBug:641022
=> Fix non-standard inherented modes of directories in debuginfo

scripts/pkgconfigdeps.sh
pkgconf (alternative to freedesktop's pkgconfig implementation)
uses this flag to stop resolving dependencies after some level.
In our case, we are not interested in checking dependencies from
buildroot at all, we just generating top-level dependency list.
References: https://bugzilla.redhat.com/show_bug.cgi?id=1401463
Reported-by: Martin Sehnoutka <msehnout@redhat.com>
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> pkgconfigdeps: disable dependency resolver where supported

build/files.c, build/parsePreamble.c, build/parseSpec.c, build/rpmbuild_internal.h, macros.in, scripts/find-debuginfo.sh
This adds support for SUSE style debuginfo packages. Due to the changes in rpm upstream the patch had to be pretty much rewritten from scratch.
As the new functionality is off per default the patch cannot break anything.
=> Add support for debugsource subpackages and split debuginfo subpackages

build/files.c
Do not store digests of ghost files
when the files exist during build time.
The hash will never be used for verification anyway.
This helps making packages build more reproducibly.
To test use
```
echo $RANDOM > %{buildroot}/var/cache/ghostfile
%files
%ghost /var/cache/ghostfile
```
and check with `rpm -qp --dump $RPM`
=> Do not store digests of ghost files

build/pack.c, lib/header.c, lib/header_internal.h, lib/package.c
Use a simple heuristic instead of looking at the lead type when we can't decided if a header is from a source package or not.
=> Make source package detection less error prone.

scripts/perl.prov
This is a [patch](https://build.opensuse.org/package/view_file/Base:System/rpm/perlprov-package.diff) we apply to rpm in openSUSE. It allows the `perl.prov` script to detect new variants of Perl package declarations that have been added in recent years.
In [Perl 5.12](https://metacpan.org/pod/distribution/perl/pod/perl5120delta.pod#New-package-NAME-VERSION-syntax) we got version numbers as part of the package declaration.
```perl
package Foo 1.0;
package Bar v1.0.0;
```
And in [Perl 5.14](https://metacpan.org/pod/distribution/perl/pod/perl5140delta.pod#package-block-syntax) we got the package block syntax.
```perl
package Foo {...}
package Bar 1.0 {...}
package Baz v1.0.0 {...}
```
We noticed this problem recently because [Dist::Zilla](https://metacpan.org/source/RJBS/Dist-Zilla-6.009/lib/ …
=> Add support for new package declarations in Perl 5.12+

tests/Makefile.am
Right now `make check` returns success exit status: 0 when the tests are failed.
```
$ make check
...
ERROR: All 358 tests were run,
21 failed (2 expected failures).
...
```
```
$ echo $?
0
```
Because the logic to succeed forcely is added below commit.
But I think that it is not good. Because we can not detect failed tests for example in `rpm.spec` check section.
https://github.com/rpm-software-management/rpm/commit/52bc67436f5bc28d2bd08a9fd3498cf16d5817bb
After this modification, `make check` returns error exit status.
```
$ make check
...
ERROR: All 358 tests were run,
21 failed (2 expected failures).
...
```
```
$ echo $?
2
```
=> Return error exit status when make check is failed.

macros.in
It has been used in redhat-rpm-config for long time and some
packages depend on it (though without `_` prefix).
It's just more convenient than writing %{_rpmconfigdir}/macros.d/...
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>
=> macros: add %_rpmmacrodir

sign/rpmgensig.c
The replaceSigDigests function is only used in includeFileSignatures
when WITH_IMAEVM is defined. If not warning is generated.
Signed-off-by: Mark Wielaard <mark@klomp.org>
(this is same patch as posted to mailing list, sending it here since now we have CI)
=> replaceSigDigests is only used with IMAEVM.

build/files.c
```
==9077== 336 (40 direct, 296 indirect) bytes in 1 blocks are definitely lost in loss record 32 of 37
==9077==    at 0x4C31C15: realloc (vg_replace_malloc.c:785)
==9077==    by 0x57575B7: rrealloc (rpmmalloc.c:65)
==9077==    by 0x574FEE2: argvAdd (argv.c:138)
==9077==    by 0x4E45C8E: addNewIDSymlink (files.c:1705)
==9077==    by 0x4E4B946: generateBuildIDs (files.c:1969)
==9077==    by 0x4E4B946: processPackageFiles (files.c:2542)
==9077==    by 0x4E4B946: processBinaryFiles (files.c:3076)
==9077==    by 0x4E44180: buildSpec (build.c:262)
==9077==    by 0x402E6E: buildForTarget.constprop.1 (rpmbuild.c:517)
==9077==    by 0x4030CA: build.constprop.0 (rpmbuild.c:550)
==9077==    by 0x4020AA: main (rpmbuild.c:697)
==9077==
==9077== 487 (48 direct, 439 indirect) bytes in 1 blocks are …
```
=> fix couple of memory leaks in rpmbuild

rpmio/digest_openssl.c
```
digest_openssl.c:552:9: warning: Value stored to 'rc' is never read
rc = 0;
^    ~
```
Acked-by: Stephen Gallagher <sgallagh@redhat.com>
=> digest_openssl: return failure if setting key failed

macros.in
Since the introduction of "errexit" option of build-scriptlets-handling
(covering mainly prep, build, install, and check phases) shell execution
(sh -e) in d9a3f08d8, it was also for some undocumented reasons
accompanied with "exit 0" enforced scriptlet epilogue, now in the form
of ___build_post macro.
Per POSIX specification[1] (and using the terms devises), these two
provisions combined provide mostly the desired bail-out-ready execution
behaviour for:
- simple command
- last command in an AND-OR list
i.e., when these fail (non-zero exit status), the shell itself in turn
exits, carrying the exit status through its boundary, consequently
failing rpmbuild process as such.
Where such a propagation does _not_ occur and why does the behaviour
leave more to be desired, is a matter of the …
=> Build scriptlets handling: pass exit status of last execution regardless

lib/depends.c, lib/order.c, lib/rpmdb.c, lib/rpmds.c, lib/rpmds.h
An (A unless B) dependency implements (A and not(B)). This kind is useful
for "or" type dependencies, e.g. "Conflicts" or "Supplements".
As "Conflicts: (A unless B)" is equivalent to "Requires: (B if A)", I
thought this type is not needed. But there is no such equivalence
for Supplements, thus the change in mind.
Like with "if" we also have a syntactic sugar "else" flavor:
(A unless B else C) is the same as ((A unless B) or (B and C))
This commit also makes the "else" handling code in depends.c much
easier to understand.
=> Add support for 'unless' rich dependencies

configure.ac
The typo in this check prevents rpm for correctly detecting compatibility with OpenSSL 1.0.2.
=> configure: Fix typo for libcrypto usability check for OpenSSL check

doc/rpmspec.8
Add information on the missing parsing option of rpmspec (-P,--parsing)
in its manpage.
=> Add missing option to rpmspec manpage

po/pl.po
Transifex has wrong plural forms for Polish that they refuse to change.
Now that RPM ditched Transifex, we can fix it.
=> Update Polish plural forms

build/rpmfc.c, build/rpmfc.h, tools/rpmdeps.c
This is an alternative solution to the part in https://github.com/rpm-software-management/rpm/pull/216 that was rejected.
Rather than changing the behavior of the existing `--rpmfcdebug` option, this adds a new option `--all-per-file`, which outputs the same information as `--rpmfcdebug` does, but to stdout. 
The reason why this is needed and why not to just use `rpmdeps --rpmfcdebug ... 2>&1` is that if there is an error, the error message would then end up on stdout as well and never be shown to the user who then has no idea why the command failed (assuming that stdout is caught by some other process that uses the output from `rpmdeps` as its input).
I am not very happy about the option name, `--all-per-file`, but it was the best I could come up with to indicate that it outputs all …
=> Add a new option --alldeps to rpmdeps

python/setup.py.in
This fixes the Python bindings ModuleNotFoundError for custom prefix.
http://lists.rpm.org/pipermail/rpm-maint/2017-September/006568.html
The reason is the Extension class libraries attribute does not accept library file or directory path.
According to
https://docs.python.org/3/distutils/apiref.html
https://docs.python.org/2/distutils/apiref.html
> libraries list of library names (not filenames or paths) to link against
We may close below ticket by this PR.
https://github.com/rpm-software-management/rpm/issues/130
Below is the work flow to check the bug is fixed.
```
$ pwd
/home/jaruga/git/rpm
$ ./autogen.sh --noconfigure
$ ./configure --prefix="$(pwd)/dest"
$ make
$ make install
$ dest/bin/rpm --version
RPM version 4.14.90
$ cd python/
$ which python3
/usr/local/python-3.6.2/bin/python3 …
```
=> Fix Python bindings library path for custom prefix.

configure.ac
If /etc/passwd contains multiple users with UID 0 then user_with_uid0 will
contain a line feed which results in config.h containing:
#define UID_0_USER "root
(i.e. without a closing quote.)
The same problem occurs with /etc/group.
Let's only emit the first match in each case so that there is only ever a
single result.
=> Make configure cope with multiple users/groups with ID 0

COPYING
I was looking at this file in the context of dnf/rpm-ostree integration:
https://github.com/rpm-software-management/dnf/pull/991#issuecomment-355587679
The incorrect use of "it's" was distracting; I ended up rewording the initial
sentence to be more direct.
The second hunk is another grammar fix.
=> COPYING: Minor grammar fixes

lib/signature.c
The old code just subtracted 8 bytes from the reserved space, but
that does not take tag alignment into account and led to the
signature header overwriting the package header.
We now use headerSizeof to calculate the real size difference.
Note that this only works reliable if the reserved space tag comes
last in the signature header!
=> Fix sigheader generation for big archives

scripts/brp-python-bytecompile
This added check figures out whether invoking `$default_python` is necessary and exits early if no files would be bytecompiled by the two blocks below.
This prevent's invoking `$default_python` (i.e. `%{__python}` (i.e. most likely `/usr/bin/python`)) when not needed. Currently (before this change) it has been invoked twice for each build (iff the executable was present in the buildroot), even tough in most cases it did nothing. While this might have been harmless, it prevents us to deprecate or even forbid `/usr/bin/python` invocation during RPM build as proposed in Fedora in [1].
While this change is driven by Fedora's needs, I believe it can be useful for others as well. It doesn't render the script utterly more complex, while it prevents it from doing 2 superfluous (possibly slow) …
=> brp-python-bytecompile: Run a pre-flight find before invoking $default_python

macros.in, plugins/ima.c
Even though config files may be close to what could be described as
'mutuable files', we now want to install the signatures on these files
as well.  However, we should be aware that the signatures of these
files may become incorrect or missing once RPM post installation scripts
or other programs have modified these configuration files.
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com
=> Also apply signatures to config files

rpmrc.in
AArch64 has another common name for the architecture: `arm64`. And while compilers, the kernel, and RPM use `aarch64`, a number of language ecosystems use `arm64`.
In addition, Debian packages use the `arm64` architecture name to refer to `aarch64`, and AArch64 packages that are translated from DEB to RPM format tend to not be installable because there's not a sufficient architecture mapping.
This change adds the `arm64` identifier as an alias for `aarch64` so that this works as expected, rather than breaking on unknown architectures.
=> rpmrc: Add architecture compatibility mapping between aarch64 and arm64

lib/legacy.c
rpmtdFreeData resets td.count to 0, so the whole thing never worked.
Better late than never, they say.
=> legacy.c: Fix headerGetEntry count

rpmio/rpmfileutil.c
Avoid dividing by zero when hitting an ELF section without fixed-size
entries.
Thanks to Michael Schroeder for helping trace the problem (in #420)
=> Fix division by zero in prelink detection, issue 420

scripts/find-debuginfo.sh
debugedit and dwz do not support DWARF compressed ELF sections, let's
just decompress those before extracting debuginfo.
Tested-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> find-debuginfo.sh: decompress DWARF compressed ELF sections

scripts/pythondistdeps.py
The purelib and platlib were both defined to /usr/lib64/python on 64bits systems. This is because:
>>> get_python_lib(standard_lib=1, plat_specific=0)
'/usr/lib64/python3.7'
>>> get_python_lib(standard_lib=1, plat_specific=1)
'/usr/lib64/python3.7'
>>> get_python_lib(standard_lib=0, plat_specific=0)
'/usr/lib/python3.7/site-packages'
>>> get_python_lib(standard_lib=0, plat_specific=1)
'/usr/lib64/python3.7/site-packages'
So now we use standard_lib=0 to get the site-packages base path from /usr/lib and not /usr/lib64.
See https://bugzilla.redhat.com/show_bug.cgi?id=1609492
And https://src.fedoraproject.org/rpms/python-rpm-generators/pull-request/2
=> Python generators: Use nonstandardlib for purelib definition

fileattrs/Makefile.am, fileattrs/pythondist.attr
Rather than having the pythondistdeps dependency generator run on all Python code, this separate attr will activate it only if the package includes Python dist metadata (such as egg-info or dist-info for Python Eggs and Python Wheels, respectively).
This is much more efficient, too, since the generator is only run in circumstances where it will provide useful information.
This is based on the dependency generator attr used in Mageia, OpenMandriva, and other systems that use the generator.
=> fileattrs: Add attr for pythondistdeps and fix python attr

python/header-py.c, python/rpmii-py.c, python/rpmmi-py.c, python/spec-py.c
Addressing things like
```
print s.prep()
^
SyntaxError: invalid syntax
```
=> Make python examples run with python 3, the print commands.

scripts/find-debuginfo.sh
sort output of find in find-debuginfo.sh
to make build results more reproducible
in spite of indeterministic filesystem readdir order.
Even where these lists do not become part of an rpm,
it makes it easier to debug unrelated issues
by having less overall diff from diffing build filesystem trees (one of the standard reproducibility-debugging techniques I use).
For openSUSE, this helped to make squid, openssh, postfix and shadow
packages build reproducibly.
See https://reproducible-builds.org/ for why this is good.
Note: elfbins.list has remaining indeterminism from the `run_job` function running in parallel unless using `-j1`
Note: only tested in a slightly different variant on openSUSE's rpm-4.14.1
=> find-debuginfo.sh: sort output of find

python/spec-py.c
Addressing
```
Traceback (most recent call last):
File "test.py", line 7, in <module>
print(s.prep())
TypeError: 'str' object is not callable
```
=> rpm.spec's .prep seems to be an attribute.

rpmpopt.in
Almost nobody uses them, so the
"Relocations : (not relocatable)" line is a waste of screen estate.
Just output the line if there's something interesting to show.
=> Skip showing empty Relocations line in rpm -qi

scripts/find-debuginfo.sh
Example output:
...
original debug info size: 120600, size after compression: 77604
...
=> Info how beneficial is dwz compression.

macros.in
e.g. can be useful for src.rpms where .tar.xz files are already compressed
=> Document uncompressed payload

build/build.c
Make sure SOURCE_DATE_EPOCH is in the past,
otherwise, builds before noon will not have normalized mtimes
from %clamp_mtime_to_source_date_epoch
This also helps other programs like tar --clamp-mtime
Tested successfully on openSUSE.
To reproduce, create a changelog entry with only a date
```
* Fri Aug 31 2018 user@host
- dummy
```
and build it before 12:00 UTC
using macros
```
%source_date_epoch_from_changelog Y
%clamp_mtime_to_source_date_epoch Y
%use_source_date_epoch_as_buildtime Y
%_buildhost reproducible
```
`rpm -qpvl` showed file mtime values to not be normalized
and therefore build results were not bit-identical.
Edit: would be nice to avoid the modulo heuristic and find out if there was a time in the changelog or just a date. How?
=> build: Make sure SOURCE_DATE_EPOCH is in the past

macros.in
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> Fix %arm macro to include newer processor types

macros.in, rpmrc.in
armv8* is aarch64 machines in 32-bit mode
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> Add armv8* arch variants to rpmrc.in

fileattrs/python.attr, fileattrs/pythondist.attr
The current regular expression for matching on Python metadata files was
too greedy, leading to generating dependency information for Python modules
that were actually bundled in another module rather than actually being
installed in a way that is usable and accessible from any Python code
using the system interpreter.
This change tightens the regular expression so that we only match on
modules that are installed in a way that they'll register with
distutils/setuptools based tools (such as pip) and usable as
dependencies for other Python module packages.
Resolves [RhBug:1618949](https://bugzilla.redhat.com/show_bug.cgi?id=1618949)
=> fileattrs: Tighten pythondist path regex for metadata (RhBug:1618949)

doc/manual/dependencies
This is the last reference to %__find_prereq macro,
the support for this macro was removed long time ago
by commit 44e5913dae80f1040748441af35fb02b840c397a.
=> doc/manual/dependencies: remove reference to %__find_prereq

doc/manual/spec
Document briefly conditionals and the fact that they work correctly in spec files only.
=> Add descrption of conditionals into the spec documentation

scripts/find-debuginfo.sh
Since file 5.33, PIEs are identified by a new MIME type, meaning that,
currently, for such executables, the .gnu_debugdata section is not
added, even if -m is passed.
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> find-debuginfo.sh: Handle position-independent executables

build/parseSpec.c
Before this commit, rpm handles text after %else or %endif
nonconsistently and does not give any feedback:
- a text after %else was expanded according to evaluation
of the previous %if.
- a text after %endif was expanded according to evaluation
of the previous %else, resp. %if if there was no %else.
So in the current spec files there exist lines like:
%else %if 0%{?centos}
%else !use_embedded
%endif # with_perf
(comments must have '#' at the start of the line to behave as defined)
So to be consistent and clear, this warning is added. It looks
for example:
warning: line 93, no text in allowed after %else
=> Warn if a text is after %else or %endif

tests/Makefile.am, tests/data/SPECS/iftest.spec, tests/rpmmacro.at
The underlying problem tested in the patch:
If a macro is in a macro file and at the same time it contains
%ifxxx - %endif (%ifxxx here denotes one of %if, %ifarch, %ifnarch,
%ifos, %ifnos) then during the rpm expansion of the macro the lines
inside %ifxxx - %endif are expanded in all cases (no matter whether
the condition after %ifxxx is satisfied or not).
Thus e.g. if the following definition is in a macro file:
%mymacro \
%if 0  \
%global bbb ccc \
%endif \
%{nil}
and a spec file contains line:
%mymacro
then during the expansion of %mymacro macro %bbb is globally
defined even if the condition after %if is not true.
It is not a problem in evaluation of the %if condition. It is caused
by the fact that the whole %mymacro is expanded in several recursive 
steps and in meantime there is no …
=> Test a macro from a macro file that contains %ifxxx - %endif

lib/query.c, tests/rpmquery.at
Additionally if a package query with the argument was successful, there 
is no need to rpm query of the argument.
=>  Correct rpm -ql exit value when optional -p is omitted (RhBug:1680610)

rpmio/digest_nss.c
signal.h must be included to be able to use sigaction
Fixes:
- http://autobuild.buildroot.org/results/395fd44a930dfc2ad380bc735c26d9ce62344295
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> rpmio/digest_nss.c: fix build on musl

scripts/find-debuginfo.sh
It helps to make build results reproducible. Based on Mark Wielaard's idea.
=> Sort list of hard linked files in find-debuginfo.sh (RhBug:1421272)

build/files.c
Initialize verifyFlags for specialdir, because
FileEntryFree(&fl->cur) zeroed all fields, including verifyFlags, so we have to fill them again.
Closes issue #655
Note: only slightly tested
=> Initialize verifyFlags for specialdir

lib/fprint.c
Both yum and dnf perform a test-transaction before the real thing,
and both neglet to check for an error code from the test-transaction
when there are no problem objects to return. Which can happen in
some special cases, such a using different vsflags between initial
package read and transaction (which is what both yum and dnf do),
which can cause the in-transaction package open fail on corrupt packages.
And when this failed transaction is fed back to rpmtsRun(), it
segfaults in fingerprinting as the second loop of symlink checking
doesn't check for NULL's element files like the first loop does.
Add the missing NULL check and remove bogus "can't happen" comment to fix.
FWIW, the scenario with different vsflags and corrupted packages doesn't
happen by default in rpm >= 4.14.2, the corrupt …
=> Fix segfault on fingerprinting symlink round (RhBug:1660232)

build/files.c, configure.ac
The prime use-case is build-id generation for compressed kernel modules, see  https://bugzilla.redhat.com/show_bug.cgi?id=1650072 for background.
The first commit is independent in that it simply improves the detection of kernel modules, the second part actually enables compressed ELF via use of dwelf_elf_begin().
Caveat: I haven't actually tested it with a kernel module due to not having a sane reproducer (rebuilding the entire kernel just for this is not an appetizing thought).
=> Support build-id generation from compressed ELF files

tests/Makefile.am
Up to now the rebuild has been keyd to the top directory rpmbuild binary,
but this misses numerous cases where the testing-environment requires
rebuilding, including but certainly not limited to python bindings.
It may take a few seconds more but compared to the test-suite runtime
this is just peanuts, not to mention the amount of gray hair and wasted
engineer hours caused by test-environment not updating when it should.
=> Always rebuild the test-suite testing-environment from scratch

scripts/pythondistdeps.py
Fixes https://github.com/rpm-software-management/rpm/issues/664
=> Python generators: console_scripts entry points require setuptools

macros.in, scripts/brp-strip-static-archive, tests/Makefile.am
This variant passes RPM_BUILD_NCPUS as environment variable to all build scripts and uses it to paralize brp-strip-static-archive.
Obsoletes #663
=> Alternative implementation of #663

build/parseChangelog.c, build/parseDescription.c, build/parseFiles.c, build/parsePolicies.c, build/parsePrep.c, build/parseScript.c, build/parseSimpleScript.c, build/parseSpec.c, build/rpmbuild_internal.h
Consolidate umptheen copy-slop variants of the same readLine() construct into a unified helper, port all simple cases to use it. parsePreamble.c has a couple of readLine() uses that do more work than just add lines, that's left as an exercise for another rainy day. Supposedly no functional changes, other than truly unified behavior for all these cases (there were some subtle error checks missing in some of the copies)
=> Consolidate most spec line reading into a single helper function

build/build.c, build/files.c, build/rpmbuild_internal.h, build/rpmfc.c
=> Unify build-script running to always use rpmfcExec()

lib/poptALL.c
Before the patch rpm treats the relative path as a full path.
The new behavior is similar to the "--root" option.
=> Use --dpbath only with full path (RhBug:1696408)

build/files.c, tests/rpmbuild.at
While supported of course, absolute symlinks are nasty in many ways
so issue a warning to packagers. Related to #668.
=> Warn on absolute symlinks at build-time

build/parsePreamble.c
Fixes a regression on mixed auto vs manual numbered patches/sources
introduced in commit 5fc4e1dd101b27eb8ed9526552c42bb809ac6790
=> Continue patch/source autorenumbering from last specified number

scripts/brp-strip-static-archive
The change made in fc2c986 can break for large values of %_smp_build_ncpus as
this many processes are able to overflow the following pipe.
Thanks to Denys Vlasenko for testing this.
This change solves this problem by running a whole processing pileline for each
parallel (file) process. This has also the benefit of running at least some
stip commands in parallel.
The -n param fro xargs was increased to 32 to further reduce the over head of
spawing the helpers as they are now needed for each run of the file command.
=> Fix brp-strip-static-archive parallelism

macros.in
The only real users were in the unused %GNUconfigure macro which was
already removed in commit bb2cd52cf1067b9d18106f127a5034e2ad50db64 and
these should've gone with them.
This is a counter-proposal to #688
=> Drop leftover autotools-related macros

scripts/check-buildroot
Reduces run time on my /usr dir from 1:17 to 0:15 when fully cached.
Use
RPM_BUILD_ROOT=/usr RPM_BUILD_NCPUS=16 time scripts/check-buildroot
to toy around yourself.
=> Make check-buildroot check the build files in parallel

rpm2archive.c
Fixes "warning: ‘rc’ may be used uninitialized in this function"
introduced in commit c73b0f34e32c299c87b7163352808d1071a05d2b.
=> Fix recently introduced uninitialized variable warning in rpm2archive

build/rpmbuild_internal.h, build/rpmfc.c, build/spec.c
When called in spec context, the package structs are properly freed
but in rpmdeps context, commit 49f2bb7d8fd91f2d8b22bf7128fd3defe4ed5434
only added a "dirty kludgery" to make it not blow up. This causes
the rpmds structures created in rpmfcApplyInternal() to leak memory.
Make freePackage() internally available and use it for freeing the
dummy struct too to fix.
=> Fix memleak in rpmfcApplyInternal() in standalone operation (eg rpmdeps)

macros.in
This is bascially a more elaborate version of #660 :
- Add language specific %build_fooflags macros to allow separate distro-wide defaults for c, c++ and fortran
- Add %build_ldflags for specifying distro-wide ldflags (how on earth we didn't have this?)
- Split FOOFLAGS= setting out of %configure to %set_build_flags macro to make them available outside autotools
=> Adopt compiler flags related enhancements from Fedora

build/files.c, lib/rpmfi.c, lib/verify.c, macros.in, rpmio/Makefile.am, rpmio/rpmfileutil.c, rpmio/rpmfileutil.h
Back in the turn of the century somebody thought it was a neat idea
to completely compromise system security to improve program start-up
start-up times a wee bit. Since then, people have thankfully started
coming to their senses and removed prelink from distros entirely.
Lets stop papering over the security disaster: we obviously cannot
stop people from using prelink, but instead of trying to undo the
damage for verification purposes, we'll now report such a system as
compromised. Which is how it should be, IMNSHO.
This eliminates a whole lot of extra junk from each and every file
digest calculation that we do, so it might even show up on somebodys
performance charts. It also gets rid of libelf dependency outside
librpmbuild, which is a nice little bonus.
Inspired by a patch to eliminate …
=> Stop papering over the security disaster known as prelink

lib/rpmchroot.c
Since we don't have proper user/group info inside userns-root, avoid
going there unless we have to. Fixes a regression introduced in
commit b4c832caed0da0c4b0710cfe2510203a3940c2db where non-root,
non-chroot verification shows user and group differing on all files.
=> Only switch to userns-root if we actually need it for chroot()

build/rpmfc.c
This basically turns the dependency generation order inside out: previously we ran through the file list one by one, running dependency generators for all types the file was found to match, ie in file:attr:deptype order. Now we do the exact opposite: deptype:attr:file, which allows us to optimize to only expand all those macros once per deptype / attr instead of once per file. 
Sadly all that is lost in the noise of actually forking + executing those dependency generators, but this is basically a prerequisite for the far more important optimizations, such as (some day) teaching the generators to work on multiple files at once and ultimately, multiple generators in parallel.
=> Dependency generator optimization and cleanup

build/Makefile.am, build/parseList.c, build/parsePreamble.c, build/parseSpec.c, build/rpmbuild_internal.h, tests/Makefile.am, tests/data/SOURCES/hello-1.0-install.patch, tests/data/SPECS/hello-auto.spec, tests/rpmbuild.at
This introduces two new spec sections, %patchlist and %sourcelist,
which can be used for adding patches and sources by just listing their
names instead of all the tedious Patch[n]: etc boilerplate, you can
just copy-paste file names into the list, the entries are always
autonumbered, eg:
Patch0: popt-1.16-pkgconfig.patch
Patch1: popt-1.16-execfail.patch
Patch2: popt-1.16-man-page.patch
...
can now we replaced with
%patchlist
popt-1.16-pkgconfig.patch
popt-1.16-execfail.patch
popt-1.16-man-page.patch
Typical packages have far fewer sources than patches, so %sourcelist
is not as immediately useful but added anyway for symmetry and because
its so easy.
Depends on PR #678
=> Add support for %patchlist and %sourcelist spec sections

lib/depends.c
When adding update elements, we set the erase element to depend on the
install element, but if an API user adds the same erasure manually
after adding the update, we know its a duplicate erasure and filter
it out, BUT we zero out the dependent element in the process. And
if installing the update now fails, we end up removing the whole package
due to that missing dependent element.
This never happens with rpm itself so we can't easily test it, but is
100% reproducable with dnf (at least dnf 3-4). Apparently it adds all
erasures by itself (which is kind of understandable I guess, perhaps
we should better allow this in the API)
=> Fix packages getting erased on failed update with dnf (RhBug:1620275)

build/parsePreamble.c, tests/data/SPECS/foo.spec, tests/rpmspec.at
Commit 6dafb24684baa71fe3b89be6404e6ab0362cf316 introduced a regression
where patch/source (and likely buildroot and docdir too) values
end up leaking to macros of other tags, due to missing reinitialization
to NULL in the code.
This only shows up in specs ordered in a specific way which is why
our test-suite failed to trip it, but it caused eg Fedora attr.spec and
kernel.spec to fail parse. Hijack the otherwise unused foo.spec to
create a test-case for this.
=> Fix regression causing patch/source tags leaking to other macros

build/files.c, build/pack.c, build/parseSpec.c, build/rpmbuild_internal.h, rpmio/macro.c, rpmio/rpmstring.c, rpmio/rpmstring.h, tests/rpmmacro.at
Report filename and line number on all macro expand errors and warnings from macro files and specs, includes and manifests.
This is an alternative proposal for PR #494 to address ticket #491, and doesn't involve API changes or additions and covers more than just the spec.
=> Report filename and line number on all macro expand errors and warnings

python/header-py.c, python/rpmmodule.c, python/rpmsystem-py.h, python/rpmtd-py.h, python/spec-py.c
Remove remnants of long dead code, and eliminate unnecessary hoops for header object creation from spec.
=> Couple of python binding cleanups

tests/Makefile.am
Should've been in commit 58dcfddc376a7c97de1432f0082be0d5f01adbcd
This was originally part of #719 but that turned out to require more work than anticipated. Breaking distcheck is a release blocking regression however.
=> Include dynamic buildrequires test material in dist tarballs

tests/Makefile.am
Another distcheck regression fix, should've been in commit
ad8c12c5d962c136232d6309d3324a4e57b32877
Originally part of #719 but there's still problems with that.
=> Include file capability test material in dist tarballs

Makefile.am, ci/Dockerfile, tests/Makefile.am
Using distcheck instead of plain check will catch many more source-level errors, such as regressions to out-of-tree builds and source files present in git tree but missing from automake. These issues sometimes go unnoticed for long times, only to be discovered when preparing for a release at which point you'd rather worry about something else than chasing pesky distcheck regressions.
=> Use distcheck as the CI test

build/parsePrep.c, tests/rpmbuild.at
First issue is that doUntar() when encounters an issue related to the
spec file, returns non-NULL which indicates that no error has happened.
Second is that even if it would return that, parsePrep() is simply
ignores return code.
Also be more consistent with "goto exit;".
Fixes: 76c429c3178c965c6517629957a633768132904c
Fixes: c7a8c1e079d2a166b9848ae6afa1b0cfab1b250a
Fixes: https://github.com/rpm-software-management/rpm/issues/728
=> Stop immediately if there is a problem with Source

build/build.c, build/rpmfc.c
Also, emptying stdout if it was requested does not make sense when
command fails. Usually, if command fails, you still might want to see
the output and use it somehow.
References: https://github.com/rpm-software-management/rpm/issues/728
=> rpmfc: Return failures in rpmfcExec

lib/rpmlib.h
Pointed out in #724, including popt.h is in no way necessary for rpmlib.h
or using librpm in general, only the rpmcli API needs it.
=> Drop leftoever popt.h include from rpmlib.h

rpmspec.c
Commit d2f48e93d32e222d4727b9684d2032f9bb9fc498 moved the --target
argument to be global, but didn't completely remove the local target
variable from rpmspec.c, or the code that used it to trigger re-loading
the rpm configuration files (which is now handled by the global argument
callback in poptALL.c).
=> Remove unused target variable from rpmspec.c

sign/rpmsignfiles.c
Fixes, AFAICT, the --signfiles regression introduced in commit 8f8fe718413a4066ecc6718f92091d9e87a2d443 and clarifies the code a bit in a separate commit.
=> Fix --signfiles regression (#723)

tests/atlocal.in
A misconfigured DNS can cause bogus test-suite failures and hideous
slow-down for no reason of our own. Use a preset, predictable
buildhost name to avoid such issues.
=> Use a pre-determined buildhost in test-suite to avoid DNS usage

build/pack.c
When creating packages in parallel, more than one thread can call
this at once. As it's modifying global macro state to update file
name and line number, things will get garbled if we permit more than
one thread.
While this is necessary for the above reason, and should fix #742,
it shouldn't crash even without this so there's probably something
else wrong too.
Closes: #742
=> Only permit one thread at a time in addFileToTag()

build/pack.c
Getting header content in multiple threads is causing problems since it
can (and apparently does) change internal state.
=> build: Limit copying changelog one at a time

lib/rpmchecksig.c, lib/rpmcli.h
Commit a239ddefa90575ce80ed4436beb4005a97e32644 changed rpmpkgVerifySigs()
to accept fine-grained vsflags instead of query/verify style
nosignature/nodigest hammers, but rpmVerifySignatures() didn't get
updated accordingly. This will cause most unexpect behavior (in particular
in 4.14.x), for example QUERY_DIGEST which was used for disabling all
digest verification was defined as (1 << 19), which happens to be the same
as RPMVSF_NORSA which is how it would now be treated. Similarly confusion
with VERIFY_SCRIPT becoming RPMVSF_NODSA etc.
Just use the transaction verify flags instead, and mark the qva argument
as unused. It's an API change but that's okay in 4.15, and it's also an
explicit breakage at compile time (due to those DIGEST/SIGNATURE symbols
removal). In 4.14.x this is a …
=> Fix rpmVerifySignatures() passing garbage as verify flags in rpm >= 4.14

macros.in
The job killer introduced at 06953879d3e0b1e9a434979056d1225ab4646142
failed to take into account the fact that the processes *can* die between
us grabbing the pids and actually killing them, and that trying to kill
a non-existent process will cause a script running with -e to actually
terminate an error. So we end up failing a successful build by trying
to kill process that exited on its own, ugh :)
=> Don't fail build trying to kill a non-existent process (RhBug:1720143)

lib/header.c
We always allocate the index here as should be obvious from the code,
the condition is a leftover that might've been relevant in the turn
of the millenium but not anymore.
This construct confused clang into thinking there's a NULL pointer
dereference at the end of a long callchain (maybe because the indexlen
argument is signed so if you passed in -1 as indexLen... but fixing
those int32_t's is another story)
=> Drop bogus condition from header index allocation

scripts/find-debuginfo.sh
This is a request to add support for compressing annobin notes found in executable binaries built on Fedora and RHEL systems.
The annobin project adds a note section to binary files describing the security hardening features of how they were built.  Unfortunately these notes can get quite large, especially for projects that use lots of object files.  The objcopy program from the binutils package has an option to reduce the size of these notes by eliminating empties and merging duplicates.  If the binary does not contain any annobin notes then the objcopy will take no noticeable amount of time.  In fact even if the file does contain annobin notes the merging process is relatively fast and it is unlikely to add any significant amount of time to the overall build process.
=> Compress annobin notes

doc/manual/macros, rpmio/macro.c, tests/data/macros.testfile, tests/rpmmacro.at
There has been no way to add comments to multiline macros, and while
spec files technically support #-commenting at beginning of lines, it
does not apply to all sections and causes generation after generation
of packagers to stumble on the same items over and over: macros
are expanded within spec comment lines, which makes commenting multiline
macros such as %configure annoying, comments inteded for scriptlets
end up being in the previous scriptlets body, and numerous other quirks.
This implements the M4-inspired %dnl macro primitive which literally
discards everything until the next newline (or end of string), without
expanding the contents. This allows comments to be used inside multiline
macros and everywhere in spec.
Caveat: in some places such as %description the newline doesn't …
=> Implement %dnl (discard to next line) macro primitive for comment use

lib/headerfmt.c, rpmio/rpmsq.c
We've been treating thread local storage as if it were free parking, but it's actually a scarce resource and our use is causing python imports to fail in busy programs (RhBug:1722181)
The header format error return is unavoidable but we can just as well use a dynamically alloced TLS buffer, saving muchos TLS memory. The __thread uses in rpmsq don't make sense at all in reality, so better revert and rethink from scratch.
=> Fix excessive use of thread local storage (RhBug:1722181)

build/parseSpec.c, configure.ac
AC_OPENMP supports --enable/disable-openmp out of the box, but as it
only sets OPENMP_CFLAGS *if needed by the compiler to support openmp*,
it's utterly useless for conditional building. And because AC_OPENMP
doesn't set $ac_cv_prog_c_openmp to anything if --disable-openmp was
used, we need to test that it's neither empty nor unsupported to
determine if we actually have openmp, in order to set an autoconf
define that we can actually use to conditionalize aspects of the
build on. Argh.
=> Fix build with --disable-openmp

lib/rpmdb.c
The code that makes use of the index set does a manual sort
call, so having a wrong value did not cause harm in the past.
=> Clear the "mi_sorted" flag when adding to an index set

lib/psm.c
This brings the code in sync with checkProblems() fixing errors
that happens when an erase element exists for an install of a
package with an identical NEVRA.
Use "rpm --reinstall --replacepkgs" to reproduce on the command
line.
=> Use a rpmtsPrunedIterator iterator in markReplacedInstance

build/files.c
Commit ee3126dd3d4ca609f254ac5d647c9ff3e413e9dd added an innocent
looking check to ban characters below < 0x20, but char is signed
so it ends up banning the whole upper range too. Cast to unsigned
and add a comment as a reminder. Thanks to Michael Schroeder for
pointing this out!
Fixes ee3126dd3d4ca609f254ac5d647c9ff3e413e9dd
=> Watch out for char signedness when checking for printable

build/build.c
Closes: https://github.com/rpm-software-management/rpm/issues/760
=> rpmbuild: Generate src.rpm with dynamic BRs with --force

build/spec.c, macros.in
Since b8a54d6a1e9bb6140b6b47e23dc707e4b967537e, when `SOURCE_DATE_EPOCH` is set, `RPMTAG_BUILDTIME` winds up being set with that value. This is not always desirable, particularly if you are using the build time for filters and evaluation in certain types of package release pipelines.
This is an adaptation of the downstream patch in SUSE's rpm package written by @mlschroe intended to address [SuseBug:1087065](https://bugzilla.suse.com/show_bug.cgi?id=1087065) (private bug 😢).
=> Do not set RPMTAG_BUILDTIME to SOURCE_DATE_EPOCH when defined by default

build/files.c
In case of #776 the added rpmbuild error looks:
error: Can't read content of file: /home/tester/reps/776/zdroj/776/tests/testing/build/BUILDROOT/h-1.0-1.x86_64/etc/foo/bar
=> Raise an error if reading a file during rpmbuild fails (#776)

build/parseSpec.c, tests/Makefile.am, tests/data/SPECS/ifmultiline.spec, tests/rpmmacro.at
Trailing '\' after multiline conditionals or %include will be trimmed.
After the patch lines like:
%if 1 && ( 2 || \
3 )
%endif
will be parsed correctly. The other lines stay unchanged.
A test is added.
=> Parse multiline conditional and %include parameters correctly (#775)

build/build.c
Fixes: https://github.com/rpm-software-management/rpm/issues/781
Reported-by: Michael Schroeder <mls@suse.de>
=> rpmbuild: Generate buildreqs.nosrc.rpm even if no output

lib/depends.c, lib/rpmte.c, lib/rpmte_internal.h, lib/transaction.c, lib/verify.c, tests/rpmdb.at
Rpm used to rely on the "replacepkgs hack" to get rid of the old
header entry when reinstalling a package. This has a number of
problems when the headers are not identical or different
install flags were used.
To mitigate this, a '--reinstall' option was added that made rpm
use an erase element in this case.
This commit takes this one step further by changing the code to also
use an erase element in the --upgrade case. The code is mostly simpler,
but we need a different implementation for commit fd40d58efa, as we now
have erase elements both for --reinstall and --upgrade. Thus we
need to store the addop in the transaction element.
The commit does not change the behaviour of 'rpm --install'.
=> Use an erase element to delete packages with same NEVRA

lib/transaction.c
Found during RhBug:1714657 QA testing.
In addition, add a comment to clarify the fallthrough as intentional.
=> Fix memleak during transaction verify step in the NOKEY case.

macros.in
If I didn't screw this up, it should help with #798.  It just pulls the `V=1 VERBOSE=1` bit out to a separate macro to make it easier to override.
=> Split verbose make flags to a separate macro

tests/Makefile.am, tests/data/SPECS/weirdnames.spec, tests/rpmbuild.at
Being C, rpm itself can typically handle pretty much anything you throw at it, but the surrounding scripts are much more fragile. The notable exception is the dependency generator which whose "API" specifically uses newlines to separate filenames.
This fails on brp-strip-static-archive  since commit fc2c986d8f5e4174885ae377750185339636f062
=> Add a testcase for filenames with special characters in them

rpmio/rpmpgp.c
Currently a PGP public key file which does not have any end-of-line character(s) at end of file, but is valid otherwise, is not considered valid by rpmio.
This change adds a special-case for the string terminating null byte right after the terminating `-----` of the `END PGP` header.
=> rpmio: Handle EOF without EOL better at END PGP in rpmpgp.c

macros.in, platform.in
This was only added in commit 2bb7b0cf066c97a9d92eb0bf59618896000cb29d,
but turns out that this kind of usage is bad for build reproducability
because the system-specific CPU count gets recorded RPMTAG_OPTFLAGS
and the resulting binaries too (depending on gcc flags).
In addition, gcc upstream has decided to make -flto default to
autodetected parallelism. Since -flto can be overridden with
by simply appending -fno-lto for the packages that need to disable it,
there's no practical need for us to provide such a macro for disabling
either.
=> Drop %_lto_cflags macro afterall

build/parseDescription.c, build/parseScript.c, tests/Makefile.am, tests/data/SPECS/mini.spec, tests/rpmbuild.at
More ripples from the parseLines() unification, the callers used to
explicitly allocate an empty string buffer, but with lazy allocation
from parseLines() they're getting NULL in the special circumstance of
being last in the spec, and no "body". Specifically this happens with
empty %description or scriptlet without a body, eg
"%post -p /sbin/ldconfig".
The script regression report + reproducer and a preliminary patch
originally from RhBug:1732276 by nvwarr.
=> Fix segfault regression on empty script or description at end of spec

ci/Dockerfile
This doesn't do anything at all in itself because all the repositories
have gpgcheck=1 by default. However adding this line allows disabling
the gpgcheck for individual builds via Semaphore build settings, which
allows us to deal with signatures on rawhide breaking twice a year
causing our builds to appear failed for no good reason.
=> Add a dummy line to CI setup to allow controlling dnf gpgcheck per build

scripts/brp-compress, scripts/brp-java-gcjcompile, scripts/brp-python-bytecompile, scripts/brp-python-hardlink, scripts/brp-strip, scripts/brp-strip-comment-note, scripts/brp-strip-shared, scripts/brp-strip-static-archive, scripts/check-buildroot, scripts/check-rpaths, scripts/find-debuginfo.sh, scripts/find-lang.sh, scripts/gendiff, scripts/rpm2cpio.sh, scripts/rpmdb_loadcvt, scripts/tgpg
It corrects warnings  [SC2166] spotted by covscan:
warning: Prefer [ p ] && [ q ] as [ p -a q ] is not well defined. [SC2166]
warning: Prefer [ p ] || [ q ] as [ p -o q ] is not well defined. [SC2166]
Motivated by last the comment in #802. This should fix all [sc2166] warnings spotted by covscan on RPM version 4.14.2.
=> Prefer '[] && []' to '[ -a ]' and '[] || []' to '[ -o ]' in tests

build/build.c, build/files.c, build/rpmbuild_internal.h, build/rpmfc.c
Commit 18e8f4e9b2dd170d090843adf5b5084658d68cf7 and related changes caused us to capture and re-emit stdout of all build scriptlets, whether we actually use the output for anything or not. Besides doing a whole bunch of work for nothing, this can disrupt the output of build scriptlets by making the output jerky and out of order, at least inside mock and other tools which in turn grab rpm output. This makes troubleshooting failed builds unnecessarily hard for no good reason.
Handle the whole thing in a different way: on regular builds, don't capture anything where we don't actually need to. This restores the natural flow of output. We still need to somehow handle quiet builds though, and we can't use redirect to /dev/null from %___build_pre like we used to, because dynamic buildrequires …
=> Restore strict order of build scriptlet stdout/stderr output (#794)

scripts/find-debuginfo.sh
There's code setting variable id in scripts/find-debuginfo.sh, but there's no
subsequent use.  The only use of $id in the script is in do_file, where it is
a local variable.
The variable setting was introduced in commit 6b3b435fa "Add dwz debuginfo
compression support" in combination with a subsequent make_id_link using the
variable, but the make_id_link was removed in commit bbfe1f86b
"Add build-id links to rpm for all ELF files".
Remove the unused variable.
=> Remove unused variable id in find-debuginfo.sh

macros.in, tests/rpmbuild.at
Non-gzip compression introduces extra dependencies to packages, force gzip compression on the dependency generation test to avoid basically false failures. This lets us run the test-suite with other compression methods as needed (but not changing any defaults here)
Also document zstd compression in macros file.
=> Make dependency generation test payload-compression agnostic

build/parseSpec.c, platform.in
On 32bit plaforms, address space is easily exhausted with multiple threads, causing arbitrary builds failure regressions (RhBug:1729382). Simply cap the number of threads to maximum of four on any 32bit platform to play it safe. It's still three more than we were able to use on older releases...
In addition, introduce a separate tunable for tweaking the maximum number of threads just in case, defaulting to max CPUs available.
This is a stopgap solution to the 32bit arch build regressions in 4.15.x (RhBug:1729382) that is simple and straightforward enough for 4.15.0. The more elaborate heuristics suggested in PR #821 need more time for discussing, tweaking and testing than we have right now.
=> Cap number of threads on 32bit platforms, add a tunable (RhBug:1729382)

rpmio/expression.c
If the expression after '%{expr:' is mutiline like:
%{expr: 0 || 0 ||
0 || 0 |o| 0 ||
0 || 0 || 0 }
then it is better not to support marker pointing to the exact
place of the error.
=> Rip the marker support for multiline %{expr:...} error messages

doc/manual/queryformat
- in a majority of examples in manual the text after the --queryformat
argument is in  double quotes - thus it does not look good to wrote
that "A query format is passed to RPM after the --queryformat
argument, and normally should be enclosed in single quotes".
- in case of:
rpm -qa -i --queryformat "%{NAME} %{SIZE}\n"
-i is not ignored, so this is omitted in the text.
- language correction
- added name of file with the list of all formatting tags,
- package dev is not reachable now, so replaced by nss,
all tags are now written in capital letters,
%{FILEVERIFYFLAGS:hex} looks better then %{FILEVERIFYFLAGS}
=> Correct and update Query formats documentation

INSTALL, Makefile.am, ci/Dockerfile, configure.ac
libgcrypt is a much more straightforward and lightweight as a library,
doesn't come with a massive runtime library of its own, runtime which
messes with SIGPIPE and all, has a nice clearly compatible license (LGPL)
and is somewhat faster than NSS. What's not to like?
Change the default and add relevant documentation to INSTALL. Drop
the hopefully now unnecessary override from distcheck flags, and
switch CI over too.
=> Change the default crypto implementation to libgcrypt (from NSS)

rpmio/expression.c
Expressions like '5 +' did not print an error message before.
=> Print an error for expressions with missing operands

rpmio/expression.c, tests/rpmbuild.at, tests/rpmmacro.at
Identifier expansion got broken in 2000 when getMacroBody() was
removed from the API (commit 3ad99fcba52fcc5e8ab636d2f1760c945cdfbf19).
Nobody seemed to have noticied, so it's safe to say that there is
no one that used it the intented way.
With the bad commit there is an unintended use for it: it is
a way to specify a string without the otherwise needed quotes.
So this commit might break some existing spec files, but cleaning
those up is easy and makes the world a better place.
=> Remove TOK_IDENTIFIER support from expression parsing

rpmio/expression.c
The %if lines in the specfile are expanded before the expressions
get evaluated, so the re-expansion of strings is surprising.
It's also not done for integers, which makes it inconsistent.
The original expression parser seems to have been written
without taking the upfront expansion into account, thus the
string expansion and the TOK_IDENTIFIER code.
As I can't imagine anybody using this feature lets just drop it.
=> Stop expanding strings in the expression parser

plugins/systemd_inhibit.c
The inhibition lock warning message is output in single-user mode
due to absent of dbus service. I suppress the warning message because
the "inhibit" operation may not be needed in this mode and the message
just confuses users.
=> Suppress inhibition lock warning message in single-user mode

rpmio/expression.c, tests/rpmmacro.at
v1 gets double-freed when there's an error parsing the result side
of the ternary operator. Add testcases to go, one that catches the
actual error and another which serves to demonstrate that the false
branch doesn't get parsed at all, errors or no.
=> Fix double-free on ternary operator parsing error

build/files.c, tests/Makefile.am, tests/data/SPECS/docmiss.spec, tests/rpmbuild.at
Fixes regression from commit 1ba05a7456aafb52e89df5dd42d494d09f9ea6a4
where doc files always terminate build regardless of the macro value.
Add a testcase to go.
Fixes #807
=> Resurrect %_missing_doc_files_terminate_build functionality

rpmpopt.in
This adds all of the rpmbuild popt aliases that expand to defines to
rpmspec as well.
It also changes --trace to include --POPTdesc argument help.
Signed-off-by: Peter Jones <pjones@redhat.com>
=> Add all of the rpmbuild macro aliases to rpmspec as well

build/parseSpec.c, doc/manual/macros, rpmio/Makefile.am, rpmio/expression.c, rpmio/macro.c, rpmio/rpmmacro.h, rpmio/rpmmacro_internal.h, tests/rpmmacro.at
This adds %[ expr ] as a new means to do expression expansion in rpm. Unlike %{expr:} the expression is expanded in the parser, so we are safe against expansion results messing up the syntax and also can to short-circuiting.
=> Support new %[ ] expression expansion syntax

rpmio/expression.c
Also reduce the number of alloc/free calls by adding ValueSetXXX()
variants that change a value.
=> Free memory leak in unary op handling

doc/manual/macros
I looked into rpm/doc/manual/macros to check 0 and 1 added into the builtinmacros[] in PR #853. Values added in PR #853 are correct, but description of macros %verbose and  %getconfdir  in manual is confusing. So that is why I created this PR.
=> Correct description of %verbose and %getconfdir in the macro manual

rpmio/expression.c, tests/rpmmacro.at
This commits change the handling of the logical operators. It allows to use strings as condition and also changes || and && to return the last evaluated term like in perl/python/ruby.
Fixes #852
=> Logical op improvements

lib/psm.c, lib/rpmtriggers.c, lib/transaction.c
The primary motivation here is to consolidate all database accesses
on one side of the chroot, currently it happens on both sides of the
border causing all sorts of issues and limitations (such as preventing
us from using more advanced modes of databases).
As a positive side-effect, the sections where we potentially run
inside chroot are more easily identifiable.
Consolidating on the outside may seem counter-productive, to improve
security it seems you'd want to spend as much time *in* as possible,
including database accesses. Unfortunately due to rpm's access patterns
and API promises, that's not really achievable (tried several approaches,
run into as many dead-ends).
Technically we could localize the chroot placement much further, but
doing so would change the side for transaction …
=> Localize our chroot in/out operations to minimize time spent inside

lib/rpmprob.c
These messages have been an endless source of confusion and complaint
throughout their existence, to the point that various programs have added
their own "translation" for these messages. Changing the message is likely
to break those (regex-based) translations but then hopefully the
translations will not be needed after this.
Fixes #879 (and at least a dozen bugs in various distro bugzillas
whose numbers I'm too lazy to dig up)
=> Clarify the disk space problem messages

build/rpmfc.c, tests/Makefile.am, tests/data/SPECS/shebang.spec, tests/rpmbuild.at
Ignoring the error code from rpmfcHelper() means that invalid dependencies
get silently ignores. Intentionally not stopping at the first error though,
as it's often useful to get all errors at once.
Add testcases for legal and illegal output from dependency generator.
Fixes #881
=> Percolate errors up from rpmfcHelper()

build/build.c, tests/rpmbuild.at
Mark dynamically generated buildrequires autogenerated to make them in line with other autogenerated dependencies, this also makes the parseRCPOT() error reporting work.
Also stop on invalid generated dependencies.
Fixes #801
=> Fix dynamic buildrequire error handling

lib/rpmliblua.c, rpmio/rpmlua.c, rpmio/rpmlua.h
rpmlua.h was originally written in a way that allows it to be included
regardless of whether Lua is actually enabled in rpm or not, or where
Lua headers are, specifically to isolate the rest of rpm from these
details. That was changed in commit 62bd62286aa888c60145daf315a938dd87eadc89
when <lauxlib.h> started getting included in rpmlua.h, which leaks to
places like librpmbuild which do not directly use Lua.
The way Lua typedef's the luaL_Reg struct to itself defies my C fu for
for handling this in some nicer typesafe way, fix this all by just using
a void pointer instead, this is just an internal API where buyer can be
expected to beware.
Fixes #888
=> Avoid using types from Lua includes in rpmlua.h again

build/files.c, build/pack.c, build/rpmbuild_internal.h, tests/Makefile.am, tests/data/SPECS/scriptfile.spec, tests/rpmbuild.at
Support for -f is not limited to %files, so it makes sense to have a common helper to do it. Inspired by the third such case to be added in #874 .
=> Refactor aux file reading (%files -f manifest etc) to a common helper

build/parsePrep.c
If we don't want spec->buildSubdir to be set, then we should just bail
out before the logic that sets it, not undo it afterwards and set macro
body to NULL, amazing that this isn't blowing up someplace.
Lastly, %setup -a/-b would try to access tarballs that build-in-place
is supposed to skip entirely, just skip the whole argument checking
instead as they're not going to be used anyway.
=> Cleanup + fix --build-in-place handling in %setup

lib/rpmtriggers.c
This is part II of commit 6d610e9b9a906548ce44265d7f36199441ea8bca which
missed one but common case where the element with matches gets passed
to the callback instead of the owning one, as pointed out in RhBug:1724779.
=> Always execute file trigger scriptlet callbacks with owning header

ci/Dockerfile, configure.ac
This adds a configure option to cleanly enable -Werror in builds, and enables it for CI, hopefully for obvious reasons.
=> Enable -Werror in CI builds

plugins/systemd_inhibit.c
Turns out this isn't a safe thing to do, as an API user could have
their own dbus connections in the same process and shutting those
down is a rather impolite thing to do (and causes crash, burn and
other injuries, eg RhBug:1750575)
This reverts commit d5f201345f6d27b6280750e5c6502f4418614fbc.
=> Revert "Fully shutdown DBUS on systemd_inhibit cleanup (RhBug:1714657)"

lib/backend/lmdb.c
The mapsize in LMDB is a limit of the DB size. It's set to 256M now, and if the DB reaches this size, rpm operations fails with:
---
error: lmdb:    rc(-30792) = mdb_cursor_put(): MDB_MAP_FULL: Environment mapsize limit reached
error: rc(-30792) adding header #31959 record: MDB_MAP_FULL: Environment mapsize limit reached
---
In my case, it was next to it, and it was failing on updating an RPM with 34.5K of files (as during update it should store data for the old and new files both).
Increase the size of the DB to 1GB, it should cover most of use cases now, but we should probably come up with a better solution in the future, if we decide to use this DB.
=> Increase lmdb DB size from 256M to 1G

lib/backend/dummydb.c, lib/backend/ndb/glue.c
ndb doesn't implement a specific verify option, but that doesn't mean
the data within should be considered invalid. This causes ndb to fail
the test-suite on "rpmdb --rebuilddb and verify empty database" for no
good reason. Similar arguments could be made for dummydb although it
matters much less there.
=> Don't report unimplemented db ctrl and verify ops as errors

lib/backend/db3.c, lib/backend/dbi.c, lib/backend/dbi.h, lib/backend/dummydb.c, lib/backend/lmdb.c, lib/backend/ndb/glue.c, lib/backend/sqlite.c, lib/rpmdb.c
This is early steps towards uprooting the internal db API from its Berkeley DB origins - what makes sense with BDB/LMDB can be a huge hindrance with other types of backends.
The general plan is towards eliminating the generic, vague cursor object from the internal API and replace with iterator(s) on the backend level, and pushing operations further into the backend. 
This is only an RFC until the sqlite backend (#899) is merged (and will obviously need to be updated after that)
=> Push some add/del rpmdb logic deeper into backends

build/parseSpec.c
In 464d21dc8c176222c6586e2ee503fec6207f0d29, support for building RPM
without OpenMP was conditionalized on the `ENABLE_OPENMP` define being
set by the compiler. However, the include statement for omp.h in
parseSpec.c was not conditionalized as everything else was.
Because the conditional was previously missing, RPM fails to build
in environments where OpenMP is completely unavailable. This is the
case in environments such as macOS, as Clang does not provide an
OpenMP implementation there.
=> build: Add missing ifdef to conditionalize omp.h include statement

lib/backend/db3.c, lib/backend/dbi.c, lib/backend/dbi.h, lib/backend/dummydb.c, lib/backend/lmdb.c, lib/backend/ndb/glue.c, lib/backend/sqlite.c, lib/rpmdb.c, lib/rpmdb.h, macros.in
Okay okay, maybe not...
Add name and path members to backend db_ops struct, use them for configuring and detecting, and misc related tweaks.
Started doing this for implementing rpmdbStat(), but got stuck wondering about the API: my initial version requires an open rpmdb for stat'ing, which limits its usefulness. Perhaps there should be separate calls for an open database and non-open one, just like there's fstat() and stat(). Thoughts?
=> Make database backends self-aware

lib/query.c, tests/rpmdb.at
RPMDBI_PACKAGES differs from the indexes in how record searches behave, indexes return NULL for non-existent values but with RPMDBI_PACKAGES (and the pseudo index LABEL) we always get an iterator which we need to walk to determine whether there's data or not. Use the newly introduced helper to get the query return right.
One could argue that this should be done in the database code, but then the behavior is kinda consistent other iteration over RPMDBI_PACKAGES: you don't know how many, if any, matches there are until you walk it.
=> Fix --querybynumber on non-existent record, add test

build/build.c, build/reqprov.c, lib/psm.c, tests/rpmbuild.at
Details in the commit messages, executive summary:
- Packages are not permitted to provide rpmlib() capabilities, so don't (the use-case is covered by other means)
- src.rpm requires are generally build-time requires, rpmlib() is the odd man out. Mark build-time rpmlib() dependencies with MISSINGOK to allow install-time to skip them.
This replaces the earlier PR #878. Original issue reported at https://pagure.io/copr/copr/issue/1038
=> Fixes to rpmlib(DynamicBuildrequires) dependencies

configure.ac, lib/formats.c, lib/query.c, lib/rpmchecksig.c, rpmio/rpmkeyring.c, rpmio/rpmpgp.c
LGTM pointed out localtime() and ctime() are not thread-safe, and additionally ctime() is considered obsolete since POSIX.1-2008. Replace with localtime_r() and strftime() instead. 
Long broken --prtpkts debug switch is fixed in a separate commit to have means of testing the strftime() change.
=> Eliminate uses of non-threadsafe locatime() and ctime() functions

lib/headerfmt.c, tests/rpmquery.at
Previously, we assumed a backslash character would always be followed by
a character to be escaped, and advanced our "start" pointer by two
places before the next iteration.  However, this assumption breaks if
the lonely backslash happens to be the last character in the query
string, in which case we would end up pointing beyond the \0 and let the
parser wander into the unknown, possibly crashing later.
This commit ensures we detect this corner case and error out gracefully
with a message.
=> Handle incomplete escape seq in queryformat (RhBug:1755230)

lib/backend/sqlite.c, tests/rpmdb.at
Misc improvements:
- handle DBI_CREATED flag correctly for all tables in sqlite (for automatic index rebuilds)
- let sqlite handle header number allocation (for less overflow-prone algorithm, at least in theory)
=> Sqlite improvements

build/pack.c, build/parsePreamble.c
Commit e68eb68c4a6c3635b8cf58a05277f7da49058d16 introduced a regression
on Icon tag causing a crash on source rpm build, due to spec->numSources
being off by one if an icon was present.
A nicer fix would be eliminating numSources entirely but it's not as
easy as it should be due to dynamic buildrequires messing with it,
leaving that for another time.
The second commit fixes an unrelated, recently introduced memory leak.
=> Fix Icon tag crash on src.rpm build, regression in 4.15.0 (RhBug:1769579)

build/build.c, build/spec.c, tests/rpmsigdig.at
Commit fa303d5ba6bef5b4a44b884c6dadadc27b594caa moved buildhost and
buildtime calculation out of the package generation to early spec
initialization, but this broke reproducable builds: if buildtime is
to be set from changelog, changelog needs to be parsed first.
So either we need to do it twice or we need to do it right, and
besides avoiding duplication, conceptually these values are only
meaningful during a build and not a parse, so this restores that part
of the original code while keeping things thread-safe.
Fixes: #932
=> Only calculate buildhost and buildtime during an actual build

build/rpmfc.c
The order of file classification isn't interesting in itself, but arbitrary
order makes contents of RPMTAG_CLASSDICT non-deterministic which is not
nice for reproducable builds. Tell OMP to handle the class dictionary
in order.
Cancellation points are not allowed in ordered construct so we need to
drop that. It doesn't change the actual results, just means that we  run
a little longer in case errors are encountered.
Fixes #934
=> Preserve processing order in file classification

configure.ac
libgcrypt from 1.8.5 provides a pkg-config file as well as the traditional
libgcrypt-config script.  As pkg-config is more resiliant in the face of
complicated build environments (for example cross-compilation and sysroots)
prefer the pkg-config file, falling back to libgcrypt-config if that doesn't
exist.
=> configure.ac: prefer pkg-config to find libgcrypt

build/rpmfc.c
Store the file type strings in the classifier, and generate the dictionary and its ids serially after the parallel section completes to ensure stable order. Besides making the classifying really run in parallel again, this also moves the pool- and file-counting related constraints out of the parallel section for theoretically better parallelization.
This is an alternative fix to #934, using omp order clause simply made the classification run serially.
=> Generate file class dictionary after file classification for stability

lib/backend/sqlite.c
Postpone sql index creation until closing time on database rebuilds,
this is more than 50% improvement on rebuilddb time on both SSD and
traditional disks.
=> Optimize sqlite database rebuild

scripts/brp-strip-static-archive
as it is not POSIX compliant and not supported on BSD and others
Dropping the use of grep here and using -regex of find instead to get rid of
the need for looking at lines terminated by newline.
Using only basic regular expressions for portability.
Resolves: #948
=> brp-strip-static-archive: Do not use xargs -d

scripts/find-debuginfo.sh
Use -0 instead which is more widly available.
Related: #948
=> find-debuginfo.sh: Dont use xargs -d for portability

rpmio/digest_libgcrypt.c
If we're using libgcrypt for hashing we need to initialise libgcrypt, otherwise
it will crash when used in parallel packaging runs.
Fixes #968
=> rpmio: initialise libgcrypt

lib/backend/db3.c, lib/backend/lmdb.c, lib/backend/ndb/glue.c, lib/backend/sqlite.c, lib/depends.c, lib/rpmdb.c, lib/rpmdb.h
rpmtsCheck() builds some hashes over rpmdb keys, whose buildup is barely measurable in normal install/update/erase transactions, but when repeated thousands of times during rpm -Va, things start adding up. Add a new interface to avoid fetching tonnes of unused data and use it. More details in the commits.
=> Add a key-only rpmdb iterator to optimize rpmtsCheck()

plugins/selinux.c
We already filter out -EOPNOTSUPP and return OK, but the message was
getting logged before the filtering so we'd spit out spurious error
messages on filesystems that don't support SELinux (RhBug:1777502)
=> Silence spurious error message from lsetfilecon() on -EOPNOTSUPP

rpmio/rpmfileutil.c
I spot it while adding support for zstd compressed metadata in
URPM/urpmi, which was broken by this typo
typo introduced in commit 3684424fe297c996bb05bb64631336fa2903df12
This fixes issue #990
=> fix zstd magic

scripts/pythondistdeps.py
Fixes https://github.com/rpm-software-management/rpm/issues/995
For this input: pyparsing>=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6
Instead of (invalid):
(python3.8dist(pyparsing) >= 2.0.1 with
python3.8dist(pyparsing) < 2.1.2 or python3.8dist(pyparsing) >= 2.1.2.0 with
python3.8dist(pyparsing) < 2.1.6 or python3.8dist(pyparsing) >= 2.1.6.0 with
python3.8dist(pyparsing) < 2.0.4 or python3.8dist(pyparsing) >= 2.0.4.0)
Produces (valid):
(python3.8dist(pyparsing) >= 2.0.1 with
(python3.8dist(pyparsing) < 2.1.2 or python3.8dist(pyparsing) >= 2.1.2.0) with
(python3.8dist(pyparsing) < 2.0.4 or python3.8dist(pyparsing) >= 2.0.4.0) with
(python3.8dist(pyparsing) < 2.1.6 or python3.8dist(pyparsing) >= 2.1.6.0))
For this input: babel>=1.3,!=2.0
Instead of (invalid):
(python3.8dist(babel) >= 1.3 with …
=> Python dist deps: Put bounded requirements into parenthesis

lib/rpmplugins.c
This is the recommended way in the manpage; if there is
a lingering error from an unrelated dl*() call that was
never obtained via dlerror(), it needs to be cleared
prior to calling dlsym().
=> rpmplugins.c: call dlerror() prior to dlsym()

ci/Dockerfile
BDBD, LMDB and SQLite were already implicitly enabled via build
dependencies, but NDB build has not been enabled at all.
Came up when discussing read-only BDB in #980.
=> Explicitly enable all our database backends in CI

lib/signature.c
The generic case was reported in #270 and fixed quite a while ago in
commit 34c2ba3c6a80a778cdf2e42a9193b3264e08e1b3, but signing uses a
different code path and require the same treatment.
Fixes: #1002
=> Don't require signature header to be in single contiguous region part II

lib/backend/ndb/glue.c, lib/backend/ndb/rpmpkg.c, lib/backend/ndb/rpmpkg.h
This commit adds a verify method for ndb's Packages.db database.
It also cleans up the pkgdb code a bit:
* removed unused lzo compression code
* added some more comments and fixed spelling mistakes
* made "ordered slots" flag a boolean
* fixed a corner case where a package id lookup could segfault
if no packages were in the database
* no longer free the pkgid hash all the time
=> ndb: add verify method and cleanup code

ci/Dockerfile, configure.ac, lib/Makefile.am, lib/backend/bdb_ro.c, lib/backend/dbi.c, lib/backend/dbi.h
This commit implements a slow read-only backend that allows
accessing of BerkeleyDB databases without using the BerkeleyDB
library. The code supports btree version 9 and hash version 8
and 9.
There are two use cases for this:
1) Conversion of an existing BerkeleyDB to a different
backend.
2) Allowing package scriptlets to do database queries while
in a transaction that replaced rpm with a version that
no longer links against BerkeleyDB.
Currently prefix searching is not supported (but it would be
easy to add).
=> Add support for reading BDB without the library

scripts/find-debuginfo.sh
Submitting on behalf of Denys Vlasenko:
For kernel build, "${LISTFILE}.dirs.sed" is debugfiles.list.dirs.sed
and it contains 1782 lines of sed script.
It is applied to two files, both are about 4450 lines long.
This is slow (~30 seconds) because of ~16 million regex matches
performed by sed.
But we don't need or want regex match here
(and it's buggy, since dots in pattern match will be treated
as "any character", which is wrong here. For example,
/usr/lib/debug/lib/modules/5@4@0-0@rc7@0@fc31@test@x86_64/vdso/
would match
/usr/lib/debug/lib/modules/5.4.0-0.rc7.0.fc31.test.x86_64/vdso/
pattern, but it should not).
This change performs matching using shell string comparison ops.
For kernel build, this change results in run time of about one second.
Signed-off-by: Denys Vlasenko …
=> find-debuginfo.sh: speed up %dir generation

macros.in
I find %autosetup -S git very hard to use when a patch needs updating for a new release of a project.  This gives us the standard patch behavior of applying what it can and giving .rej files for what it cannot.  I don't know how far back the --reject argument is valid, but it at least appears to be present in git 2.3.3: https://git-scm.com/docs/git-apply/2.3.3
=> Use git apply --reject to assist with modifying patches

lib/backend/ndb/rpmxdb.c
=> ndb: fix ftruncate return value warning

build/parseSpec.c, tests/data/SPECS/foo.spec, tests/rpmspec.at
Since requires in source rpms are buildrequires, with the same logic
provides in source rpms are buildprovides, and what does a build
provide if its not the names of the packages to be generated.
This seems like a natural fit, should be useful for various purposes, and
eliminates the need for a special rpmspecQuery() with RPMQV_SPECBUILTRPMS
to get that information.
=> Add NEVR provides for all packages that would be built into source rpms

doc/manual/macros, rpmio/macro.c
I fail to see how this is useful functionality to anybody:
$ rpm --eval "%{F:foo}"
filefoo.file
=> Drop useless %{F:..} built-in macro

lib/rpmdb.c
Introduced in commit 27ea3f8624560bd158fc7bc801639310a0ffab10, the
wrong header is being added in case of v3 packages.
Fixes: #1017
=> Fix regression on v3 package handling on database rebuild

COPYING
As the code in the rpmio sub directory was split out of the lib sub dir
it is already under LGPL as "code derived from" "the source code in the
lib subdirectory" according to the license. But not having the sub directory
mentioned in the license confuses users and contributers.
So this change does not change the license of any code but only clearifies the
current situation.
Resolves: #516
=> Explicitly mention that the rpmio/ sub dir is under LGPL

plugins/systemd_inhibit.c
Commit 708e61307bc3fd027b016fdf5a1d1a5274c1843c introduced a memory leak
on the error object: if the message is suppressed then the error object
is never freed. Test for the suppression conditions separately to fix.
=> Fix a minor memory leak on suppressed inhibition lock warning message

scripts/check-files
busybox diff use different output format: '+' and '-' instead '> ' and '< '
=> Make check-files compatible with busybox diff 

rpmpopt.in
When splitting rpmsign from rpmbuild this command line parameter was kept
as an popt alias. But this limits what other parameter can be passed to
the rpmsign command in a difficult to understand way. In the end everyone
is better off using the rpmsign command directly.
Issue a error message stating the parameter is no longer supported
Resolves: #153
=> Remove --sign from rpmbuild

macros.in
This PR renames the `%arm` macro to `%arm32` and adds an `%arm64` macro as a simple alias for current and future 64-bit ARM architectures. This makes it consistent with other architectures we have, such as MIPS, POWER, and x86.
In order to maintain legacy compatibility, the `%arm` macro still exists as an alias for `%arm32` to prevent _massive_ breakage across Linux distributions that use it for ARM architecture handling.
=> Small updates to the ARM macros

build/parseDescription.c, build/parseFiles.c, build/parsePolicies.c, build/parsePrep.c, build/parseScript.c, build/policies.c
popt always returned malloc'ed memory for POPT_ARG_STRING items, but
for whatever historical reason rpm systematically passed const char *
pointers as targets, making them look non-freeable. Besides changing
just the types and adding free()'s, const-correctness requires extra
tweaks as there's mixed use from string literals and poptGetArg() which
does return const pointers.
=> Fix POPT_ARG_STRING memleaks in librpmbuild

macros.in
This makes it easier to reference all RISC-V architectures supported by RPM in the same way that ARM and POWER architectures are.
Like ARM, RISC-V has a lot of subarchitecture variants, so having the structure in place to be able to reference all of them easily will be very useful in the near future.
=> Add architecture macro for all RISC-V processors

build/policies.c
Commit 307872f71b357a3839fd037514a1c3dabfacc611 broke build with
SELinux enabled but was accidentally merged. Fix the breakage.
=> Fix build regression in commit 307872f71b357a3839fd037514a1c3dabfacc611

lib/rpmplugins.c, system.h
It is needed in lib/rpmplugins.c only anyway.
=> Move <dlfcn.h> out of system.h

lib/rpmds.h
isUnorderedReq() returned True as soon as any qualifier that does not
require ordering is passed. But some qulifiers - basically the scriptlets
run during installation and erasure of the package - may still require
the dependency to be taken into account during ordering.
Now isUnorderedReq() returns 0 if any of those are also set.
Resolves: #1030
=> Fix isUnorderedReq() for multiple qualifiers

platform.in
This change ensures that any existing buildroot contents are wiped
and a fresh empty one is created for usage in `%install`.
Variations of this exist in virtually every RPM-based Linux distribution
for more than a decade. At this point, it is expected behavior everywhere
and it is amazing that it has not yet been put in RPM itself until now...
Credit goes to Michael Schroeder from openSUSE for the original work
and Tom Calloway for the variant adapted for Fedora that is the basis
for this change.
=> platform: Ensure empty buildroot for %install

rpmio/macro.c, tests/rpmmacro.at
Fix double-expansion of arguments to built-in macros (except for %{expand:..} whose sole purpose is to double-expand) refactoring the more special cases out of doFoo() and fixing misc other related bugs in the process. Details in the individual commit messages.
=> Bunch of macro fixes and cleanups

build/files.c, build/parseFiles.c, build/parsePrep.c, build/parseSpec.c, rpmio/macro.c, rpmio/rpmmacro.h
This adds a ME_NOEXPAND macro flag that turns off body expansion.
This is much simpler than the weird % character doubling. It's also a bit faster
because there's less calls to expandMacro().
=> A saner way for marco argument escaping

build/rpmfc.c, rpmio/macro.c, rpmio/rpmmacro.h, tests/rpmbuild.at
In some cases generators are remarkably simple, such as just echoing back the basename of the file in some namespace such as foo(lib.so), and forking out a shell to perform such a mundane task is both hideously slow and plain dumb, when we have quite some string processing facilities and even a full-blown programming language embedded in rpm itself.
This adds support for using macro functions as generators: if the generator macro is a parametric macro, then we call that macro with the file name as the first argument instead of shelling out, and the expansion of the macro is used as the output. Multiple lines in output are allowed, and generator styles can be mixed freely (eg shell out for provides but use macro function for requires etc).
=> Add support for macro-only dependency generators

lib/query.c, rpmspec.c
Parsing a spec, even unsuccessfully, will affect the global macro
state in any number of ways that may affect the following operations
in unpredictable ways. Lacking any saner way to do this, reset the
entire global macro state after each spec parse in rpmspec and spec
query code (rpmbuild already does this) while maintaining possible
cli-specified target and rcfile.
=> Reset global macro state after each spec query/parse

lib/fsm.c
It gets only written to and nobody uses it, so be gone.
=> fsmMkdirs: Remove dnlx array

doc/manual/macros, rpmio/macro.c, tests/rpmmacro.at
=> Implement %{macrobody:...} built-in for retrieving the literal macro body

lib/fsm.c, lib/rpmts.c, lib/transaction.c, macros.in
Try to auto-detect non-rotational disks on start of transactions,
and if all involved disks are non-rotational enable optimizations:
%_minimize_io to conserve writes, and %_flush_io to avoid trashing
the system caches.
Caveat: this potentially overrides values from system macro configuration
which is not ok, hence it's only an RFC until this is addressed. Macros
are awfully clumsy for the internal interfaces anyway...
=> Auto-enable optimizations for non-rotational disks on Linux

plugins/selinux.c
Refactor the custom exec context setting code to look like setexecfilecon()
in case the real one is not available to eliminate pesky behavioral
differences between the two cases.
This fixes a concrete bug of libselinux setexecfilecon() returning with
an error when security_getenforce() returns with -1 (such as a bare
chroot with no /sys mounts etc), causing us to spit out useless error
messages in that case ever since fixing the bogus if-logic in
commit ab601b882b9d9d8248250111317615db1aa7b7c6.
Fixes: #1077
=> Use common error logic regardless of setexecfilecon() availability

lib/fprint.c
This reduces the number of calls to fpLookupSubdir() and also gets rid of a poolid->str->poolid roundtrip.
=> More fpLookupSubdir cleanups

lib/depends.c, lib/fprint.c, lib/fprint.h, lib/rpmal.c, lib/rpmal.h
This gets rid of a couple of id->str->id roundtrips and also makes the dependency hashes in rpmtsCheck() use pool ids instead of strings.
=> Speed up dependency solving by using pool ids

lib/backend/dbi.h, lib/backend/ndb/glue.c, lib/backend/ndb/rpmpkg.c, lib/backend/ndb/rpmpkg.h, lib/rpmdb.c, lib/rpmdb_internal.h, lib/rpmts.c, rpmdb.c
This can be used to recover as much data as possibly from a terminally broken database. It is currently only supported for the 'ndb' database.
This method is currently hidden from the API by using a macro to select salvage mode. If it should be more exposed, we can add a rpmtsSalvageDB() method.
=> Add a --salvagedb option to the rpmdb tool

lib/backend/sqlite.c
SQL LIKE is a quirky thing when you only really want exact matches
on a substring. Which begs the question, if we want exact matches on
substring then why not do just that? Why not, indeed. This avoids
escaping madness and the need to use custom extensions for such
a mundane, trivial thing.
Fixes: #1018
=> Fix prefix match searches on strings containing % on sqlite backend

build/parsePreamble.c, lib/depends.c, lib/formats.c, lib/rpmdb.c, lib/rpmds.h
Add a new "meta" qualifier for expressing dependencies that are not
concrete install- or run-time dependencies, and thus should not take
part in install ordering.
There are quite a lot of such dependencies in the wild, for example
versioned sub-package cross-dependencies are typically of this type
and a common source of unnecessary dependency loops. Another common
case are dependencies of meta-packages.
=> Introduce a new qualifier for meta dependencies (RhBug:1648721)

build/rpmfc.c, tests/rpmverify.at
Immaterial %ghosts (ie those that only exist in spec, not disk) trip
up ENOENT errors which end up in package headers, so we have gems like
this in CLASSDICT:
cannot open `/builddir/build/BUILDROOT/crypto-policies-20191128-2.gitcd267a5.fc31.noarch/etc/crypto-policies/back-ends/krb5.config' (No such file or directory)
Treat errors in classify as errors, and filter out ENOENT to handle
the above case, others we'll want to have rpm error or at least warn on.
Notably this trips up an error from a symlink loop in two of our test-cases
that have gone unnoticed until now.
=> Don't store file classification errors into headers

build/rpmfc.c
libmagic strings are notoriously unreliable as the details from version
to version. We link to libelf anyway so we might as well as get the
info straight from the horse's mouth.
Besides being more reliable, this detaches the coloring business from
the hardcoded rpmfcTokens struct and informative-only FILECLASS contents,
opening the door for other changes in that area.
=> Use libelf for determining file colors

build/rpmfc.c, tests/rpmbuild.at
In addition to "magic" strings, support classifying files by matches
on their MIME types which are far more predictable than the notoriously
volatile magic strings which are intended for human consumption.
This adds an optional %__foo_mime and %__foo_exclude_mime patterns
to file attributes. If the mime-variant is present, magic is ignored
if present (with a warning).
The testcase is a fine example of how the grass not necessarily being
any greener on the other side: the actual output is far more predictable,
but the actual classification is not. Our "script" with an arbitrary
unknown interpreter is considered text/plain by libmagic.
Fixes: #1097
=> Support file classification by MIME type

lib/package.c
"RPM v3 is dead" has been repeated over and over in various forums for
the last 15+ years but as long as rpm itself silently accepts it, most
users will have no clue. Log a deprecation warning on V3 retrofits,
in anticipation of eventual removal.
Related: #1107
=> Visibly deprecate RPM v3 support

doc/rpmsign.8, rpmsign.c, sign/rpmgensig.c, sign/rpmsign.h, tests/rpmsigdig.at
On packages where a separate payload digest exists (ie those built with rpm >= 4.14), rpm v3 header+payload signatures are nothing but expensive legacy baggage, as the payload digest will be signed by a header-only signature already, without having to recalculate the entire file.
Automatically detect the payload digest presence and only add V3 signatures on packages that need it, but also add an override switch to force their addition if needed for compatibility or so.
Fixes: #863
=> Stop adding rpm v3 header+payload signatures by default where not needed

configure.ac
Both components are dead upstream for about seven years, deprecate them for later removal, now that we have alternatives.
=> Deprecate Berkeley DB backend and beecrypt support

Makefile.am, ci/Dockerfile
Fix distcheck to work without extra compile step, and drop said extra step.
=> Eliminate extra compilation step from CI

configure.ac
Our beloved gettext 0.16.1 version causes automake to complain about
AM_PROG_MKDIR_P being deprecated although we never directly use such
a macro for anything. This appears to have been fixed in gettext 0.18.2
so bump to that version, having been released in 2012 makes it, um,
mature enough, even for rpm purposes.
=> Bump gettext version to 0.18.2 to get rid of deprecation warnings

scripts/perl.prov
As noted in particular with App::cpanminus, a lot of perl virtual
provides are created that the package *doesn't actually provide*. This
package uses Module::FatPack to embed required libraries that may not be
already installed on the system, which defines them in HEREDOCs for
later use.
The only other example where I found package code completely within a
HEREDOC was in Mail::Sender, and that code is intended to be used only
privately within Mail::Sender itself. This seems like a valid set of
code to explicitly ignore.
This is an attempt to make the parser identify, then skip, HEREDOCs when
looking for provided packages.
Fixes #1106
=> Skip HEREDOCs when parsing perl virtual Provides

doc/Makefile.am
https://rpm.org/wiki/Releases/4.16.0 says "Add man pages for all plugins and rpm2archive (#1016)"
However RPM 4.16.0 alpha doesn't actually include them…
Ahem
This pull request actually includes the new man pages  the tarball and thus the vendor rpms… :-)
Thanks
=> actually include the new man pages

configure.ac, lib/transaction.c
Unlike that multiple statfs() variants, statvfs() is actually in
POSIX 1-2001 already and covers everything we need so there's little
point mucking with anything else. statvfs() is what Linux has been
using all along anyway this means no change on the primary platform.
If this actually regresses something, adding back OS-specific bits
is not a problem, but at least we'll get a clean start with that.
=> Flush 20+ year old statfs() jungle, always use standard statvfs()

tests/atlocal.in
Fixes the reproducable build test failing in Fedora rpm builds due to
%source_date_epoch_from_changelog being set on the outside, which
leaks the SOURCE_DATE_EPOCH environment into the test-suite and
changes the expectation.
=> Unset SOURCE_DATE_EPOCH for the test-suite

build/files.c, build/rpmfc.c, configure.ac, lib/backend/db3.c, lib/backend/ndb/glue.c, lib/backend/ndb/rpmpkg.c, lib/backend/ndb/rpmxdb.c, lib/backend/sqlite.c, lib/cpio.c, lib/rpmchroot.c, lib/rpmdb.c, lib/rpmfi.c, lib/rpmlock.c, lib/rpmscript.c, lib/rpmts.c, lib/transaction.c, lib/verify.c, misc/fts.c, rpmio/rpmglob.c, rpmio/rpmio.c, rpmio/rpmlua.c, sign/rpmgensig.c, system.h
dirent.h and struct dirent are actually standard on this millenium, the
only thing that isn't is d_type member for which we have and retain
a specific test in configure.ac. Include <dirent.h> where needed,
relatively few places do which makes it even a bigger insult to have
this included from system.h.
=> Flush 1998 vintage dirent.h and fcntl.h compatibility mess from system.h

lib/backend/dbi.c
If configuration points to non-existent backend, tryBackend() will
segfault on the first call. Duh. Regression introduced in commit
3eb0eed3806b41efdf86f0433d0b5d7d6c953561.
=> Fix regression causing segfault on database autodetection

build/rpmfc.c
'fn' already contains full path to a file, so no need to prepend it once
more. This is actually breaking things.
Before:
D: Calling %{__pythonname_provides %{?__pythonname_provides_opts}}() on /home/brain/rpmbuild/BUILDROOT/hello-1-1.fc33.x86_64//home/brain/rpmbuild/BUILDROOT/hello-1-1.fc33.x86_64/usr/share/applications/org.gnome.Terminal.desktop
After:
D: Calling %{__pythonname_provides %{?__pythonname_provides_opts}}() on /home/brain/rpmbuild/BUILDROOT/hello-1-1.fc33.x86_64/usr/share/applications/org.gnome.Terminal.desktop
Fixes: https://github.com/rpm-software-management/rpm/issues/1162
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
=> rpmfc: Do not prepend buildroot to a path for parametric generator

fileattrs/ocaml.attr
Commit a6fe37c39b39acbcbd014dd1e6d5653ff84254a1 causes OCaml generators
to execute on all ELF files due to missing "magic_and_path" flag.
Fixes: #1173
=> Fix regression causing all ELF files classified as OCaml

lib/backend/ndb/glue.c, lib/backend/ndb/rpmidx.c, lib/backend/ndb/rpmidx.h, lib/backend/ndb/rpmxdb.c, lib/rpmdb.c
Use read-only mapping for the index databases if the user only requested read-only database access. Also map the xdb database header read-only and only switch to a read-write mapping if an operation is done that needs write access.
=> ndb: do not mmap the index database read-write all the time

build/files.c
In todays' "look ma what crawled from under the bed" episode, we have
encounter a subpackage whose name is not derived from the main package
name, and a manually specified debuginfo package on that. This particular
combo manages to evade all our checks for duplicate package names, and
in the right phase of the moon actually creates corrupt packages due to
two threads end up writing to the same output file simultaneously. Which
is what happened in https://pagure.io/fedora-infrastructure/issue/8816
Catch the case and use the spec-defined variant (because getting rid
of it would be harder) but issue a warning because most likely this
is not what they really wanted.
=> Handle manually specified debuginfo package more gracefully

configure.ac
The NSS library often changes in ways that somehow breaks rpm,
and these days upstream does not care about consumers of NSS other
than itself. This inflicts untold amounts of suffering on users
of rpm in distributions where rpm is linked to NSS.
Now that we have a couple of good, well-supported options, there is
no reason to keep supporting NSS as an option.
So now, we are deprecating it for later removal.
As a small, additional commit, I've added a warning for when beecrypt is selected, just to be slightly more in-your-face about the deprecation.
Closes #1175.
=> Deprecate NSS

fileattrs/python.attr
- sync with Fedora
- only match direct Python sitedir, no /opt/.../lib/python3.7 stuff
- prep for multiple digits Python major releases (e.g. 12.1)
- use the value of %_prefix
See also:
https://src.fedoraproject.org/rpms/python-rpm-generators/c/8eef42cbaa6ff0e5c006959fc06ec115ed5ca37b
https://lists.fedoraproject.org/archives/list/packaging@lists.fedoraproject.org/thread/UFKUM5UKCTNGIT3KJVYEI5VXPI23QMBN/
https://github.com/rpm-software-management/rpm/pull/1153#discussion_r407997958
=> Adjust %__python_path

scripts/pythondistdeps.py
Stop using getopt, and switch to a modern solution for parsing
arguments. Drive-by fixing some flake8 warnings, mainly whitespace.
=> scripts/pythondistdeps: Switch to argparse

rpmio/rpmfileutil.c
Issue a warning if buildtree macros (%_sourcedir etc) contain undefined
macros after expansion, such as things only defined during spec parse.
This always was a murky case that doesn't work in all scenarios, so
a warning seems appropriate. Actual behavior doesn't change here though.
=> Warn on undefined components in buildtree macros

configure.ac, plugins/selinux.c
Backport two more patches to the 4.14.3 release for the selinux plugin
=> 4.14.3 final

build/pack.c
Binary packages come in different sizes and so their build time can vary
greatly.  Dynamic scheduling, which we currently use for parallel
building, is a good strategy to combat such differences and load-balance
the available CPU cores.
That said, knowing that the build time of a package is proportional to
its size, we can reduce the overall time even further by cleverly
ordering the task queue.
As an example, consider a set of 5 packages, 4 of which take 1 unit of
time to build and one takes 4 units.  If we were to build these on a
dual-core system, one possible unit distribution would look like this:
```
TIME --->
CPU 1       * * * * * *         # package 1, 3 and 5
CPU 2       * *                 # package 2 and 4
```
Now, compare that to a different distribution where the largest …
=> build: prioritize large packages

lib/depends.c, lib/rpmal.c
Fixes regressions from commit 75ec16e660e784d7897b37cac1a2b9b135825f25: the newly added provides of to-be-built packages were being used for dependency resolution, such as spec satifying its own buildrequires, and matched against conflicts in installed packages.
Source packages cannot obsolete anything or provide capabilities or files to transactions, don't add them to rpmal at all. Explicitly skip checks against source provides, similarly to what we already did with obsoletes.
Fixes: #1189
=> Don't check source package provides against installed conflicts

fileattrs/python.attr
I haven't tested this yet, but I believe this should work.
=> Don't define global Lua variables from Python generator

lib/rpmarchive.h, lib/rpmfi.c
size_t is unsigned, so returning -1 is not going to have the expected
behavior. Fix it to return ssize_t.
Signed-off-by: Jes Sorensen <jsorensen@fb.com>
=> rpmfiArchiveRead() use signed return value to handle -1 on error

doc/manual/macros, rpmio/expression.c, tests/rpmmacro.at
Adds rpm version as a new expression value type, denoted by v"" (similar to Python u"", b"" etc), which are compared using rpm version comparison algorithm rather than regular string comparison.
For example in specs:
```
%if v"%{python_version}" < v"3.9"
...
%endif
```
...but also command lines, arbitrary macros etc: `rpm --eval '%[v"1:1.2" < v"2.0"]'`
Fixes: #1217
=> RFE: Support rpm version comparison in expressions

rpmbuild.c
Build tree macros can use %{name} or any other kind of weird things in
them. The generation of Name or anything like that from the
%{_sourcedir} or anything like this is not something what people do or
should do. Let's just parse spec first and then create any missing
directories for build tree.
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
=> rpmbuild: Create build tree after parsing a spec file

lib/rpmprob.c, lib/transaction.c
This essentially adds a check ensuring removed packages still exist when we're about to commit to the transaction, ie that nobody removed the package while we were enjoying the view.
RPMPROB_PKG_INSTALLED is (ab)used for the purpose here - it's related to the package install status anyhow and adding a separate value would be just a whole bunch of boilerplate code, but I suppose I could be conviced otherwise too.
=> Add pre-flight check for erased packages too

lib/header.c
Since commits [Place file signatures into the signature header where they
belong][1] applied, run `rpm -Kv **.rpm' failed if signature header
is larger than 64KB. Here are steps:
1) A unsigned rpm package, the size is 227560 bytes
$ ls -al xz-src-5.2.5-r0.corei7_64.rpm
-rw-------. 1 mockbuild 1000 227560 Jun  3 09:59
2) Sign the rpm package
$ rpmsign --addsign ... xz-src-5.2.5-r0.corei7_64.rpm
3) The size of signed rpm is 312208 bytes
$ ls -al xz-src-5.2.5-r0.corei7_64.rpm
-rw-------. 1 mockbuild 1000 312208 Jun  3 09:48
4) Run `rpm -Kv' failed with signature hdr data out of range
$ rpm -Kv xz-src-5.2.5-r0.corei7_64.rpm
xz-src-5.2.5-r0.corei7_64.rpm:
error: xz-src-5.2.5-r0.corei7_64.rpm: signature hdr data: BAD, no. of
bytes(88864) out of range
From 1) and 3), the size of signed rpm …
=> Fix: bump up the limit of signature header to 64MB

lib/transaction.c, macros.in
Commit 47e2463d8a98a7535e141d59d17be17d5a30862c added logic to enable
%_flush_io automatically on non-rotational disks to avoid trashing system
caches and IO peaks on the grounds that this isn't so expensive on SSD,
but real world experience suggests otherwise. Install times go from
seconds to minutes which might not matter for the random individual system
but for build systems and the like churning away continuously...
=> Don't auto-enable IO flushing on non-rotational disks

python/rpm/transaction.py, tests/rpmpython.at
The code would only raise an exception if TransactionSetCore.addErase()
returned an error, but the catch is that with many kinds of argument
types we'd silently skip the whole addition because no headers were found.
This looks to be a regression introduced some eleven years ago in
commit 9b20c706a4f93266450fae2f94007343b2e8fd9e.
Fixes: #1214
=> Fix python ts.addErase() not raising exception on not-found packages

fileattrs/metainfo.attr
Somehow it wasn't noticed before.
Fixes: 9464926456125dacb8046767f1fe4235471986e9
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
=> metainfo.attr: Fix execution of the generator

build/rpmfc.c, build/rpmfc.h, tools/rpmdeps.c
It was possible to generate Requires, Recommends etc. using external dependency generators.
Adding ability to generate OrderWithRequires.
Example use case:
When a package contains a systemd unit, %systemd_* macros are usually used;
it is usefull to add "OrderWithRequires: systemd" in this case to ensure
that systemd is installed before that package.
It will help to avoid adding "%systemd_ordering" manually to all packages using systemd.
Having systemd preinstalled before packages with systemd scriptlets is really important,
otherwise those scriptlets fail silently, and the resulting ISO or chroot may be broken.
The same makes sense for e.g. systemd-sysusers, systemd-tmpfiles.
An RPM generator using this functionality was implemented: https://abf.io/import/order-rpm-generators
Rebuilding …
=> Add OrderWithRequires dependency generation

build/pack.c
RPM build did not fail if rpmlint (%_build_pkgcheck_set) failed when checking binary RPMs
(it did fail correctly when rpmlint failed when checking SRPMs)
Probably fixes regression introduced by 78f61f273 ("Refactor package set checking out of packageBinaries()")
=> Fail the build if %_build_pkgcheck_set failed

ci/Dockerfile, tests/Makefile.am, tests/atlocal.in, tests/debugedit.at, tests/local.at, tests/rpmbuild.at, tests/rpmbuildid.at, tests/rpmconfig.at, tests/rpmconfig2.at, tests/rpmconfig3.at, tests/rpmconflict.at, tests/rpmdb.at, tests/rpmdeps.at, tests/rpmi.at, tests/rpmio.at, tests/rpmmacro.at, tests/rpmorder.at, tests/rpmpython.at, tests/rpmquery.at, tests/rpmreplace.at, tests/rpmscript.at, tests/rpmsigdig.at, tests/rpmverify.at, tests/rpmvfylevel.at
Up to now we've run tests in a mish-mash of an environment where bits and pieces of previous tests might exist, and as state has been shared it's been impossible to execute tests in parallel.
This makes the pre-populated testing-root read-only to the owner to force all writers to perform an extra setup call to gain a private testing environment. Most of the users needing this already had RPMDB_INIT calls to ensure clean rpmdb state so that's where this is hooked onto.
There's a fair bit of gymnastics with the environment to make things match on both sides of fakechroot, some of which can hopefully go away eventually once the dust from this settles. This is also rather heavy as it is, on my laptop serial execution goes down from ~1m15s to ~1m45s, but then parallel execution with -j8 is …
=> Execute tests in independent testing roots to enable parallel running

tests/local.at, tests/rpmbuild.at, tests/rpmbuildid.at, tests/rpmconfig.at, tests/rpmconfig2.at, tests/rpmconfig3.at, tests/rpmdeps.at, tests/rpmi.at, tests/rpmreplace.at, tests/rpmverify.at
Merge tests to groups when they share built content to avoid redundant builds over and over again, eliminate redundant copies on build tests etc. Besides removing gobs of crud, makes it run faster too.
=> Testsuite cleanup

build/pack.c
The pkg variable used in the parallel loop was declared outside
of the omp parallel construct, so it was shared among tasks.  This
had the potential to cause a data race.  The gcc openmp implementation
did not hit this problem, but I uncovered it while trying to compile with
clang.  My best guess as to what was happening is that after the last
task was launched, all tasks had the same value of pkg and were operating
on the same data at the same time.
This patch marks the variable as firstprivate, so each tasks gets its
own copy of the variable.
=> Fix data race in packageBinaries() function

build/rpmfc.c, tests/rpmbuild.at
Previously only the legacy external dependency generator listened to
exit codes from the generator, and even that only for provides.
Anybody building packages will want to know if generators barf up
for one reason or another. Let them.
Always call rpmfcExec() with failnonzero set, pass errors around, add tests.
Fixes: #1183
=> Always fail build on dependency generator failures (#1183)

build/files.c
The symlinks do occupy space so they should be counted, except for
hardlinks to symlinks.
Rpm's own disk-space accounting is not affected, it always looks at
individual file sizes rather than the total size.
=> Account for symlinks in total package size (RhBug:1848199)

lib/transaction.c, tests/Makefile.am, tests/data/SPECS/hlbreak.spec, tests/rpmverify.at
The existing FSM code doesn't correctly handle FA_TOUCH on hardlinked
file sets, which causes the hardlink set to break on at least some
upgrade scenarios when minimize_writes is enabled.
Only enable FA_TOUCH on non-hardlinked files to work around the issue
for now. While at it, rearrange the conditionals around min_writes to make
it a bit clearer. Testcase adopted from original reproducer by
Fabian Vogt, thanks!
Fixes: #1278
=> Fix (work around) FA_TOUCH not scoping correctly over hardlinks

doc/Makefile.am
Doesn't make much sense to install manuals for features that are not
enabled in a build. Conditionalize our man page installation where
necessary, taking care to include the manuals in tarballs regardless
of configured status.
Inspired by PR (#1247) from Thierry Vignaud
=> Don't install man pages for disabled features

macros.in
It's rarely the case that the user may set global ``core.excludesfile``, ``git add .`` may not add all the files as expect.
It will fail to build if the excluded files are patch-needed.
=> macros: force add files to git index

build/rpmfc.c, tests/rpmbuild.at
This is simply too broken to patch up. Revert and back to drawing board.
This reverts commit fb5299b2a49460216c38674b7398296d3a6d767c.
=> Revert "Always fail build on dependency generator failures (#1183)"

tests/rpmsigdig.at
When running with a non-tty input (such as inside mock), the --addsign
test will fail due to GPG_TTY related warning getting emitted since commit
52c0198e245fcac55440ed1e0211d33f84681a7a. Our test-keys do not have
passphrases that need to be asked, so just silence the warning by
manually setting GPG_TTY to an empty value.
Fixes: #1290
=> Fix bogus test-suite failure when input is not a tty (#1290)

scripts/pythondistdeps.py
This change better reflects the behavior of setuptools in situations that are processed successfully, but not covered in the specification.
=> Sync python dependency conversion with pyreq2rpm.

scripts/pythondistdeps.py
See https://bugzilla.redhat.com/show_bug.cgi?id=1853597#c11
pkg_resources from setuptools 42+ no longer only use platform.python_version(),
but also platform.python_version_tuple() -- this was updated in packaging 19.1+.
This fix makes it work again with both new and old setuptools,
hopefully for some while.
https://github.com/pypa/setuptools/commit/bf069fe9ddcadaa2c029067601d06a07d037d4f7
https://github.com/pypa/packaging/commit/86a443f3185024edd0b826afdd91d8f9a4917022
=> pythondistdeps.py: Adapt Python version marker workaround for setuptools 42+

lib/header.h, lib/rpmtd.h, rpmio/rpmlog.h, rpmio/rpmpgp.h
Some of code documentation comments are misformed which causes corresponding doxygen docs not to be generated. I found out about this because I was looking the the [online docs](http://ftp.rpm.org/api/4.15.1/group__header.html#ga33376e8850c275b72059fe723a0d3066) for a function I knew existed but could not find it there.
=> Fix Doxygen comments

fileattrs/python.attr
Fix python(abi) requires generator, it picked files from almost good directories
The %__python_magic filter suddenly got actually working with file 5.39:
Before:
file.cpython-38.opt-1.pyc: data
After:
file.cpython-38.opt-1.pyc: python 3.8 byte-compiled
Hence, the filter started to pick all Python files regardless of their location.
Later, in the actual generator, paths like this were considered:
/opt/usr/lib/python3.X/...
And generated requirements on python(abi).
We don't actually need to filter the files by file magic,
so we drop it to get the previously accidentally working behavior.
We could choose if the path and magic filters are applied as OR or AND.
However, we don't want either.
We actually want to mach any files in Python directories regardless of their magic.
We *could* filter …
=> Fix python(abi) requires generator, it picked files from almost good directories

macros.in
rpmlint thinks that /usr/share/gnome/help is documentation:
`FilesCheck.py:188:doc_regex = re.compile(r'^/usr(/share|/X11R6)?/(doc|man|info)/|^/usr/share/gnome/help')`
and gives a warning that those files are not marked as docs in RPM packages.
It seems a good idea to treat help files as documentation (for example, if someone wants to reduce disk usage
by not installing documentation, he will also not want help files),
so let's add them to the default %__docdir_path
=> Treat /usr/share/gnome/help as docs

lib/tagname.c
A 2016 change (57a96d2486c26142ebb168a1f00b0374d35bf044) apparently
changed tagsByName from dynamic allocation to being static, so that
Valgrind would not complain about lost memory. The definition is:
static headerTagTableEntry tagsByName[TABLESIZE];
But a comparison was left of `tagsByName == NULL` in lib/tagname.c
and compiling with clang gives a warning, saying it is never NULL.
=> Remove compare of global array tagsByName to NULL

build/files.c
Otherwise executables that are not proper elf files are leaking libelf
handles. This results in file being left open (mmap'ed) and fails the
build on NFS as those files can't be deleted properly there.
Resolves: rhbz#1840728
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1840728
=> Always close libelf handle

configure.ac, macros.in, rpmio/rpmio.c
Port zstd compression to the new API (ZSTD_compressStream2).
My motivation is to eventually enable multi-threaded compression which can help packages like Firefox where there's a single huge rpm that is being compressed.
Once the change is accepted, the following one-liner will enable parallel compression:
```c
ZSTD_CCtx_setParameter(cctx, ZSTD_c_nbWorkers, 4);
```
=> Support threading for zstd compression.

scripts/brp-python-bytecompile
Sometimes, byte-compilation might produce two functionally identical pyc files that are not byte-to-byte identical which might cause problems.
Disabled hash seed randomization does not solve this problem entirely but helps a lot by lowering probability.
=> Disable Python hash seed randomization in brp-python-bytecompile

build/parseChangelog.c, macros.in
%_changelog_trimtime is an absolute timestamp which needs to be constantly
pushed forward to preserve the same relative age, and will start trimming
entries from unchanged packages until none are left, leading to unexpected
and confusing behavior (RhBug:1722806, ...)
It's better to trim by age relative to newest changelog entry. This way the
number of trimmed entries will not change unless the spec changes, and at
least one entry is always preserved. Introduce a new %_changelog_trimage
macro for this and mark the broken by design %_changelog_trimtime as
deprecated, but autoconvert an existing trimtime into relative for now.
As a seemingly unrelated change, move the "time" variable declaration
to a narrower scope to unmask the time() function for use on entry.
Fixes: #1301
=> Fix changelog trimming to work relative to newest existing entry (#1301)

tests/data/SOURCES/bar.c, tests/data/SOURCES/baz.c, tests/data/SOURCES/foo.c, tests/data/SOURCES/foobar.h, tests/debugedit.at, tools/debugedit.c
There is a new testcase: `debugedit .debug_types *`
=> debugedit: Fix missing relocation of .debug_types section.

sign/rpmgensig.c
Various proprietary packages in the wild have subtly malformed data
in the signature header, in particular wrt the immutable region size,
presumably from using some in-house/3rd party signing tools which do
not understand the immutable region business at all. This can prevent
resigning and signature deletion on such packages due to the more
thorough checking that rpmsign does.
As the old wisdom goes, be liberal in what you accept... we can easily
work around the crud by just taking a fresh copy of the contents that
are legit as such (otherwise the package would be uninstallable).
=> Work around buggy signature region preventing resigning (RhBug:1851508)

fileattrs/elf.attr, macros.in, tools/elfdeps.c
This was kinda ugly-but-necessary when added back in 2003 (commit
752cac72e220dcad4e6fce39508e714e59e3e0a1) but entirely redundant
since the "new" dependency generator in rpm >= 4.9.x with arbitrary
filtering support. The handful of packages using it can just as well
achieve the same (and more) without special hacks in rpm with:
%global __requires_exclude GLIBC_PRIVATE
%global __provides_exclude GLIBC_PRIVATE
=> Remove support for redundant %_filter_GLIBC_PRIVATE mechanism

macros.in, rpmio/rpmio.c
When using xz or zstd, it can be handy to automatically detect
number of threads. We can use `%{getncpus}` for that.
=> Enable thread autodetection for a parallel compression.

macros.in
The garbage collection happens in background, based on heuristic.
This means that sometimes, when subsequent commands run,
some files might disappear in the middle of an action.
For example, when a find is used in %prep:
+ /usr/bin/git commit -m ... --author 'rpm-build <rpm-build>'
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
...
+ find ...
find: './.git/objects/47': No such file or directory
find: './.git/objects/46': No such file or directory
find: './.git/objects/49': No such file or directory
find: './.git/objects/4d': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.xxxxxx (%prep)
=> Prevent automatic garbage collection in git based %autosetup macros

lib/backend/dbi.c
The rpmdb is our most precious piece of data, don't make assumptions on
invalid configuration. Together with our crazy create-db-on-read behavior,
total database loss is just one 'rpmdb --rebuilddb' away in some scenarios
with the former behavior: access an sqlite/ndb database with older
version not supporting those, silently fallback to creating empty bdb,
and if db is now rebuilt, poof the data is gone.
Detect and warn on unknown/invalid %_db_backend configuration and fall
back to using dummy backend where no damage can occur. Doesn't help with
the old versions out there, but lets at least be saner going forward.
=> Warn and fall back to dummy database on unknown database backend config

build/parsePrep.c, lib/formats.c, lib/poptI.c
There's nothing to translate in "%s: %s" and the like, don't bother
people with this stuff.
=> Stop untranslatable format strings from being translated

build/files.c
- simplify code / fix build failure with -fsanitize=address
- don't call exit() from middle of librpmbuild
=> Misc fixes to clamp_mtime_to_source_date_epoch logic

build/files.c, rpmio/rpmstrpool.c
- Fix possible read beyond buffer in rstrnlenhash()
- Add missing terminator to copyTagsFromMainDebug array
=> Fix some address-sanitizer findings

lib/transaction.c, macros.in
RhBug:1872141 (PR #1347) demonstrates how brittle and dangerous this
thing is. Until we can (re-)verify (digest and all) files not needing recreating from
fsm, this thing should be considered experimental and too dangerous
to automatically enable for casual users.
=> Disable SSD auto-detection, mark %_minimize_writes as experimental

lib/fsm.c, tests/Makefile.am, tests/data/SPECS/suicidal.spec, tests/rpmi.at
When %_minimize_writes is enabled, we determine unchanged files during
fingerprinting and only update their metadata (FA_TOUCH) instead of
always recreating from scratch (FA_CREATE) during install. However
package scriptlets (and administrators) can and will do arbitrary stuff
in the meanwhile, such as rm -f their own files in %pre, hoping to
get a fresh copy of contents no matter what. Or something.
Now, if the file was determined to not need changing by rpm, this will
just fail with chown & friends trying to touch non-existent file.
One can consider this a case of package shooting itself in the foot, but
when a package update fails or succeeds depending on %_minimize_writes this
to me suggests the feature is at fault as much as the package.
Do fsmVerify() on all files to be FA_TOUCH'ed …
=> Upgrade FA_TOUCH to FA_CREATE if the file went away (RhBug:1872141)

lib/transaction.c
Warning introduced in commit 64b4ebd315ccdaac402c083a71b431310238f6ba
which failed to take this into account, dunno how this wasn't caught
in CI or local testing.
=> Unbreak build due to defined but not used warning from ensureMacro()

lib/rpmscript.c
Contrary to what the TODO comment said, we cannot rely on chroot cwd
because an API user could've changed to some other directory in the
meanwhile. For Lua scripts, we simply need to save whatever the directory
we are in and return to that, to avoid breaking API users.
=> Remove invalid TODO comment on Lua scriptlet cwd

lib/rpmte.c, lib/rpmte.h, python/rpmte-py.c, tests/rpmpython.at
The "key" passed to rpmtsAddInstallEleemnt() and associated with transaction
elements is sometimes mistaken for user data, but it is not, as rpm relies
on it having a very specific meaning and is passed around with that very
assumption.
API users have all sorts of (legit!) needs, lets add a proper private user
data member to transaction elements.
The Python bindings to this are kinda dangerous if you liberally mix Python
and C as we can't know whether the pointer is an actual Python object or not
so we can only assume it is and hope for the best. Nobody in their right
mind should be setting user data from one language and accessing it from
another, really...
=> Add support for application private user data in transaction elements

lib/depends.c, lib/rpmts.c, lib/rpmts.h, lib/rpmts_internal.h
Add support for an optional callback hook for reveiving notifications
about added and deleted transaction elements. This lets API clients
easily track which elements get created and/or replaced by a single
rpmtsAddFoo() call and adjust their own book-keeping accordingly.
Also makes for an easy place to set application private data pointers
for newly added elements.
=> Implement a transaction set change notification callback

lib/rpmdb.c
Fixes compilation on musl, otherwise it fails with undefined references
to various O_* symbols as mentioned here:
https://www.man7.org/linux/man-pages/man0/fcntl.h.0p.html
=> lib/rpmdb.c: include fcntl.h for O_*

lib/rpmscript.c
All this time we've been logging file and transfile triggers with output
identical to that of regular triggers, confusing people for no good reason.
We know which of the three it is when creating so add a matching prefix
to the output at that point. All we need to do is move the '%' from
the scriptlet table to the printf() format string to make room for
the description prefix. Doh.
So now we get output using things with their proper names, such as:
D: running post-transaction scripts
D: %transfiletriggerin(glibc-common-2.31-4.fc32.x86_64): scriptlet start
=> Fix ambiguous diagnostics output on file triggers (RhBug:1883338)

lib/rpmts.c, lib/rpmts.h, lib/rpmts_internal.h, python/rpmts-py.c, tests/rpmpython.at
Add API to get and set callback style, defaulting to the good ole
header first style and add a new style where a transaction element
is passed in place of the header, allowing a much saner interaction.
This is doubly so in Python, where the old style callback is a
braindamaged mess. In the new mode the "key" is not passed as separate
argument at all, it can be just as well retrieved via te.Key() for
the callbacks needing it.
=> Implement alternative transaction callback style

rpmio/rpmio.c
This code eliminates a false positive failure when the destination position is > 2GiB. This is done by changing the contract for `Fseek`. Now it returns `0` on success instead of an `int` offset. Care should be used to interpret the result as there is a difference in semantics between the POSIX `fseek(2)`. Existing code is correct: negative results are still failures.
=> Make fdSeek return 0 on success, -1 on error

doc/manual/lua.md, lib/rpmscript.c, rpmio/macro.c, rpmio/rpmlua.c, rpmio/rpmlua.h, tests/rpmmacro.at, tests/rpmscript.at
Up to now, any communication with Lua scriptlets has required use of global tables. This PR adds support for real argument passing via the internal rpmlua API and converts the install scriptlet machinery to use that. More details in commit messages.
This appears more of a cleanup than new functionality as such, but is a pre-requisite for #1092 .
=> Add support for passing real local arguments to Lua scriptlets

rpmio/macro.c, tests/rpmmacro.at
This seems to be the intention of the code but it did
not work because macro parsing was resumed at the wrong
point of the input string. Without this commit, "%{}"
expanded to "%" instead of "%{}".
=> Treat unparsable macros like undefined macros

doc/manual/macros.md, lib/poptALL.c, rpmio/Makefile.am, rpmio/macro.c, rpmio/rgetopt.c, rpmio/rpmlua.c, rpmio/rpmmacro_internal.h, tests/rpmmacro.at
Macros might want to pass along options meant for others while perhaps modifying some of them, without exposing it all to users.
Have "-" as the parametric macro opts string disable all options processing in rpm, allowing the macro to handle the raw argument list as they place.
Fixes: #547
The first two commits are infrastructure pre-requisites.
=> Allow parametric macros to opt out of option processing (#547)

rpmio/macro.c, rpmio/rpmlua.c
macro.c: In function ‘mbopt’:
macro.c:895:19: warning: unused variable ‘me’ [-Wunused-variable]
895 |     rpmMacroEntry me = mb->me;
|                   ^~
rpmlua.c: In function ‘fd_seek’:
rpmlua.c:985:22: warning: unused variable ‘mode’ [-Wunused-variable]
985 |     static const int mode[] = {SEEK_SET, SEEK_CUR, SEEK_END};
|                      ^~~~
The former is actually unused, the latter should be used.
=> Fix warnings from set but unused, variables in macro.c and rpmlua.c

rpmio/macro.c, tests/rpmmacro.at
If there was a '\' at the end of the buffer, the code would
return a pointer after the trailing \0 leading to unallocated
memory access and weird results in some cases.
See commit 817959609b95afe34ce0f7f6c3dc5d7d0d9a8470.
=> Fix logic error in grabArgs()

rpmio/macro.c
This splits of a setupArgs() function that will be also used when we add a new method to expand a specific macro.
=> Refactor handling of parameterized macro args

lib/rpmrc.c
Fixes compilation on musl, otherwise it fails with undefined references
to various O_* symbols as mentioned here:
https://www.man7.org/linux/man-pages/man0/fcntl.h.0p.html
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> lib/rpmrc.c: include fcntl.h for O_*

rpmio/macro.c, rpmio/rpmmacro.h
Add the necessary infra to pass and carry dofoo/parse function pointers
in macro entries, define our basic built-in primitives at macro
initialization and adapt the built-in calling logic in expandMacro()
to look up the info from macro entry instead of the builtin table.
This has various nice benefits, such as allowing simple testing whether
rpm supports a given primitive by testing whether said macro is defined.
It also paves way for later implementing various spec constructs as
actual macros instead of the confusing pseudo-macros they are now.
=> Add preliminary support for dynamic built-in macro registration

rpmio/argv.c, rpmio/argv.h
Support adding partial / non-terminated strings to argv without having
to jump through hoops at the call site. argvAdd() becomes just a special
case of argvAddN().
=> Implement argvAddN() API for adding partial strings to argv arrays

ci/Dockerfile, rpmio/argv.h
Fix the dumb typo in argvAddN() parameter documentation, and prevent such mishaps in the future.
=> Fail CI on doxygen warnings

build/rpmfc.c
Despite ultimately having the same exact options and arguments, parametric
and non-parametric generators receive them in such different manners that
trying to handle them together only makes things more complicated.
Pass the main macro name around and let the runFoo() calls construct
the arguments as fits the case.
This also lets us take advantage of rpmExpandThisMacro() for calling
parametric generators, eliminating the need for the %1 macro argument
hack.
=> Simplify & unhackify dependency generator command construction

doc/manual/macros.md, macros.in, rpmio/macro.c, tests/rpmmacro.at
Some builtin macros have their own special meaning for ! and ? which is inconsistent with the general meaning of those. This is confusing, bad and conflicts with the goal of making builtins more like normal macros.
This changes %{verbose} to return a simple boolean that can be used in an expression, and drops support for undocumented conditional %{?load:...} which can be avoided by using newly added boolean %{exists:...} instead. Also drop support for undocumented %{!trace} syntax to disable tracing, we can easily add some other syntax to support that if necessary. 
With that, builtin macros have no special syntaxes left, eliminate the internal arguments and make builtins follow general macro conditional syntax.
=> Eliminate special conditional syntaxes from builtin macros

lib/rpmchroot.c, lib/rpmrc.c
There's no point or need to do all this fluff on library initialization,
we can just as well do it when we're told to use a chroot by
calling rpmChrootSet(), at which time we're still on familiar ground.
Eliminating unused cruft from initialization can't hurt our start-up
times either.
=> Only do early name services initialization if we actually chroot

lib/backend/sqlite.c
Curiously, sqlite allocates resources that need freeing even in case
of failure to open. Quoting from https://www.sqlite.org/c3ref/open.html:
> Whether or not an error occurs when it is opened, resources associated
> with the database connection handle should be released by passing it to
> sqlite3_close() when it is no longer required.
I disagree, but as it's documented behavior there's no point filing a
bug. So lets close the non-open connection and chug on.
=> Fix a minor memory leak on failed sqlite database open (RhBug:1896301)

configure.ac
Use AC_COMPILE_IFELSE as AC_RUN_IFELSE raises a build failure when
cross-compiling
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix cross-compilation

build/files.c, doc/manual/spec.md, tests/data/SPECS/hlinktest.spec, tests/data/SPECS/test-subpackages-exclude.spec, tests/rpmbuild.at
The intent of %exclude was always to merely support sub-packaging with
wildcards in %files sections, not to permit leaving junk in the buildroot.
Enforce this by checking against the actually packaged contents rather
than everything we encountered during collection. This also gets rid
of the ugly static check_fileList buffer - besides being ugly, such things
are bad for parallelism.
This has been widely abused so the change is likely to break quite a few
packages in the wild. As a side-effect this also cures a long-standing bug
where unpackaged excluded files leak their debuginfo into packaged contents,
as such a package will now fail to build at (RhBug:878863)
Fixes: #994
=> Require everything in buildroot to be packaged (#994)

build/build.c, configure.ac, lib/rpmug.c
We only actually used gethostbyname() for canonicalizing buildhost,
convert that to use getaddrinfo() instead: this is not a particularly
useful or interesting field so just grab whatever result comes first.
The other "use" was to initialize name services, but as we don't need
or use hostnames for any operation, we can just as well drop it. User
and group names are what we care about.
=> Eliminate use of obsolete gethostbyname() function

build/files.c, scripts/check-files, tests/rpmbuild.at
Previously we only checked for unpackaged files and symlinks, completely
ignoring eg extra directories that might be there. Just check for everything
instead. Related to #994.
Directories are a little tricky as some of them are almost always unowned
so we need to allow all path components leading to packaged files.
=> Really require everything in buildroot to be packaged

tools/debugedit.c
No need to call edit_dwarf2() if debugedit is invoked just to extract
build-id (with `-i -n'). Otherwise, we will get `DWARF version 0
unhandled' warning for compressed .debug files:
/usr/lib/rpm/debugedit: ./usr/lib/debug/...e.ko.debug: DWARF version 0 unhandled
Context: We have kernel modules elfcompressed in ALT.
@ldv-alt
=> debugedit: Do not 'edit_dwarf2' when just extracting build-id

python/rpmkeyring-py.c
pkgParsePkts() only parses the PGP armor, the actual pubkey is only
parsed as a part of rpmPubkeyNew() whose return we need to check for
separately. Emit different messages in these cases.
Thanks to @KOLANICH for pointing this out and initial patch.
=> Improve error handling in Python pubkey constructor

lib/backend/db3.c, lib/backend/ndb/glue.c, lib/backend/sqlite.c, lib/rpmdb.c, lib/rpmts.c, tests/local.at, tests/rpmdb.at, tests/rpmpython.at
If somebody is opening a database in a read-only mode (eg for query then we really have no business to *create* such database if not existing.
This implicit discard of read-only flag is such a long standing behavior that this is likely to break stuff here and there.
=> Disable implicit database creation on read-only handle

rpmio/macro.c, tests/rpmmacro.at
Accept both %{foo:arg} and %{foo arg} notation for both builtins
and user-defined parametric macros, the former only ever has one
argument whereas the latter can have multiple.
"parse" type builtins such as %define are trickier and only work with
traditional syntax for now.
=> Unify builtin and user-defined parametric macro calling syntax

ci/Dockerfile
Dockerhub has added download rate limiting (and who could blame them)
But our CI getting blocked because of other projects being busy
downloading from Docker isn't so nice, hopefully Fedora's own registry
lets us work around this.
=> Pull CI image from registry.fedoraproject.org

rpmbuild.c, tests/rpmbuild.at
Commit acf5e00281d73a2f8034091241c7b0e2ba00e383 cut a couple of corners
too many, causing the temporary file name used to extract the spec from
the tarball to end up in the src.rpm too.
Revert back to creating %_specdir for tar builds, it might not be
optimal but it's not exactly harmful either (%_sourcedir is different).
The "truly correct" solutions get increasingly complicated for such
a silly thing as this is. In addition to creating the %_specdir, we
also need to rename the file to its proper name, simplify that code
a bit while at it and add a test-case.
Fixes: #1386
=> Fix 4.16.0 regression causing invalid spec file name on rpmbuild -ts

lib/backend/dbi.c
There is no harm in allowing read access in this case. We still
error out in the database rebuild case, just to be on the safe
side.
=> Allow database probing if _db_backend is not set

lib/backend/ndb/rpmidx.c, lib/backend/ndb/rpmxdb.c
This seems to do the trick for getting NDB to compile on macOS.
We've been running this patch in production for a bit and it hasn't caused any issues for us.
Feedback welcome, My C is very very rusty, so there might be better ways of doing this :)
=> Add darwin support to NDB.

lib/rpmscript.c
Since commit c5f82d3f6223ebd0c5cc0a07ea60393ae7284929 we've blocked
most signals during transactions, which makes sense to rpm itself but
the signal mask is inherited to childs and carried even across exec(),
so all scriptlets are executing with those signals blocked as well.
Which in turn does not make sense, the scriptlets could run stuff that
actually depends on signal delivery (such as SIGALARM in RhBug:1913765).
Unblock all signals for forked scriptlet execution (Lua scriptlets are
totally different as they execute in-process for now)
=> Unblock signals in forked scriptlets

lib/rpmrc.c
What it says on the tin.
As it stands right now building `rpm` natively on a M1 box just gets you `error: No compatible architectures found for build` if you try to `rpmbuild` anything, so we need to detect when `__arm64__` is defined and set the build architecture to `aarch64`.
=> Support building on arm64 macOS

rpmio/rpmio.c
The read happened if there was no number after the 'T' option.
=> Fix out of bounds read when parsing the xz thread number

lib/header.c
This is already checked for other headers.
=> Verify that data does not overlap region trailer

doc/manual/spec.md
Add brief explanations on all our qualifiers and their semantics.
Also fix the terminology to use "qualifier" rather than "context".
Fixes: #1089
=> Document dependency qualifiers (#1089)

build/files.c, macros.in
Add macro %_duplicate_files_terminate_build to allow terminating build
on duplicate file-list entries. As there are common packaging scenarios
where duplicates are kind of required to achieve a thing reasonably
(eg a directory full of files and just one of them needs different
permissions/flags), default to off until we grow a way to better deal
with that.
Fixes: #1158
=> Support failing build on duplicate files (#1158)

macros.in
%apply_patch was never intended to be called directly, lets make this
more obvious by adding preceding underscores.
=> Rename %apply_patch to make it clearer it's an internal thing (#1357)

scripts/find-lang.sh
as the previous license is ambiguous about its support for modification
and does not carry a warranty disclaimer. MIT license is close to the origial
license in intent but more legally sound.
This is done with the consent of the original author
W. L. Estes <wlestes@uncg.edu>
who was contacted by Tom Callaway <spotrh@gmail.com> by mail
and the following contributors:
Arkadiusz Miśkiewicz <arekm@pld-linux.org>
Florian Festi<ffesti@redhat.com>
Panu Matilainen<pmatilai@redhat.com>
Per Øyvind Karlsen <peroyvind@mandriva.org>
Ville Skyttä<ville.skytta@iki.fi>
who gave their permission in the GitHub ticket
(https://github.com/rpm-software-management/rpm/issues/595).
Resolves: #595
=> Relicense find-lang.sh under the MIT license

macros.in
This prevents the patch utility to ask questions during builds.
See man patch for details
Resolves: #978
=> Add -f to %_default_patch_flags

lib/header.c
It can’t legitimately happen, and it causes problems elsewhere.  For instance, strtaglen() will suffer an integer underflow.
=> Forbid tag data with count zero

doc/manual/lua.md, rpmio/macro.c, rpmio/rpmlua.c, tests/rpmmacro.at
Add rpm macro context as a global table-like entity named 'macros' for
a more Lua-native experience with rpm macros.
Support basic indexing syntaxes (macros[k] and macros.k) for access, define
and undefine operations. Undefined macros return nil here and assigning
to nil will undefine (pop) the macro.
As a specialty, parametric macros are returned as native callable
variadic Lua functions. A string argument is passed to expand as is,
but if arguments are passed as a table, eg `r = macros.foo({1, 2, 3})`,
they are passed entirely as-is.
The macro context pointer in the userdata is not consistently used for
all operations here, but then all the macro operations in Lua are hardwired
to the global context anyway so it doesn't matter in practise. Properly
passing the context around in all …
=> Implement a table-like shortcut to rpm macros in Lua

Makefile.am, configure.ac, doc/Makefile.am, doc/rpm-plugin-fapolicyd.8, macros.in, plugins/Makefile.am, plugins/fapolicyd.c
The plugin notifies fapolicyd daemon about ongoing rpm transaction via linux pipe.
It sends file's info in "%s %lu %64s\n" format.
The daemon adds these records dynamically to the DB and they are considered as trusted.
Related PRs:
https://github.com/linux-application-whitelisting/fapolicyd/pull/105
https://github.com/linux-application-whitelisting/fapolicyd/pull/106
Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1876975
=> Added fapolicyd plugin

rpmio/macro.c, tests/rpmmacro.at
Revert commit 7f220202f20c69d6f3fd957325cdbe692bbabedd to fix #1418 and make things more consistent.
We always want the tracing output on stderr, but we might not always want the traces so conditionalize the traceback outputing to only occur on verbose levels. 
Also generate actually meaningful tracebacks by supplying the macro names where possible.
=> Improve macro traceback behavior

scripts/check-rpaths-worker
DT_RPATH has been deprecated in favour of DT_RUNPATH for some time now
and both have similar functionality.  RUNPATH is less infectious,
i.e. it does not affect search paths for dependency resolution of
dependencies, but that only limits the issues insecure paths may cause
and does not eliminate them.
It is therefore necessary to check both RPATH and RUNPATH for the same
issues.
=> Also check DT_RUNPATH when looking for rpath issues

rpmio/rpmio.c
When there is number after "T" (suggested number of threads or "0" for
getncpus), lzopen_internal() mode parser would skip one byte, and when
it's at the end of the string it would then parse undesired garbage from
the memory, making intermittent compression failures.
Fixes: 7740d1098 ("Add support for multithreaded xz compression")
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>
Cc: @ldv-alt
=> rpmio: Fix lzopen_internal mode parsing when 'Tn' is used

lib/backend/ndb/glue.c, lib/rpmts.c, lib/rpmts.h, python/rpmts-py.c
Since it's introduction, rpmtsInitDB() has passed the second argument directly to rpmdbInit() as permission bits. However commit 81fef9848051e5068694cde9b3c2be743d5a93e1 incorrectly documented this as being related to the db mode read/write *mode*, and also used it that way in the python bindings.
While looking at this, noticed that ndb passes hardcoded 0666 to open() whereas the rpm default open mode is 0644, use the API-requested mode instead. Sqlite doesn't seem to support passing a file mode request in the API (but it defaults to 0644 too).
=> Fix rpmtsInitDB() argument confusion

tests/rpmgeneral.at
If $TAPE is set tar uses the tape drive instead of stdout as default.
The rpm2archive test assumed that tar will just use stdout no matter what.
Force this behaviour per command line option.
Resolves: rhbz#1902844
=> Fix test cases failing on systems with tape drives

INSTALL, Makefile.am, build/Makefile.am, build/parsePreamble.c, build/parseScript.c, build/spec.c, ci/Dockerfile, configure.ac, lib/rpmds.c, lib/rpmrc.c, lib/rpmscript.c, rpmio/Makefile.am, rpmio/macro.c, tests/atlocal.in, tests/rpmbuild.at, tests/rpmbuildid.at, tests/rpmmacro.at, tests/rpmreplace.at, tests/rpmscript.at, tests/rpmvercmp.at, tests/rpmverify.at
More and more macros, scriptlets and other functionality has been getting
built around Lua, to the point that it has in practise been required for
several years now.
Maintaining the pretense of being optional comes at a cost in holding
back developments and having to check for that theoretical special
case. Lets make it a hard requirement and embrace it some more!
=> Make Lua a hard requirement for rpm

tools/debugedit.c
Append '/' to directories in source file list (for `-l' option) to allow
quickly distinguish them from regular files (to avoid adding them raw
into %files section). This is needed for ALT for our debuginfo
processing to speed things up.
Co-authored-by: Dmitry V. Levin <ldv@altlinux.org>
@ldv-alt
=> debugedit: Distinguish files from directories in src list file

tests/debugedit.at, tools/debugedit.c
Resubmitting patches posted on rpm-maint: http://lists.rpm.org/pipermail/rpm-maint/2021-February/016462.html
=> DWARF-5 support in debugedit

lib/fsm.c, lib/rpmfiles.h, tests/data/SPECS/hlinktest.spec, tests/rpmbuild.at, tests/rpmi.at
Run the file installation in multiple stages:
1) gather intel
2) unpack the archive to temporary files
3) set file metadatas
4) commit files to final location
5) mop up leftovers on failure
This means we no longer leave behind a trail of untracked, potentially harmful junk on installation failure.
If commit step fails the package can still be left in an inconsistent stage, this could be further improved by first backing up old files to temporary location to allow undo on failure, but leaving that for some other day.
Also unowned directories will still be left behind.
And yes, this is a somewhat scary change as it's the biggest ever change to how rpm lays down files on install.
Fixes: #967 (+ multiple reports over the years)
Details in commit messages, there are several preparatory commits …
=> Handle file install failures more gracefully

doc/manual/spec.md
This was still missing from the Spec syntax documentation
=> Add section for %generate_buildrequires to the manual

lib/header.c
Negating INT32_MIN is undefined behavior, so we must prevent it.
=> Avoid negating an attacker-controlled signed integer

lib/header.c
Unary `-` has a higher precedence than binary `/` in C.  Found by UBSAN
and libfuzzer.
Fixes c3e04c2ac91737b06ce5592e8cd8558498e566c0
=> Ensure negation comes *after* division

lib/header.c
The ‘end’ parameter to ‘strtaglen’ might point past the end of an
allocation.  Therefore, if ‘start’ becomes equal to ‘end’, return an
error without calling ‘memchr’ on that pointer.
=> Avoid incrementing a pointer past the end

lib/header.c
This prevents integer overflows.
=> Check that len is in range before using it

lib/header.c
With the changed logic, the if-clause can fall through without ever
initializing s. The exit code condition is getting more complicated
now so move it to helper variable, assume failure for a safe default.
Fixes: 165330b7bf0757e30fa8a6de9998a564fb62796f
=> Fix regression from commit 165330b7bf0757e30fa8a6de9998a564fb62796f

lib/fsm.c, lib/rpmarchive.h, tests/rpmi.at
Details in commit messages, but brief summary:
- add some missing diagnostics to file unpacking and hardlink handling
- always use the same code path to unpack files
- streamline the hardlink logic, consolidate to one place
- fix a case where partially skipped hardlink set will miss their metadata getting set
This deserves some specific test-cases as well. Will add, but don't let that prevent reviewing otherwise. The hardlink logic with the skipped files scenarios and all is a tricky piece of code.
=> Hardlink handling cleanups + fixes

lib/backend/sqlite.c
Commit fb5888417727edbd8ce1b389b1b6ee9ac899d8e4 introduced a regression
where on database open failure we end up accessing the already freed
handle when trying to report the error.
Now that we're no longer implicitly creating non-existent databases,
just simplify the whole logic to get rid of it. 4.16.x branch will need
a different fix, maybe use sqlite3_errstr() instead of _errmsg().
Reported and initial patch by Demi M. Obenour.
=> Fix regression causing access to already closed sqlite handle

lib/headerutil.c
Found by fuzzing rpmReadPackageFile() with libfuzzer under ASAN.  I didn’t include a regression test because I am not sure how best to write one for this kind of bug.  In any case, this is a minor bug.
=> Fix a tiny memory leak

lib/poptALL.c, tests/rpmmacro.at
Since --eval only has one job - to actually *print* something to stdout,
we should fail completely if that's not possible due to an external
error, instead of just not printing anything.  One particular case is
redirecting stdout to a file on a file system that's full (generating
the ENOSPC error).
In order to be able to detect such errors, we need to flush the stream
buffer first; that's because normally, if stdout is not referring to an
interactive device (a terminal), it is block-buffered, as opposed to
line-buffered.
=> Error out on --eval if stdout write fails (#1444)

lib/header.h, python/header-py.c, sign/rpmgensig.c
headerLoad(), headerCopyLoad() and headerUnload() have been deprecated as unsafe since rpm 4.10, time to start pushing them out for real. The first two are unsafe because they don't take argument for size, the last one is because it doesn't return one so it forces using the unsafe variants.
Eliminate remaining in-tree uses of the unsafe variants and issue compile-time deprecation warnings on them now that we can.
=> Really deprecate headerLoad(), headerCopyLoad() and headerUnload()

doc/rpm.8, lib/formats.c, lib/rpmtd.h, tests/rpmquery.at
Though I added these ages ago along with the arraysize thing, but guess
not.
=> Add query formats for displaying tag numbers and names

lib/rpmts.c, macros.in
Using filesystem as keyring is an unfinished development idea from 2008
which has somehow lingered on ever after.
The fs keyring behavior has potential security problems as it allows any
package to drop in files at the keyring path, instantly becoming trusted
keys.  In some scenarios this may be a desireable feature though, and
apparently some distros (Yocto at least) actually rely on this feature.
The other issue is that the on-disk and rpmdb variants don't play well
together, in fact they don't play together at all.
The rpm keyring needs a thorough redesign but until then we don't want
to force users to adjust to something that is also destined to go away.
So in the meanwhile, let people choose with a macro which behavior they
want, using a macro seems the lowest bar to cross. Add new …
=> Make the rpmdb keyring type macro-configurable

lib/header.c, sign/rpmgensig.c
=> rpmsign: support EdDSA signatures

lib/poptALL.c
It is possible for fprintf to have flushed the stream already, in which
case fflush will succeed.  Use ferror() to catch that.
Fixes 95a83332ac89e06708741e7074760981a417e64d.
=> Better detection of I/O errors

lib/package.c
Only look for known tags, and ensure correct type and size where known
before copying over. Bump the old arbitrary 16k count limit to 16M limit
though, it's not inconceivable that a package could have that many files.
While at it, ensure none of these tags exist in the main header,
which would confuse us greatly.
This is optimized for backporting ease, upstream can remove redundancies
and further improve checking later.
Fixes: RhBug:1935049, RhBug:1933867, RhBug:1935035, RhBug:1934125, ...
Fixes: CVE-2021-3421, CVE-2021-20271
=> Be much more careful about copying data from the signature header

configure.ac
-fno-strict-overflow tells gcc and clang to handle signed integer and (at least on gcc) pointer arithmetic wraparound using twos-complement representation like deity intended.
-fno-delete-null-pointer-checks tells gcc not to "optimize" away programmer added safeguards. Really.
Suggested by Demi Marie Obenour.
While at it, clean up some excess flags that have no business in upstream defaults, such as -fstack-protector which has caused us various headaches over the years.
Replaces #1501
=> Restore (some) compiler sanity

lib/backend/bdb_ro.c
The other backends would want to create the missing index, but as bdb_ro is read-only it can't do that. As the main purpose of bdb_ro is to support migrating away from BDB for which only the primary database is needed, it doesn't make sense to fail it for non-essential data. Let it fail for secondary indexes - this might affect our ability to query but that's secondary, literally, and we also do emit a warning here.
Fixes: #1576
=> Permit secondary index open to fail for bdb_ro

lib/header.c
The count can never be larger than header data size, which can never be
larger than 256MB. Most datatypes have further restrictions of course, this
is merely an outer perimeter check to catch impossibly large values that
could otherwise overflow all manner of trivial calculations.
Addresses the point I missed in PR #1493 but with a much tighter limit.
=> Better sanity check for header entry counts

lib/header.c
This introduced regressions rather than fixing something, len *is*
in range because it's capped to header size already.
This reverts commit a1344cf2a5447b442af5ef68848e13114051ca63.
=> Revert "Check that len is in range before using it"

rpmio/macro.c
The old logic always finished adding lines if an empty line
was encountered, because the check that should guard against
accessing outside of the read buffer was done at the wrong
level.
Also simplify the code by letting 'q' point to the new line and
not before the newline, which also fixes potential undefined
behaviour.
Also get rid of the unused 'nread' variable.
=> Fix logic error in macro file reader

rpmio/rpmio.c
This was found by running the testsuite under `-fsanitize=address`.
=> rpmio: avoid reading past the end of the mode string

python/rpmarchive-py.c
The current argument string mentions an optional integer argument, which does not exist.  This is probably a copy & paste from `rpmarchive_readto`.
=> Fix incorrect rpmarchive_writeto argument string

build/files.c, doc/manual/spec.md, scripts/check-files, tests/data/SPECS/hlinktest.spec, tests/data/SPECS/test-subpackages-exclude.spec, tests/rpmbuild.at
Turns out people are using %check in various "unexpected" ways, some of
which are also tied to our long-standing %exclude semantics. We need
need better %check which doesn't rely on or allow messing with actual
buildroot contents, but there's simply too much plate for a too short
a time-frame to try and do that. Revert to old buggy buildroot checking
to give time to come up with better solutions to the %check issues.
This reverts c1ca2e35025698328edcefa8dedee866d2ea0596 and
1110c280639b66c89da19a0f831af28845591997.
=> Revert strict buildroot content checks for now

lib/fsm.c
Commit f9b90179b7c80a170969d9ab4c77c0a311635e3f added debug logging for
file sizes which are 64bit in rpm, and %lu is not guaranteed to be
64bit.
Fixes: #1605
=> Fix 32bit compiler warning in recently added fsm debugging

lib/rpmts.c
At makePubkeyHeader(), the key has PGP data collected already,
so rpmPubkeyDig() is redundant. And, since the former is the only
user of the latter, which, in turn, mostly duplicates the
functionaliry of rpmPubkeyNew(), rpmPubkeyDig() may be dropped.
=> Simplify pubkey header building code

rpmio/rpmlua.c
Refuse to run rpm.interactive() unless running from tty as a minimal requisite.
Make the interactive loop print results immediately instead of process exit, eg:
```
$ ./rpm --eval "%{lua:rpm.interactive()}" 
RPM Interactive Lua 5.4 Interpreter
> print(macros['_libdir'])
/usr/lib64
> a=5
> =a
5
> =rpm.vercmp('1.0-1', '2.0-1')
-1
```
= being an undocumented shortcut to print()
=> Make interactive Lua mode actually interactive

lib/query.c, lib/rpmtag.h
RPM_NULL_TYPE is not a legit tag type, but RPM_MIN_TYPE is defined
and used as if it was. Change RPM_MIN_TYPE to 1 to make the MIN-MAX
range actually relevant, in particular for hdrchkType(). Also fix
the lone user who in query code who clearly had encountered this very
issue before but worked around locally...
Reported and initial patch by Demi Marie Obenour.
=> Fix RPM_MIN_TYPE definition, RPM_NULL_TYPE is not a legit tag type

lib/depends.c
Disabling implicit database creation on read-only handles in commit
afbc2b07839c9ffe9f274f3a4bc2395c76d65472 broke number of handy
use-cases such as install to an empty chroot directory, both with
rpm itself and dnf/yum at least, probably others too.
This minimally resurrects the desired part of the behavior: if people are
asking us to install something, creating a missing database is probably
okay to create without requiring an explicit --initdb action first.
It'll still spit some ugly errors from trying to load the keyring but
at least it'll work. The harmless errors we can try to deal with
separately later on.
=> Ensure database creation on initial installation

lib/header.c
Commit c3e04c2ac91737b06ce5592e8cd8558498e566c0 tried to address
a theoretical issue with undefined behavior but cause a regression
which was fixed in commit 1efe530450b5bdbd90128327be56c87fa1b6843b
which introduced another regression: package reading on 32bit
architectures is broken. Enough is enough. Revisit some day with
an actual plan.
This reverts commits c3e04c2ac91737b06ce5592e8cd8558498e566c0 and
1efe530450b5bdbd90128327be56c87fa1b6843b.
=> Revert trailer offset negation fiddling, too many regressions

build/files.c
parseForAttr is missing the check for the closing paren.  When a malformed
rule is encountered, the bounds for the end of the rule will be the NUL
terminator for the string.  When it overwrites the rule with spaces,
the entire string, including the NUL terminator, will be overwritten.
Later, in parseForSimple, the string will no longer contain a pathname and
will fail the check for files beginning with /.  Since the string is also
no longer NUL terminated, the error will contain garbage like the following:
error: File must begin with "/": nÔLó_;^?
Adding the check for the closing paren fixes the issue.
Fixes: #1648
=> Handle missing closing paren in %attr rules

lib/backend/ndb/glue.c, lib/backend/sqlite.c, lib/depends.c, lib/rpmdb.c, tests/rpmdb.at
The implicit database creation even on read-only access is rooted so
deep in so many places that this needs more thought and saner APIs.
While creating databases on read-only access remains a crazy thing to
do, we need to have a proper solution to point people to when changing
the behavior, and right now we don't.
This effectively reverts 86f593d5135b00a9dbf7dc6d5efc8b341002aa08,
d601a7b7ae764b31ad74b2dceff1eafb5297147f and
afbc2b07839c9ffe9f274f3a4bc2395c76d65472, but adopting 4.16.x version
of the sqlite open error message to avoid accessing freed handle, and
leaving the testcase for query on non-existent db in place (just
changing the expected result) as this is a rather fundamental behavior thing.
=> Revert back to implicit database creation for now

build/Makefile.am, build/spec.c, lib/Makefile.am
Since commit 376fef14a61a9748ce004888fe19445719a5d2d5 librpmbuild is
calling Lua directly rather than through the rpmio wrapper layer, so
librpmbuild needs LUA_CFLAGS and LUA_LIBS for building. While librpm
does not currently call Lua directly, make native Lua available there
as well as it's only a matter of time.
=> Fix build regression from 376fef14a61a9748ce004888fe19445719a5d2d5

rpmio/macro.c, tests/data/macros.testfile, tests/rpmmacro.at
Previously %{ and similar in macro file comment line would cause the
line continuation logic to trigger and silently eat macro definitions
up to the next empty line. Since 75275a87cff04da65d3557f2c40ea2b526528c4c
we permit empty lines inside macro definitions, which would cause the
whole remaining file to be silently skipped (RhBug:1953910)
Only ever parse macro file lines starting with %, and add a test for
the case.
Actual patch by Michael Schroeder, testcase by undersigned.
Fixes: #1659
=> Ignore comment line contents in macro files (#1659)

doc/manual/queryformat.md
to avoid gh-pages taking them as Liquid tags
See https://shopify.dev/docs/themes/liquid/reference/tags for details.
=> Insert space between the "{" and "%"

build/parsePreamble.c, build/rpmbuild_internal.h, build/spec.c, build/speclua.c, tests/rpmpython.at
Commit 2579d3e5ad5d713f2c161b9fb4835366ea4ea291 started storing the Lua
context in the spec, but this leads to problems as what is actually a
global context is now stored in two places, and can get out of sync.
So if you parse a spec, and then reset the global context, you get a
fancy segfault when the freeing the spec because it's pointing to
la-la-lua land.
Revert back to always using the global Lua handle.
=> Fix regression wrt Lua reinitialization (RhBug:1958095)

doc/rpm2archive.8, rpm2archive.c
Also use popt for the command line handling. As we are using librpm
anyway there is no reason to keep the dependencies low (as with
rpm2cpio).
Resolves: #1530
=> Add --nocompression option to rpm2archive

lib/package.c
Commit d6a86b5e69e46cc283b1e06c92343319beb42e21 introduced far stricter
checks on what tags are allowed in signature and main headers than rpm
had previously seen, and unsurprisingly this introduced some regressions
on less common cases:
- On rpm v3 packages and some newer 3rd party created packages (such as
install4j < 9.0.2), RPMTAG_ARCHIVESIZE resides in the main header
to begin with
- In rpm 4.13 - 4.14, file IMA signatures were incorrectly placed in
the main header.
As a quirk, permit the existence of RPMTAG_ARCHIVESIZE,
RPMTAG_FILESIGNATURES and RPMTAG_FILESIGNATURELENGTH in the main header
too provided that the corresponding signature tag is not there (so
they can reside in either but not both headers).
Initial workaround patch by Demi Marie Obenour.
Fixes: #1635
=> Fix regression reading rpm v3 and other rare packages (#1635)

lib/depends.c, tests/rpmdeps.at
Commit ddb32b9187e9ce85819a84ca8d202131fd9f8b9f added an
extra check that tests if the provide we are checking really
intersects the dependency from rpmdb. Unfortunately the
rpmdsCompare() call does not understand rich dependencies and
will consider them as not intersecting.
Unbreak the check by not doing the intersection test for
rich dependencies. We'll improve this in a later commit.
Also add test cases for dependency problems with installed
rich dependencies.
=> Unbreak checking of installed rich dependencies

platform.in, scripts/Makefile.am, scripts/brp-remove-la-files
Lots of packages remove .la files via
find $RPM_BUILD_ROOT -name "*.la" -delete
or similar. Add %remove_installed_la_files to standardize this.
I could not find tests for the macros in the rpm repository, but I testes this separately in a spec file. I went with `-delete` here and not `exec rm -f {} \;`. It might also be worthwhile to add `-print` as well.
Thoughts?
=> macros: Add %remove_installed_la_files

lib/backend/bdb_ro.c
In Hash v8 databases page type differs from newer ones to denote
the difference between sorted and unsorted pages.
Fixes reading rpm databases from older distros like SLES 11 and RHEL 5
(RhBug:1965147)
=> Support hash v8 databases from BDB < 4.6  in bdb_ro

rpmio/rpmpgp.c
Couple of very clear bugs in the decoding detection + additional bounds checks, based on patches from @DemiMarie spread across different PR's.
It's plain impossible to review multiple partially overlapping 10+ commit PR's of assorted changes in the GH interface, and we need to get this stuff moving forward one way or the other.
=> Fixes to PGP packet length decoding detection and calculation

rpmio/rpmpgp.c
Reject unimplemented critical PGP packets as per RFC-4880
Bit 7 of the subpacket type is the "critical" bit.  If set, it
denotes that the subpacket is one that is critical for the evaluator
of the signature to recognize.  If a subpacket is encountered that is
marked critical but is unknown to the evaluating software, the
evaluator SHOULD consider the signature to be in error.
We only implement creation time and issuer keyid, everything else is
unimplemented and should be flagged as an error if critical as per above.
Initial patch by Demi Marie Obenour.
=> Reject unimplemented critical PGP packets as per RFC-4880

lib/rpmds.c
As we allow dependeny flags like pre, post, ... in the spec syntax we
should not remove them when reading in the tags from a package.
Thanks to Michael Schröder for spotting this.
Resolves: #1703
=> Don't strip flags for OrderWithRequires in rpmds

docs/manual/autosetup.md, macros.in
There are cases where "apply 'em all" doesn't cut it, and passing
-m and -M is cumbersome for individual patches. Add support for
applying individual patches by passing their numbers as arguments,
update documentation.
=> Support individual patch application in %autopatch

rpmio/rpmpgp.c
According to RFC 4880 § 11.4, a detached signature is “simply a
Signature packet”.  Therefore, extra packets following a detached
signature are not allowed.
=> Do not allow extra packets to follow a signature

rpmio/rpmpgp.c
This will be used to replace incorrect checks in the calling code.
The new pgpGet() avoids undefined pointer arithmetic, too.  One
call-site of pgpGet() is broken by this change, so replace it with a
direct bounds-check.
=> pgpGet(): check that the returned length is in bounds

rpmio/rpmpgp.c
This is mostly for the benefit of fuzzers and other automated tools, and
for compilers other than GCC.  On modern versions of GCC with
-fno-strict-overflow, this is harmless.
If such patches are not desired, feel free to close this PR.
=> Reduce undefined pointer arithmetic

lib/header.c
The undefined behavior is not an issue on modern GCC, but the new code
is easier to read.
=> Make a bounds check easier to read

tests/rpmi.at
A nice little WTF this one: changing the version string length affects
the manipulated offsets in the built package. The offsets were done with
the development time 4.16.90 version, but with eg 4.17.0-beta1 the
offsets are different and the test fails.
=> Make hardlink test independent of rpm version string

scripts/check-rpaths-worker
These curly brackets are already treated as literals by the shell, so
let's make that explicit for clarity, and silence a ShellCheck warning
at the same time.
More info: https://github.com/koalaman/shellcheck/wiki/SC1083
Found by ShellCheck.
=> Add quoting to literal curly brackets

lib/package.c
Hi,
First of all, thanks a lot for working on rpm and the related projects!
The d6a86b5e69e46cc283b1e06c92343319beb42e21 commit introduced
a new variable that is only used internally by headerMergeLegacySigs().
If it is not really intended to be exposed to consumers of librpm's public API,
it should not be present there or somebody may start depending on it, making it
harder to change or remove it later.
Thanks in advance for your time, and keep up the great work!
G'luck,
Peter
=> Exclude the xlateTags symbol from librpm's public API.

lib/backend/sqlite.c
We must avoid the "database is locked" errors at every cost because
otherwise the rpmdb gets corrupted and system ends up in inconsistent
state.
Resolves: rhbz#1946046
=> Set an extremely high sqlite3 timeout

scripts/brp-strip
Otherwise SecureBoot signatures may be stripped too.
We used to exclude shared libraries from this strip as they were
supposed to be covered by another brp script (brp-strip-shared), however
it turned out the latter was never really used, so we removed the
exclusion in commit 0ab151ab138fd4fb6d3176fd0270d9cc6f4623f3.
As it turns out, that was a little too ambitious, since we may now
inadvertently strip SecureBoot signatures from kernel modules too,
provided that they're made during the build, prior to the invocation of
brp-strip.
Note that this regression currently does *not* affect the following two
cases on Fedora/RHEL systems with redhat-rpm-config installed:
- in-tree modules; these are built from kernel.spec which already
contains a hack ensuring that module signing only happens …
=> Don't brp-strip .ko files

INSTALL, configure.ac
Hi,
First of all, thanks a lot for working on rpm and the related projects!
The 986be669fb037ae0e2049a2022c4fdfa05da6747 commit introduced a use of
lua_rotate(), which is not available in Lua 5.2. Hence, bump the dependency in
the configure script's pkg-config check.
Thanks in advance for your time, and keep up the great work!
G'luck,
Peter
=> Bump the Lua minimum version to 5.3.

lib/backend/ndb/glue.c
We now only invaludate the cache if the cached entry is written
or deleted. This is needed for the code in rpmdbNextIterator()
which first reads the next header and then writes the modified
old header to the database. Therefore we must not free the cache
if a modified header with a different id is written.
=> ndb: only invalidate the database cache if we must

docs/man/Makefile.am, docs/man/rpm-plugin-dbus-announce.8.md, macros.in, plugins/Makefile.am, plugins/dbus_announce.c, plugins/org.rpm.conf
The plugin announces start and completion of transactions and
the installation and erasure of packages.
The patch still needs some polishing:
* Names of the DBus enities may need a second thought
* Man page is still missing a description of the dbus signal sent
* DBus config is not properly integrated into Makefile
Resolves: #1249
=> Add dbus-announce plugin

docs/man/rpm.8.md, lib/poptQV.c, lib/query.c, lib/rpmcli.h, tests/rpmquery.at
* Add the `--allfiles` switch which augments `-qf`
* Add a basic test for `-qf` while at it
* Update the list of possible file states in the man page (needed for consistency with the new `--allfiles` description)
=> Add support for RPMDBI_BASENAMES on file queries

misc/fts.c
The Apple Silicon toolchain removes the *64 stat symbols (deprecated
since 10.6) in favour of their unprefixed form.
This change might not work properly before 10.6, but 10.5 has been out
of support for over a decade, so that hopefully shouldn't be relevant.
Fixes #1752.
=> Fix fstat64 handling on macOS with Apple Silicon

scripts/brp-compress
Filenames with space in filename will not be handled correctly by brp-compress script. This means that variation in space and other special characters will cause problems.
Example:
```sh
$ ls /usr/share/man/man1
'test file.1'
```
```sh
$ sh /tmp/brp-compress ; ls /usr/share/man/man1
'test file.1'
```
=> Fix handling filenames with spaces in brp-compress

configure.ac
This adds the ability to explicitly disable support for libelf w/ --disable-libelf while still defaulting to building w/ libelf. Useful for cross environments targeting non-ELF platforms.
=> Allow disabling libelf with --enable/--disable-libelf

macros.in, tests/Makefile.am, tests/data/SPECS/hello-autopatch.spec, tests/rpmbuild.at
Those where not converted to integers for to lookup though not converted
to the actual file name.
Thanks to Vít Ondruch for pointing this out, suggesting the fix and
insisting on a test case!
Resolves: #1766
=> %autopatch: Fix patch number parameters

docs/manual/macros.md, lib/formats.c, rpmio/macro.c, tests/rpmmacro.at
This is exactly the same as :shescape query format, hence the name.
=> Add %{shescape:...} macro for single quoting with escapes for the shell

scripts/brp-strip
Not 100% sure if this "no machine" business is 100% correct. But it looks like a better defense against `strip` failing than relying on the file name alone.
=> Don't strip *.go and ELF files with "no maschine"

lib/rpmfi.c
No point in allowing NULL only for one of the arguments.
Thanks to ex0z3 (https://github.com/ex0z3) for reporting!
Resolves: #1782
=> Check file iterator for being NULL consistently

ci/Dockerfile
Been stuck on Fedora 32 for too long anyhow, but for debugedit we need
at least 35. Kick out a BDB remnant while at it.
=> Drag our CI to this decade

po/zh_CN.po
Original translation for 'hash' in Chinese meant the kind of 'hash' in SHA instead of '#'. 
Such mistaken may caused by a lack of context when translating, that made the translate totally wrong for the option
Translation in this commit meant 'show a progress bar made up of # notation for installing'
=> Correct Chinese translations for '-h' option in command line

fileattrs/ocaml.attr, scripts/ocamldeps.sh
OCaml cmxs files are static libraries, which can be loaded at runtime
via the Dynlink module. They apparently do not provide any useful
runtime dependency information to be stored into the packages
Provides/Requires list. Therefore just skip them.
Adjust attr, remove extension and ELF magic
Adjust ocamldeps, do nothing with cmxs files.
Fixes: a6fe37c39b39acbcbd014dd1e6d5653ff84254a1
Signed-off-by: Olaf Hering <olaf@aepfle.de>
=> Update OCaml requires/provides to ignore cmxs

scripts/check-rpaths-worker
The `$lower` variable is always empty, see https://bugzilla.redhat.com/show_bug.cgi?id=2019804
This also changes the badness 32 message to say "a rpath" or "a runpath" which isn't perfect, but is certainly better than "an runpath".
=> Fix broken output of check-rpaths-worker

scripts/brp-strip
The original commit might have seemed like an easy remedy for
third-party modules affected by commit 0ab151a (such as rhbz#1967291),
but it also prevents the modules built from the kernel tree (which
employ a different signing strategy, see below) from being stripped off
of debug and symbol data, so it's not the correct solution after all.
Simply put, *.ko files *are* ELF files, so there's no good reason to
skip them.
Third-party modules should instead adopt the same hack as the in-tree
ones, i.e. overriding the %__spec_post_install macro so that the signing
occurs as a last step, after any kind of stripping has taken place.
Example from kernel.spec:
%define __modsign_install_post \\
\# Do the signing here
[...]
%define __spec_install_post \\
\# eu-strip(1) gets called here …
=> Revert "Don't brp-strip .ko files"

scripts/brp-remove-la-files
Try to minimize accidentally removed .la files that aren't libtool .la
files.
I wasn't sure if there's a better way to do this than the manual loop, but here it is.
This is the result of  the discussion in https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/AMKKEGJZBMPE4IQHKGR65RXKF2NALSOP/
=> remove-la-files: Use file to check for libtool files

rpmio/expression.c, rpmio/rpmlua.c, rpmio/rpmlua.h, tests/rpmmacro.at
Lua functions start with a "lua:" prefix. The result of the function call is always stringified, nil is translated to the empty string.
=> Allow to call lua functions from the expresion parser

python/rpmfiles-py.c
Only, use more descriptive names than the C-side counterparts.
Python has nice facilities for dealing with binary data so return it
as such rather than converting to hex.
=> Add Python bindings for rpmfilesFSignature() and rpmfilesVSignature()

build/build.c, rpmio/rpmlog.c, rpmio/rpmlog.h
Confusingly, the "RPM build errors" section also includes messages
logged as warnings.  That gives the false impression that they somehow
contributed to the actual build failure and therefore were turned into
errors.
This appears to be a historical artifact; when a message passes through
the logging system and is of the priority RPMLOG_WARNING or higher, we
save it in a global buffer (ctx->recs), which is then simply dumped with
rpmlogPrint() in the error summary.  This was probably good enough when
the summary was introduced (commit f2efc72, year 2000), as there were
almost no warnings generated by RPM at that time, however as they became
more abundant, the summary code was never revisited.
There are 3 ways to fix this discrepancy:
1) Change the summary's title to "RPM build problems"
2) …
=> Separate build warnings from error summary

lib/rpmscript.c, rpmio/rpmlua.c, rpmio/rpmlua.h
This screams for a closure, use one. This is not supposed to change
any functionality.
If you wonder about the date, this is indeed a leftover from last years Lua campaign, forgotten for whatever reason which I've also forgotten.
=> Eliminate static rpm.next_file() from the Lua API

Makefile.am, docs/man/Makefile.am, docs/man/rpmlua.8.md, docs/manual/lua.md, po/POTFILES.in, tests/Makefile.am, tests/data/t1.lua, tests/rpmmacro.at, tools/rpmlua.c
Being able to run stuff easily in rpm context helps developing and debugging
scriptlets and macros too. Supports running one-liner statements from
the cli, regular scripts and an interactive session.
This is placed into a separate executable for, well, separation and
simplicity, but it'll also give us means to link to readline without
dragging that to main rpm dependencies (but that's left for later).
=> Add rpmlua wrapper command for running our Lua interpreter standalone

docs/manual/relocatable.md
Manual page Relocatable Packges was corrupted
due to use of unescaped angle brackets `<` and `>`.
Parser attempts to interpret these as a html tag.
Fixed by escaping the brackets with `\`.
=> Fix Relocatable Packages manual page formatting

build/rpmfc.c
Here is simplified overview of possible dereference:
```cpp
if (fc == NULL) {
rpmlog(RPMLOG_ERR, _("Empty file classifier\n"));
goto exit;
}
// ...
exit:
rpmstrPoolFreeze(fc->cdict, 0);
~~~~~~~~~
```
This issue was found by Svace Static Analyzer.
=> Fix possible NULL pointer dereference in rpmfcClassify

rpmio/rpmpgp.c
Make sure selfsig is freed in case we break out of the loop in this
block.
Note that the tests added with the binding validation commit bd36c5d do
not cover this code path so valgrind won't show this.
=> Fix memory leak in pgpPrtParams()

sign/rpmgensig.c
pgpPrtParams() may leave sig2 unchanged and if we're not in the very
first iteration of the while() loop, we could pass a freed pointer to
pgpDigParamsCmp().  Fix by setting it to NULL after freeing.
=> Fix use-after-free in haveSignature()

build/parsePreamble.c
We are using weak dependency for ordering now. So it make sense to also
qualify weak dependencies with the time they are needed/wanted in the
transaction to make use of this information in ordering.
Especially (posttrans) could be useful to remove weak deps from dependency
loops during ordering when they are only needed after the installation.
Resolves: #624
=> Allow qualifiers like pre, post, preun, ... for weak dependencies, too

sign/rpmgensig.c
While signing an rpm package the file descriptor is not closed before replacing the signature.
For example, this could be a problem if the rpm --addsign is called in a virtual machine on Windows with a NTFS shared folder:
```
rpmsign --addsign --signfiles ... "untitled-0.1-1.i486.rpm"
untitled-0.1-1.i486.rpm:
error: replacing untitled-0.1-1.i486.rpm failed: Text file busy
```
=> Close file before replacing signed

configure.ac
Hi,
Thanks a lot for developing and maintaining RPM and the related tools and libraries!
The Debian package of rpm was found to build incorrectly on the armhf (arm7hl-linux) architecture. It turns out the cause is that the configure script does not recognize the -gnueabihf (not -gnueabi) suffix and does not strip it correctly.
What do you think about these two changes? The first one teaches configure about the -gnueabihf suffix, and the second one attempts to make it easier to catch future occurrences of this issue early.
Thanks in advance for your time, and keep up the great work!
G'luck,
Peter
=> Fix a couple of issues with removing the GNU suffixes from the target triplets.

tests/rpmquery.at
These three changed tests were failing, on at least aarch64, due to
architectural incompatibility errors on installing the
`hello-1.0-1.i386.rpm`, though the tests themselves aren't concerned
with executing the binaries, just querying the installed files. Thus, we
can just install them with `--ignorearch`.
On a Fedora 35 EC2 `m6g.8xl` host:
```
$ uname -a
Linux ip-172-31-51-16.us-west-2.compute.internal 5.15.11-200.fc35.aarch64 #1 SMP Wed Dec 22 15:23:21 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
On `master`:
```
$ podman build -t rpm -f ci/Dockerfile .
$ podman run --rm rpm
...
ERROR: All 490 tests were run,
6 failed (3 expected failures).
Failed tests:
rpm 4.17.90 test suite test groups:
NUM: FILE-NAME:LINE     TEST-GROUP-NAME
KEYWORDS
206: rpmquery.at:206    rpm -qf
query
207: …
```
=> Fix failing 'rpm -q' tests on non-i386-derived arches

lib/backend/ndb/rpmpkg.c
The descriptor is openned in rpmpkgOpen, and we treat 0 as valid file descriptor.
Here we should do the same or fail earlier.
=> treat 0 as valid file descriptor

rpmpopt.in
Since we record the symlink permission bits (777) in the database and
chmod(1) affects the pointed-to file (not the symlink itself), applying
these bits to anything on the file system would either be pointless (a
symlink) or an error (a ghost file present as a regular file but
recorded as a symlink in the database).
The former is already handled with the -L test, this commit handles the
latter.
=> Skip recorded symlinks in --setperms (RhBug:1900662)

rpmkeys.c, tests/rpmsigdig.at
If writing to stdout or stderr fails, rpmkeys should exit with a
non-zero status code.
=> rpmkeys: exit non-zero on I/O errors

docs/manual/lua.md, lib/rpmscript.c, tests/Makefile.am, tests/data/SPECS/reloc.spec, tests/rpmi.at
Pass relocatable package prefixes as RPM_INSTALL_PREFIX Lua table
to Lua scriptlets, add a test-case.
In Lua, indexes start at 1 rather than 0, so the numbers appear
off by one which is annoying, but consistent within Lua and our other
similar Lua constructs.
Fixes: #1531
=> Support relocatable packages in Lua scriptlets too (#1531)

fileattrs/Makefile.am, fileattrs/rpm_macro.attr, scripts/Makefile.am, scripts/rpm_macros_provides.sh
This commit adds a very simple provides generator for rpm macros as suggested on the Fedora packaging mailing list:
https://lists.fedoraproject.org/archives/list/packaging@lists.fedoraproject.org/thread/DUFER7QAFYIBYDANJQQ37FBNL5YISZQ2/
cc @hroncok @Conan-Kudo
=> Add a rpm_macro() provides generator

misc/fts.c
ad87ced fixed compilation for ARM64 macOS, but it broke builds on Intel
macOS.
Let's fix it by gating the changes from ad87ced behind
`_DARWIN_FEATURE_ONLY_64_BIT_INODE`. This macro is defined whenever the
ARM64 macOS fix is appropriate, but only after we've included
`sys/cdefs.h`.
This does mean that we're still using a deprecated API on Intel macOS
10.6+. I looked into avoiding this, but it seems to require more
significant refactoring. It's not clear that more significant changes would be
worth it given that Apple is slowly phasing out their Intel machines.
=> Fix stat64 handling on Intel macOS

rpmio/rpmpgp.c
If a public key was too short for the curve ID, the code would
previously perform out-of-bounds pointer arithmetic, which is undefined
behavior in C.  Check that the packet is long enough to contain the
curve ID before bumping `se` past the curve ID.
Furthermore, if a public key is too short to even contain the fixed-size
header, an out-of-bounds pointer would be created, which is also
undefined behavior.  Fix this by returning early if the buffer is too
short.
Finally, return early if the public key algorithm or curve ID is
invalid, rather than relying in processMpis() to fail.  While
processMpis() will error out, bailing out explicitly is much clearer.
=> Fix bounds checks in public key parsing

docs/man/rpm.8.md
Signed-off-by: Thomas Moschny <thomas.moschny@gmx.de>
=> Explicitly state that \0 is not supported in queryformat strings.

lib/poptALL.c
by checking for error log entries. Issues in the macro files also
trigger the EXIT_FAILURE exit code.
Resolves: #1796
=> Make exit code reflect broken rcfile on --showrc

lib/rpmdb.c
The rpmdb cookie is not a security feature, but as these existing
hashes are more convenient than coming up with our own... we then
run into the great big wall of FIPS which in its current incarnation
disallows use of SHA1. And so rpmdbCookie() fails under current FIPS.
Just bumping the algorithm to SHA256 seems the path of lowest
resistance, whether that algo makes sense for this purpose or not.
=> Bump hash for rpmdb cookie to SHA256 to appease FIPS

docs/man/rpm.8.md, lib/depends.c, lib/fsm.c, lib/order.c, lib/poptI.c, lib/psm.c, lib/rpmcli.h, lib/rpminstall.c, lib/rpmte.c, lib/rpmte.h, lib/rpmte_internal.h, lib/rpmts.h, lib/transaction.c, python/rpm/transaction.py, python/rpmts-py.c, rpm.c, rpmpopt.in, tests/rpmpython.at, tests/rpmverify.at
--setperms, --setugids and --setcaps were fun demos of alias capabilities
in the nineties, but they can be downright dangerous when used
separately, are blisfully unaware of all state in rpm yet try to
duplicate functionality existing in C, and thus are a constant source
of bugs that are between hard to impossible to fix in the alias space.
Add a new transaction element type for the restore operation, wire
through all the necessary places. In places (like ordering) this is
an overkill but otherwise it seems like a natural thing to be able
to process restore alongside package install/remove. The restore
operation is a cross between install and erase codepath-wise so touches
some funny places, but FA_TOUCH does just the thing, and now all the
regular disablers like --nocontext and --nocaps …
=> Reimplement --restore as a transaction element, obsolete --setperms & co

rpmio/rpmpgp.c
Also fix a memory leak in an error path.
=> Check that the CRC length is correct

rpmio/rpmmalloc.c, rpmio/rpmutil.h, system.h
rreallocn() is like realloc() but with multiplication protection.
Inspired by glibc's reallocarray() but I dislike that name.
While at it, add xmallocn() as a shortcut to rreallocn(NULL, ...) case.
Based on initial patch by Demi Marie Obenour.
=> Add rreallocn() to librpmio public API

rpmio/rpmpgp.c
If a key ID cannot be obtained, the key is useless.  This also ensures
that pgpPrtKey only needs to handle input that getKeyID has already
validated.
=> Bail out if a key ID cannot be obtained

lib/rpmfi.c, lib/rpmfi.h
The directory index must only be changed in sync with file iteration,
otherwise you get garbage out. The NOTYET'ed rpmfiDI() seems to suggest an
idea to have a separate mode of directory-only iteration in which context
rpmfiSetDX() would've perhaps made sense, but as it is this is plain
dangerous. Thankfully these APIs so broken that there can be no
legitimate users, so we can just turn them into a no-op until we have
to bump the soname next time.
The things we still have lurking in the codebase...
=> Disarm 21 year old landmine in the rpmfi API

lib/rpmfi.c, lib/rpmfi.h
Up to now, rpmfiSetFX() has returned the previous file index on success,
and -1 on error. Which seems okay on the outset, but on a just
initialized iterator the file index is at -1 which means the returned
-1 sometimes indicates an error and sometimes success. This is so broken
that none of the callers even try to use it (grep for it). Which is
lucky in the sense that it means we can change it.
Simply return the newly set index on success and -1 on error, it may
not be the greatest return code on earth but at least it's
non-ambiguous.
=> Make rpmfiSetFX() return code meaningful

build/build.c
Otherwise the user is not made aware that SOURCE_DATE_EPOCH is left
unset despite having set source_date_epoch_from_changelog.
=> build: warn if source_date_epoch_from_changelog set but changelog missing
