rpm-software-management/rpm

lib/header.c

If the i18ntable was smaller than the i18nstring entry an out of bounds
read could result.  This should not happen in a valid package, but even
if RPM rejected such packages during load, this situation could still
result as a result of usage of the RPM API.

Avoid reading out of bounds of the i18ntable

---

tests/Makefile.am

We are now using populate_testing as an entry point to manually calling
rpmtests (as described in the test/README.md). Right now this does not
rebuild the test suite itself. So while populate_testing itself does not
really care this makes it more user friendly for humans.

Make test suite a dependency of populate_testing

---

build/build.c
build/files.c
build/parsePrep.c
build/rpmbuild_internal.h
build/spec.c

This patch makes a couple of related changes:
- lets you set %{buildsubdir} as a global to expose it everywhere,
rather than just specific parts of %prep (%setup and %patch*)
- lets you choose what path is used independently of the unpack
options in %setup
- allows you to use a different %{buildsubdir} in different parts of
the .spec, for instance if you have multiple builds of the same code
with different compile options
Rebased #860 to $CURRENTYEAR
Resolves: #860

Make %{buildsubdir} usable without being a side effect of %setup

---

lib/fsm.c

Permit building with ./configure --with-cap=no

fsm.c: permit building without file capability support

---

build/build.c
build/parseSpec.c
build/rpmbuild.h
build/rpmbuild_internal.h
build/spec.c
docs/man/rpmbuild.8.md
docs/manual/buildprocess.md
docs/manual/spec.md
macros.in
rpmbuild.c
tests/Makefile.am
tests/data/SPECS/specstep.spec
tests/rpmbuild.at

Configuring the sources (eg ./configure, cmake and whatnot) is really a distinct step which is very unlike the actual build, in that the actual build steps are generally equal for all projects using a given build system, but configuration differs greatly once you go beyond the default paths and the like.
This is essentially a pre-requisite for implementing build system templating  in spec files.
Fixes: #1086
Couple of preceding commits to establish tests and fixup + comment the build-letter switch-case ordering which caught me too :sweat_smile:

Add separate build configuration (%conf) section to spec

---

docs/manual/tags.md
lib/tagexts.c
macros.in
tests/rpmdb.at

RPMTAG_ARCHSUFFIX from commit e6a6399cb4c87f049bb75b8da83f5759522bcc58
assumes all headers have RPMTAG_ARCH, but a notable exception is gpg-pubkey
headers in rpmdb, causing segfaults on `rpm -qa` on normal systems.
Special case conditionals in queryformats get ugly and error-prone real
fast, which is why we have all the NEVRA formatter extensions. Avoid
adding yet more of those tags by handling the dot formatting in
ARCHSUFFIX instead - the "suffix" in the name seems to imply this
anyway.
Also add tests to cover the common -qa cases.

Handle missing RPMTAG_ARCH in RPMTAG_ARCHSUFFIX

---

lib/rpmscript.c

Commit cb6aa82dbc10d554f8d234e934ae7c77e39a3ce2 unblocked all signals
from scriptlets, but turns out this is too much: SIGINT, SIGTSTP and
SIGQUIT sent from the terminal are passed to the process group, and
with unblocked signals end up killing our scriptlets while rpm itself
continues. -ENOSENSE.
Stopping (and continuing) is okay though so we don't block that.

Fix regression on ctrl-c during transaction killing scriptlets

---

lib/fprint.c
lib/misc.h
lib/query.c
lib/rpmchecksig.c
lib/rpmdb.c
lib/rpminstall.c
lib/rpmrc.c
lib/rpmscript.c
lib/transaction.c
rpmio/rpmsq.h

Details in commit messages, but in short, this drops the dreaded "block signals on rpmdb on" behavior that every librpm user comes to loathe. As a bonus, it also improves thread-safety by eliminating global structures.
This is a pretty drastic change to a very long-standing behavior so some fallout would not be unexpected, despite being a positive change.

Drop BDB era handholding on signals

---

lib/rpmchecksig.c
macros.in

This is insecure in so many ways I'm not going to bother trying to list
them all. It's an undocumented "feature" left over from more innocent
times, time to give it the axe.

Drop support for undocumented keyid based import over the net

---

lib/fsm.c

Commit 0e3024ca3e7450104e70ec8d213cf223e71f7c02 introduced a leak on
directory file descriptors from hardlinked sets, preventing some large
packages with many hardlinks from installing at all.
fsmMkfile() needs to close the firstdir fd when done with it because
that's the only place that knows when it's safe to do so. However, there
could be non-hardlink entries left in the same directory, so we must not
close *that* descriptor. Dup the firstdir descriptor so we're free to
close it without worrying about the other state.
Fixes: #1947

Fix file descriptor leak regression on install (#1947)

---

lib/formats.c
lib/misc.h
lib/verify.c

This improves performance of rpm -V --nofiledigests by ~2%
by avoiding an extra parameter and a sprintf call.

Small speedup on rpm -V

---

rpmio/digest.h
rpmio/rpmpgp.c

According to RFC 4880 §5.2.3.4 the signature creation time MUST be a
hashed subpacket.  Enforce this requirement in RPM.  Also set the saved
flags to `PGPDIG_SAVED_TIME | PGPDIG_SAVED_ID` for v3 signatures.

Require creation time to be unique and hashed

---

rpmio/rpmpgp.c

Such data is probably an attempt to exploit RPM, not do anything useful.
This avoids a whole class of silly integer overflow problems.
Signatures in packages are already limited to less than 64MiB by the
maximum size of the signature header, and this is already a sufficient
limitation.

Reject OpenPGP data over 1MiB

---

docs/manual/queryformat.md

The example command in the "Query Expressions" section fails because of
the backslash added in a9678c2dc (Insert space between the "{" and "%",
2021-05-06):
$ # rpm -qa --queryformat "%-30{NAME} %|PREINPROG?{ %{PREINPROG\}}:{no}|\n"
error: incorrect format: unknown tag: "PREINPROG\"
...
While this is relatively easy to spot and fix, it is better to avoid
non-working examples in the documentation.
Fortunately, there is no need to escape the closing `}}` as there is no
opening `{{` tag.  The dependency_generators and macros pages both
contain un-escaped `}}` strings which are displayed correctly.
Add a space to the else condition as well, to align the output.

docs/queryformat: fix query expressions example

---

CONTRIBUTING.md

It was incorrectly listed as git send-mail.
(I hope these last three PRs don’t count as a flood, given that 2 are trivial)

Fix name of git send-email command

---

tests/rpmsigdig.at

- Some versions of gpg appear to default to using SHA512.  This
breaks test 273's assumption that gpg generates a SHA256 hash.
Configure gpg to use SHA256.
- Fixes #1969.

Force gpg to use SHA256 when generating signatures.

---

tests/Makefile.am
tests/rpmpgpcheck.c
tests/rpmtests.at

They didn’t run due to a testsuite bug.

Make the OpenPGP parser tests actually run

---

rpmio/digest_openssl.c

This fixes a double-free bug in the OpenSSL backend.  This bug is not considered exploitable as it cannot be reliably triggered by an attacker.  It also deletes a bunch of cruft.

Improve the OpenSSL crypto backend

---

lib/rpmts.c
lib/rpmts_internal.h
tests/rpmsigdig.at

The fs keyring doesn't of course need the header to be created, but going through the same motions ensures consistent results, ie the key goes throught the same validation steps and we also get a "descriptive" file name for free (descriptive in that it matches the rpmdb NVR)
The first commit just paves way for this.

Support imports to fs keyring too

---

lib/rpmfi.c

It’s undefined behavior, even if the length is 0.

Avoid calling memcpy() on NULL

---

lib/rpmfi.c

headerGet() returning 0 is an error condition.

Fix inverted logic in base2bin()

---

include/rpm/rpmpgp.h
lib/formats.c
lib/rpmts.c
lib/rpmvs.c
rpmio/digest.h
rpmio/rpmkeyring.c
rpmio/rpmpgp.c

- Add accessor functions pgpDigParamsSignID, pgpDigParamsUserID,
pgpDigParamsVersion, pgpDigParamsTime, pgpDigParamsHashPrefix.
- Move the definition of `pgpDigParams_s` from `rpmio/digest.h` to
`rpmio/rpmpgp.c`.
- Change code to use the accessor functions.
- Fixes #1979.

Make pgpDigParams opaque

---

Makefile.am
build/parsePrep.c
macros.in
po/POTFILES.in
rpmio/macro.c
tests/rpmbuild.at
tests/rpmmacro.at
tools/rpmuncompress.c

See commit messages for details, but in brief this adds a new `rpmuncompress` tool which knows how to uncompress and extract what `%setup` and `%patch` can handle from the command line.
This makes it easier for packagers to extract multiple archives rather than wrestle with `%setup` for no good reason, plus it eliminates a silly dependency to sources and patches from the spec parsing step. Those are needed for building, not parsing.

Move source/patch uncompress logic from spec parse to build time

---

include/rpm/rpmds.h
include/rpm/rpmfi.h
include/rpm/rpmkeyring.h
include/rpm/rpmpgp.h
lib/psm.c
python/rpmds-py.c

This stuff is already mostly rendered harmless but we should make callers aware that it'll actually be going away in the next cycle.

Add missing deprecation warnings to various APIs

---

include/rpm/rpmsq.h
python/header-py.c
python/rpmds-py.c
python/rpmfi-py.c
python/rpmmodule.c
python/rpmts-py.c
rpmio/rpmsq.c

We have all manner of old cruft laying around that we want to remove, but technically we need to deprecate it first...

Add missing deprecation/obsoletion warnings to rpm 4.18 

---

macros.in

%__gpg_sign_cmd needs to be able to cope with strange characters in e.g.
%_gpg_name.  Use the builtin shescape macro to make this
straightforward.  Also rip out the old (and commented-out)
%__gpg_verify_cmd.

Properly escape %__gpg_sign_cmd

---

rpmio/rpmpgp_internal.c

A key ID subpacket is not a key usage flags subpacket and must not be
interpreted as such.  This caused RPM to wrongly reject a signature that
had both key ID and key usage flags subpackets in the hashed section.
@pmatilai I believe this fixes a regression in 4.18 alpha.

Avoid parsing key usage flags from hashed key ID subpackets

---

build/parsePrep.c

With RPM 4.18 non-quiet setup (`%setup` without `-q` or `%autosetup -v`) fails with:
+ /usr/lib/rpm/rpmuncompress -x -v/builddir/build/SOURCES/jquery-3.6.0.tar.gz
rpmuncompress: -v/builddir/build/SOURCES/jquery-3.6.0.tar.gz: unknown option
See https://bugzilla.redhat.com/show_bug.cgi?id=2079127

Fix a typo in doUntar that breaks verbose uncompression

---

rpmbuild.c
tests/rpmbuild.at

Successful rpmbuild -br needs to produce an src.rpm, this was untested
in the testsuite and commit ad8b9bd2ca93cf4319680f056bb40bfc24661991
missed this twist in the logic. Fixing is an obvious one-liner now,
add a test to ensure it doesn't happen again.

Fix multiple regressions related to dynamic buildrequires (RhBug:2078744)

---

build/parsePrep.c
build/parseSpec.c
build/rpmbuild_internal.h
tests/rpmspec.at

Handling %setup and %patch pseudo-macros in %prep is, ahem, special.
Which is why they don't appear expanded in --parse output despite
getting expanded at actual build-time. Add a flag to spec parsing
machinery to allow handling spec->parsed locally where needed, and
do so for %prep.
This is slightly ugly, but the alternatives are far more complicated
and still wont get rid of the ugliness as long as %patchN syntax
preprocessing is needed.
Fixes: #2048

Fix %setup and %patch not getting expanded in rpmspec --parse output

---

rpm.pc.in
rpmio/Makefile.am
rpmio/rpmpgp_sequoia.c
tests/Makefile.am

When rpm is configured to use Sequoia for the OpenPGP implementation
('configure --crypto=sequoia'), librpmio is linked against
librpm_sequoia.
librpm_sequoia can't directly implement the OpenPGP API, because
librpmio won't reexport librpm_sequoia's symbols, and we don't want
a program linking against librpmio to explicitly link against
(i.e., need a DT_NEEDED entry for) librpm_sequoia.
We can circumvent this problem by having librpm_sequoia provide
identical functions under different names, and then having librpmio
provide forwarders.  That's what this commit does: a Sequoia-specific
file forwards pgpFoo to _pgpFoo.  It's a bit ugly, but it is better
than a brittle, non-portable hack.
Fixes #2051.

Don't require a user of librpmio to link to librpm_sequoia

---

include/rpm/rpmpgp.h
lib/rpmts.c
rpmio/rpmpgp_internal.c

When importing an OpenPGP certificate, lint the certificate to show
the user possible issues.  Fail if the certificate is completely
unusable.  Using the Sequoia backend, this yields, for instance:
$ ./rpmkeys --import tests/data/keys/alice-revoked-subkey.asc
Certificate B3A771BFEB04E625:
Subkey 1F71177215217EE0 was revoked: Key material has been compromised, it was the maid
Certificate does not have any usable signing keys
Fixes #1974.

Before importing an OpenPGP certificate, lint it

---

docs/manual/tsort.md
lib/backend/sqlite.c

News about rpm 4.0.1 ordering algorithm changes are getting a bit
long in the tooth. Rewrite the whole doc to make it reflect modern rpm
behavior.

Rewrite ordering documentation

---

build/build.c
docs/man/rpmbuild.8.md
rpmbuild.c
tests/rpmbuild.at

Traditionally rpmbuild has only cleaned up the build directory on
--rebuild mode, but by default leaving tonnes of digital waste behind in
the far more common -bb mode. Default to cleaning up build directory
in addition to buildroot on successfull binary package creation,
with the exception of short-circuit'ed builds.

Remove build tree automatically on successfull binary package creation

---

scripts/check-rpaths-worker

Recent binutils can do debug section lookups over the internet, but this
is something we never want during rpmbuild (everything else aside, we're
just building the thing so there wont be anything on the net anyhow).
Disable the lookups by setting DEBUGINFOD_URLS to empty rather than
using the specific option as this is compatible with any old version of
readelf.

Prevent readelf internet access during rpaths checking (RhBug:2079600)

---

rpmio/expression.c
tests/rpmmacro.at

We use an empty string when discarding a value due to short circuiting, but
an empty string is not allowed for versions. So use "0" in that case.
Fixes: #1883

Fix short circuiting of version strings in expressions

---

build/files.c
docs/manual/spec.md
include/rpm/rpmfileutil.h
lib/manifest.c
lib/rpmgi.c
lib/rpminstall.c
rpmio/rpmglob.c
tests/Makefile.am
tests/data/SPECS/globesctest.spec
tests/rpmbuild.at

Enable the use of backslash quotation in the `%files` section of a spec file, just like in a typical shell, for example:
```
%install
touch "%{buildroot}/file*"
touch "%{buildroot}/file%%"
touch "%{buildroot}/file[with spaces]"
%files
/file\*
/file%%
"/file\[with spaces\]"
```
This PR builds upon the recent commit 66fa46c006bae0f28d93238b8f7f1c923645eee5 which replaced our flawed `glob(3)` implementation with the one from GNU libc.
Another PR is in the works which will change the semantics of double quotes to make the following work:
```
"/file[with spaces]"
```
Fixes: #1749

Add shell-like escape support to %files

---

tools/rpmuncompress.c

Fix unterminated macros being called when rpmuncompress
tries to expand an lrzip, 7zip or zstd compressed file

Fix unterminated macros in rpmuncompress

---

macros.in

Commit 3a6b1d8fbf846d3f1b139d343fdfddebe99ae42b assumed "master" as the
default git branch to track, however the name can be changed globally,
so make it explicit.
Given the choice now, go with "main" as the general trend, e.g:
https://fedoraproject.org/wiki/Changes/GitRepos-master-to-main

Use explicit default branch in %autosetup -S git

---

scripts/rpm2cpio.sh

Processing binary data in shell is very fragile. In this case the code breaks when encountering newline characters (\n) as part of the header size which is a binary integer.
Reported as https://bugzilla.redhat.com/show_bug.cgi?id=1983015

Make rpm2cpio.sh more robust

---

macros.in
tests/Makefile.am
tests/data/SPECS/hello-sources.spec
tests/rpmbuild.at

by enclosing them in single quotes (').
Replace sigle quotes within with '\'' as needed for sh
Resolves: #1445

Properly quote %sources and %patches

---

scripts/rpm2cpio.sh

As we look at the first 4 bytes anyway there is no reason to read more.
Reading more also hits a bug in bash on aarch64 (rhbz#2115206).

rpm2cpio.sh: only read needed bytes of file magic

---

build/files.c
docs/manual/spec.md
lib/manifest.c
rpmio/rpmglob.c

Clean up some old cruft, update the docs and prepare ground for the following PR.

Glob code refactoring

---

rpmio/rpmlua.c

This is a fix for small issue I encounter while was playing with lua in rpm spec:
```
➜  rpm --eval "%{lua:rpm.interactive()}"
RPM Interactive Lua 5.4 Interpreter
> print(rpm.vercmp('1', '1'))
0
> print(rpm.vercmp('', '1'))         
[string "<lua>"]:1: bad argument #1 to 'vercmp' (invalid version )
> print(rpm.vercmp('1', '')) 
> 
```
If first argument is wrong in `rpm.vercmp()` - meaningful error message as expected
if second argument is wrong - nothing happens and `nil` returned

Fix rpm lua rpm_vercmp error message if second argument is broken

---

configure.ac

https://github.com/rpm-software-management/rpm/commit/1cdb72ae48b7ba689c5c79118f4f0c1b4ffe6b7c
introduced a change where triplets that rpm doesn't know about
are rejected, which in turn causes a regression for users like
Yocto that explicitly use them.
In particular, x32 is a 64 bit x86 ABI with 32 bit pointers and
is supported via settings in custom /etc/rpmrc:
```
arch_compat: qemux86_64: all any noarch x86_64_x32 qemux86_65
```
----
Note from Alex:
this was previously submitted here:
https://github.com/rpm-software-management/rpm/pull/2143
The pull request was closed with reverting the commit that introduced the problem in 4.17 branch, but this does not solve the issue in 4.18 or in master. This new pull request is made so that we can hopefully find a solution that satisfies everyone, …

configure.ac: add linux-gnux32 variant to triplet handling

---

lib/psm.c
tests/rpmscript.at

Packages need to be able to differentiate between install and upgrade scenarios, seems commit ab069ec876639d46d12dd76dad54fd8fb762e43d with half the lights out...
As %posttrans happens after all the excitement, with the erasure elements already executed, so the installed package count cannot be used to differentiate between install and upgrade. So we need to find it out the hard way: see if there's an erasure element that depends on this package.

Fix %posttrans argument on upgrade

---

docs/manual/macros.md
rpmio/macro.c
tests/data/SPECS/configtest.spec
tests/data/SPECS/replacetest.spec
tests/rpmconfig.at
tests/rpmconfig2.at
tests/rpmmacro.at

Despite all the Lua magic we already do, it's annoyingly often the case that shelling out is easier (or at least shorter) than doing the same in Lua (substrings, length etc)
Add shorthand macros %gsub, %len, %lower, %rep, %reverse, %sub and %upper which simply wrap the corresponding Lua string.* functions for convenience.

Add shorthand macros for some conventient Lua string operations

---

build/files.c
docs/manual/spec.md
include/rpm/rpmfileutil.h
lib/manifest.c
lib/rpmgi.c
lib/rpminstall.c
rpmio/rpmglob.c
tests/Makefile.am
tests/data/SPECS/filemiss.spec
tests/data/SPECS/globesctest.spec
tests/rpmbuild.at
tests/rpmi.at
tests/rpmquery.at
tools/rpmgraph.c

In the `%files` section, we currently try to match globs literally if they don't expand to any existing files. This doesn't include special (`%doc` and `%license`) files so fix that. To make this behavior consistent everywhere, also do the same kind of fallback on the CLI when reading package names.
As a side effect, error reporting for globs is now unified with that for non-glob files as we pass both through the same IO routines.

Unify glob fallback behavior

---

build/pack.c

BZ2 compression type is no longer recognized during package build when used in %_binary_payload or %_source_payload.  This is caused by a typo that got in as part of commit https://github.com/rpm-software-management/rpm/commit/48d0fa954ca1629ffb0092b9c00555570241d6a0.

Fix unrecognized bzlib regression in pack.c

---

build/files.c
docs/manual/spec.md
include/rpm/rpmfileutil.h
rpmio/rpmfileutil.c
tests/Makefile.am
tests/data/SPECS/badescape.spec
tests/data/SPECS/badquote.spec
tests/data/SPECS/globesctest.spec
tests/rpmbuild.at

Treat globs in a quoted filename as literal (not just spaces). This makes the behavior consistent with the typical shell quotation and also makes the escaping of a large file list easier to automate.
This makes the following work as expected:
```
%files
"/some/path[with spaces and square brackets]"
```
That's equivalent to:
```
%files
/some/path\[with\ spaces\ and\ square\ brackets\]
```
Only double quotes are supported for now. Adding single quotes as an alternative to mix & match isn't difficult, but would just make things needlessly more complicated to document and review.
This is the last PR in the long-running series of glob revamps that all started with #1749, which this PR, if merged, also concludes. :partying_face:

Add proper quotation support to %files

---

lib/depends.c
lib/psm.c
lib/rpmdb.c
lib/rpmts_internal.h
lib/transaction.c
tests/data/SPECS/versiontest.spec
tests/rpmi.at

A missing epoch is returned as NULL from rpmteE(), but the rpmdb matching code can't handle NULL in any meaningful way currently. Arguably it should, but that's a bigger topic...
Specifically convert a missing epoch to a "0" which matches the behavior in mireSkip() to handle, adjust testcases as appropriate. 
Add a whole bunch of epoch related tests, and refactor related copy-paste code to a helper function while at it.

Handle downgrade within V-R when epoch goes away (RhBug:1845069)

---

CMakeLists.txt
ci/Dockerfile
tests/CMakeLists.txt
tests/package.m4.in

Apparently the "testsuite voodoo" comment in tests/Makefile.am has scared everybody (myself included) from even looking at how this all works. Turns out, it's not so magic afterall, and better yet is not at all tightly integrated with the rest of the surrounding autotools works. There are paths to be communicated and translated and for some items different mechanisms are more sensible, but that's to be expected.
While having a dependency to autom4te (from autoconf package) in a cmake build is not ideal, this is hardly an end of the world either as long as it doesn't require the entire build to be autoconf based. Means we don't need to port it to something else just now. Phew!

Implement test-suite execution in cmake

---

build/parsePrep.c

These look like they were different blocks needed at different places at some point. But I fail to see why this split is still necessary.

Remove duplicated code in doSetupMacro

---

docs/manual/macros.md

This started life with the realization that the RPM website Markdown formatter was combining double dashes into an en dash, in the docs. (See, for example, near the end of the second paragraph in the section "[Defining a Macro](https://rpm-software-management.github.io/rpm/manual/macros.html)"):
> “–” can be used to separate options from arguments.
It kind of grew from there. The primary commit is the one to add backtick fencing to more literals in the body text, in an attempt to combat the issue mentioned above. It _should_ be successful, leading to a clearer statement:
> `--` can be used to separate options from arguments.
The others are just cleanup, and I can drop any on request. (I can drop the fencing one, too, of course.)

Docs: Some formatting fixes for macros.md

---

build/CMakeLists.txt
lib/CMakeLists.txt
rpmio/CMakeLists.txt

We should really do this for all our dependencies, but notably Debian and derivates have multiple versions of Lua available, each in different includedir, and build fails without this.
Fixes: #2258

Remember to set include directories from pkgconfig for Lua

---

macros.in

The build and source directories are plain old directories, never any sort of URLs. Drop the misleading and obfuscating u2p macro uses from the build environment setting.
As of this commit, u2p is unused within rpm.

Eliminate remaining %{u2p:...} uses

---

build/build.c
build/parseSpec.c
macros.in

See commit messages for details, this stuff needs to be calculated at the time of build, not time of (spec) parse and restored when done. Besides making more sense, it removes stuff out of the way of #1485.

Improve CPU/thread calculations a bit

---

tests/rpmsigdig.at

The `rpmkeys type confusion` test was added in ec13083f46a1e to check that the internal OpenPGP parser rejects a certificate with an invalid component.  The Sequoia backend happily accepts the certificate and ignores the invalid component, which causes the test to fail.  Mark the test as specific to the internal OpenPGP backend.
Fixes #2272.

Fix rpmkeys type confusion test.

---

rpmbuild.c
tests/data/SPECS/specstep.spec
tests/rpmbuild.at

Some source packages assume that BuildRequires are installed before %prep is executed.  For example, `openssh` BuildRequires `automake` and runs `autoreconf` in %prep.
Prior to 11c56d5 `rpmbuild -bp` checked BuildRequires and printed a helpful error message if there were any missing dependencies.  Since that commit, `rpmbuild -bp` skips the BuildRequires check, which can lead to misleading errors in %prep.
This commit restores the BuildRequires check in `rpmbuild -bp`.

Fix regression: -bp should check BuildRequires

---

docs/man/CMakeLists.txt

Pass -s/--standalone to pandoc as it's needed in order for the man pages to render properly in man(1), we also used this option pre-cmake.
Fixes: #2283

Fix missing headers/footers in generated man pages

---

docs/man/rpm2archive.8.md
rpm2archive.c

If stdout is not a terminal, output the archive(s) to it, instead of creating file(s) on disk.  This makes rpm2archive consistent with rpm2cpio. This makes rpm2archive consistent with rpm2cpio.
Based on a patch from yangchenguang <yangchenguang@uniontech.com>.

Allow piping from rpm2archive

---

sign/rpmgensig.c

https://bugzilla.redhat.com/show_bug.cgi?id=2141686 revealed that much of the rpm-ecosystem is still using the obsolete v3 OpenPGP signature format, I think largely due to workarounds for legacy rpm versions (from around the turn of the millennium) that have just been forgotten in place. Lets at least issue a wake-up warning when that happens.
Unfortunately this is can't really be tested as current GnuPG versions just ignore any --force-v3-sigs arguments.
Fixes: #2286

Issue a warning when signing created an OpenPGP v3 signature

---

CMakeLists.txt
docs/man/CMakeLists.txt
docs/man/index.md
docs/man/rpmsort.8.md
tools/rpmsort.c

rpm-sort(8) is intended for use in shell scripts.  sort(1) is not RPM versioning-aware, and attempting to work around that is fraught. Instead, provide a wrapper around rpmvercmp() using qsort().
Fedora's grub2 has carried a version of this since 2015, and a more complex version was also part of the grubby project (provided at /usr/libexec/grubby/rpm-sort) since 2018.  This version has been simplified and adapted to the RPM project.
Also-authored-by: Peter Jones <pjones@redhat.com>
Signed-off-by: Peter Jones <pjones@redhat.com>
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
[Code is ready for inclusion.
While rpmdevtools does provide a rpmdev-vercmp utility, it is limited to comparing two versions at once only, meaning shell scripts would need to reimplement the sorting logic.  It's …

Add rpm-sort utility for sorting RPM versions

---

ci/Dockerfile

After being stuck on an EOL Fedora for so long, it's nice to be on the leading edge for a change.

Bump CI to Fedora 37

---

CMakeLists.txt
INSTALL
ci/Dockerfile

Defaulting to a deprecated build option tends to looks a bit strange. Make Sequoia the default crypto option, update docs and add the dependency to CI environment.
Fixes: #2065

Default to Sequoia crypto as per roadmap

---

scripts/brp-remove-la-files

This should fix https://github.com/rpm-software-management/rpm/issues/2332

brp-remove-la-files: use -0 to work on macOS

---

configure.ac
python/Makefile.am
python/rpm.egg-info.in

To compensate for the loss of egg-info from the python distutils build, create one ourselves.
This is effectively a backport of e31fb5b75898bfa09180dba02475c6d01764d94f which dismissed the need for an automake version, but unfortunately Python 3.12 and automake-based rpm versions do co-exist in the same time-space continuum and we'll have to deal with this in rpm 4.18 as well.
As to why not just use distutils from python-setuptools: that variant turns the egg-info into a directory, which in rpm is a one-way street. And we don't need that multi megabyte Python library to fill in these couple of values, really.

Generate Python egg-info from automake builds (4.18.x)

---

rpm2archive.c

Fix silent wait when missing input RPM package
Signed-off-by: yangchenguang <yangchenguang@uniontech.com>

Fix silent wait when missing input RPM package

---

build/files.c
tests/data/SPECS/globtest.spec
tests/rpmbuild.at

Somehow this fell through the cracks when refactoring processBinaryFile() in commit f062d5744c3ee338daaeb8e11b1fc20f9e44dee3, it basically disabled the use of the %dev directive altogether, oops.
Without rpmIsGlob() (which was also yanked in the recent cleanups), we can't easily determine whether a string is a glob pattern, so don't overcomplicate this and just remove the error message, and always consider any metachars in a %dev line literal.
Since %dev is meant for device *creation* [1] at install time and we never lstat() those filenames in addFile(), any use of globs within such a filename can only possibly be meant literally, period.
That doesn't mean we shouldn't actually document %dev itself in our own docs but let's do that separately.
Thanks Panu for discovering this regression …

Unbreak %dev directives in %files

---

lib/fsm.c
tests/atlocal.in
tests/data/SPECS/dev.spec
tests/data/SPECS/fifo.spec
tests/populate
tests/rpmi.at

While it's possible to open special files, they are, well, special and have "side-effects" also known as, ahem, semantics. Opening a device file in Unix means accessing that *device*, and FIFOs have their own semantics.  In other words, for rpm's purposes, we should never EVER open these files as a part of the install / permission setting etc. Fix this major brainfart in 25a435e90844ea98fe5eb7bef22c1aecf3a9c033.
OTOH this forces us back to the less secure path based operations for these files, which is what we were trying to avoid in the first place. There always was a tiny race between create + open for these (because there's no atomic way to create + open anything but regular files) but this opens up the window quite a bit.
Nobody should be placing device nodes in user-owned directories …

Fix install of block and character special files (#2195, #2275)

---

macros.in
scripts/find-lang.sh
tests/data/SPECS/find-lang-test.spec
tests/populate
tests/rpmbuild.at

Use the new dynamic spec feature to create language sub packages.
The is more of a RFC as there are a few things that need more polishing. The code for getting the language description is a bit ad-hoc and may need to switch to another entry in `locale` data. Suggestions welcome.
The package declaration should probably also move into a macro. Probably to the point where the spec parts are only one macro with the right parameters

Add --generate-subpackages to find_lang.sh

---

build/parsePrep.c
docs/manual/autosetup.md
docs/manual/spec.md
tests/data/SPECS/hello-g3.spec
tests/data/SPECS/hello-r2.spec
tests/data/SPECS/hello.spec
tests/data/SPECS/hello2.spec
tests/data/SPECS/hello2cp.spec
tests/data/SPECS/hello2ln.spec
tests/rpmbuild.at

Document %setup and %patch in the reference manual, even if briefly.
Convert our own %patch uses in the testsuite to modern syntaxes and officially deprecate the stupid %patchN syntax so we may some day actually get rid of it.

Document %setup and %patch, officially deprecating %patchN

---

tests/CMakeLists.txt

Recently there have been a fair amount of random failures in the CI, due to apparent ordering errors / lack of dependencies that have been hard to reproduce locally. The key is probably CI running "make check" right away, which then proceeds on all the relevant targets in parallel. And nowhere at all we're telling it that the tests need the entire project to be already built. So apparently the "make install" in tests/populate often ends up building a significant part of the project and ... that two competing makes in the tree ever actually manage to complete at all is a small miracle.
There doesn't seem to be a way to add a dependency on the ALL target in cmake, so have
populate_testing target depend on top-level cli utils to enforce at least "mostly sane" situation when running "make …

Try telling cmake that the project needs to be built before testing

---

rpmio/macro.c
tests/rpmmacro.at

This is the same issue as commit 1767bc4fd82bfacee622e698f9f0ae42c02126fa was with Lua, and so the same fix works: restore the nesting level from the macro context when re-entering macro engine from %[] expression. Analysis and suggested fix by Michael Schroeder, reproducer from Miro Hrončok.
Add tests for both %[] and %{expr:...}, although the latter isn't affected because the expression is macro-expanded beforehand.
Fixes: #2354

Fix macro scoping level on re-entry from %[] expresssion (#2354)

---

build/parsePrep.c

Instead of treating `%patch` with no options and errors the same as `%patch 0`, just raise an error. There will be folks who have missed the warning-only phase, but we don't want to wait another ten years to finally rid ourselves of these legacy quirks.
Related: #2205

Turn `%patch` without arguments and options into an error

---

macros.in

New macro ___build_package_notes_env contains environment variables that package-notes depends on. This allows easier mocking of rpm build environment and isolated execution of check phase of rpm packages possible.
Hi,
in many tests using upstream test suite is used approach that builds sources and
tests with optflags as used in Fedora builds. This proved to be problematic since
package-notes started to depend on environment variables defined through rpm
macros. There is a workaround that can solve this but since `___build_pre` macro
contains `cd` command at the end, evaluation of it in tests must be followed by
`cd` back to the original directory. This change allows us to get rid of this following
`cd` and has no effect on the current way of building.
Please see also this …

Split ___build_pre macro to make mocking rpm build environment easier

---

rpmio/rgetopt.c

[POSIX defines optarg only for options with arguments](https://pubs.opengroup.org/onlinepubs/000095399/functions/getopt.html) and callback() is expecting optarg to be NULL for options without arguments, however, at least on musl optarg will carry a pointer to the argument of the previous option with argument.  This commit makes the behaviour deterministic and expected.

support for POSIX getopt() behaviour

---

build/files.c
include/rpm/rpmtag.h

Unlike #2390, this doesn't change the bit-level value so it's backwards compatible, this is just for eliminating compiler level ambiguity.

Eliminate RPMTAG_NOT_FOUND signedness mismatch, take II

---

lib/header.c
lib/header_internal.h
lib/package.c
lib/query.c

*Fun* (for some idea of fun) refactoring of header internals to replace signed integers with unsigned ones in various places. This isn't supposed to change behavior (except maybe catch some errors we previously didn't) but with this type mess, you never know. So lotsa churn in small bisectable commits...
This is a significant chunk of #2385, but not complete.

Header internals type cleanup

---

docs/manual/spec.md

(sicne rpm >= 4.9) -> (since rpm >= 4.9)

Fix a typo

---

build/rpmfc.c
fileattrs/elf.attr
macros.in

Disable ELF dependency generation on kernel modules, there will not be any so it's waste of time. Prevent tools like `readelf` in scripts from doing network lookups during build.

Dependency generation sanity

---

build/parsePrep.c
build/rpmbuild_internal.h
build/spec.c
tests/data/SPECS/hello-patch.spec
tests/rpmbuild.at

Avoid polluting the build log with this warning repeated as many times as there are %patchN lines.  Once per build should be enough for the packager to notice (there's also a warning summary now).
Basically, make the warning context-independent, meaning that it doesn't matter which line caused it (so don't even print it), we just want to warn about such usage being present in the SPEC.
Suppressing duplicate log messages could be a useful feature on its own so we may eventually want to implement this in rpmlog() with something like a RPMLOG_NODUP flag (and perhaps print the number of suppressed messages in the summary, too) but until then, just keep it simple and use a static int.
Rather than adding another %patch to hello2-suid.spec which is also used elsewhere in the test suite, just …

Issue %patchN deprecation warning just once

---

lib/rpmrc.c

The GCC headers put bit_LZCNT into the list for CPUID 1 %ecx values, but that corresponds to VMX. LZCNT is actually advertised in CPUID 0x80000001 %ecx, which is also referred to as "ABM" by AMD and some other places.
This bug was partially inherited from GCC, which uses LZCNT wrongly and also has an ABM feature which maps to the same bit. I'll have to reach out to the GCC maintainers to clarify what's going on there. I hope we get some unified place for all this mess at some point...

The bit for LZCNT is in CPUID 0x80000001, not 1

---

build/rpmfc.c
sign/rpmgensig.c

Unfortunately, pressing Ctrl+C while `%check` is running gives false-positive result. I found what is happening using strace. Please review. I can make backport (the code has changed recently, so fix is slightly different)

Fix ignoring exit code of child scripts in case of EINTR

---

lib/rpmscript.c
rpmio/rpmlua.c

Commit 2d418ad3c11bcf0261d0022ac177d13284a8d5fb added a safety catch for runaway children from package scriptlets, but we have many other ways to run Lua scriptlets too, and runaway children are equally harmful in them all. Catch them all centrally by wrapping lua_pcall() instead.
Besides handling more cases, there are a couple of more subtle improvements here: rpmlog() in a child process is undefined behavior due to the locking it does, but also nonsensical - rpmlog() is more than fprintf() and any warnings/errors it collects end up in the wrong process. Check and log from the parent instead.
Finally, make it a warning instead of an error because we're not failing the scriptlet because of this, and make the message more generic as besides exec(), this can be avoided by waiting for the …

Catch runaway forked children from Lua scriptlets centrally

---

build/rpmfc.c

I noticed there are ~150K .html files in all libreoffice rpm files and the detection is significantly delaying package build. Thus, I introduce more exceptions for commonly used file formats.

add more libmagic exceptions for HTML, SVG and PNG

---

rpmio/rpmlua.c
tests/rpmmacro.at

When natively calling a parametric macro from Lua, with the arguments inside a table, we can't assume lua_tostring() always succeeds as it can fail eg on a table. Report the error instead of crashing in argvAdd(), and add a test as well.

Fix a segfault on a non-stringable argument to macro call from Lua

---

build/build.c
docs/manual/macros.md
macros.in
rpmio/macro.c
rpmio/rpmio.c
tests/rpmmacro.at

See commits for details, but short summary: add optional proc/thread argument to %{getncpus} macro which consider the available memory and address space, based on newly added tunables for tasksize. 
The goal here is to avoid build failures due to gross overallocation on constrained systems, and to allow packagers to easily adjust for gigantic builds.
Fixes: #804

Consider available memory and address space for parallel execution

---

include/rpm/rpmtag.h

Set to 0xffff0000 (or 4294901760), I was getting:
error: ISO C restricts enumerator values to range of 'int' (4294901760 is too large) [-Werror,-Wpedantic]
This happened not when building rpm itself, but when building rpminspect which links with librpm and uses rpm's headers.  The system in question was FreeBSD 13.1 which has clang 13.0.0.
It is a corner case, but I like testing things on non-Linux platforms as often as I can to find errors like this.
With this change, the rpm test suite passes for me.

Bring RPM_MASK_RETURN_TYPE in to the signed int range

---

CMakeLists.txt
build/CMakeLists.txt

This fixes a regression from automake where we also didn't use pkg-config for libmagic.
Fixes: #2246

Don't rely on pkg-config for libmagic just yet

---

plugins/CMakeLists.txt

which was accidentially dropped when converting to cmake
Use CMAKE_INSTALL_FULL_SYSCONFDIR as it expands to /etc instead of /usr/etc
Resolves: #2474

Install /etc/dbus-1/system.d/org.rpm.conf

---

CMakeLists.txt

cmake variables and the derived macros.
CMAKE_INSTALL_INFODIR and  CMAKE_INSTALL_MANDIR already include the datarootdir. So just prepending the prefix is sufficient.

Remove second share/ dir from infodir and mandir

---

CMakeLists.txt

HAVE_BZLIB_H was not set due to a typo leading to the bz2 support not being compiled in although the library was detected correctly.

Fix bzip2 detection

---

plugins/CMakeLists.txt

Another bit lost in the cmake transition: plugin linkage to librpm and librpmio. In rpm itself this doesn't really matter because the running process supplies the necessary symbols but it's a different story when eg a Python process uses dlopen()'ed bindings.

Fix undefined symbols from plugins in some circumstances

---

macros.in

Commit a213101bc3af65c860d045c65fb4e2ef7566a4c6 changed %_smp_build_ncpus into a parametric macro, but this breaks common usage via the Lua macros table as parametric macros are returned as closures rather than the expanded value.
This seems like a design flaw of the macros table, but as an immediate remedy for the breakage, add another layer of indirection to revert %_smp_build_ncpus back to a non-parametric macro.
Fixes %constrain_build macro in Fedora, which ironically is made obsolete by the change that (unintentionally) broke it.

Revert %_smp_build_ncpus change to a parametric macro (RhBug:2210347)

---

docs/manual/macros.md
rpmio/macro.c
tests/rpmmacro.at

Seems like a useful thing to have, and a bit crazy that we haven't had any reasonable mechanism for this before now.
Fixes: #2523

Add %{rpmversion} builtin macro for getting the running rpm version

---

lib/rpmdb.c

Back in 1997, commit be0b90359bcd8156385178eb9b570c0538c0333f added a sanity check for --rebuilddb operation, skipping headers which lack some basic tags. Name, version and release are real requirements for packages, but checking for buildtime is odd, and plain wrong. Yes, we expect that to be present in packages built by rpm, but that's not used for any processing and certainly is not required for a package to be installable. And if it can be installed then it can't be right to throw it away when rebuilding, leaving untrackable orphan files in the process.
It is also documented as informational and optional by LSB. While severely outdated, it is right on this account.
Fixes: #2527

Remove obscure check for package build time from --rebuilddb (#2527)

---

plugins/CMakeLists.txt

Hard code the prefix to /usr as this needs to match with dbus and not our own install prefix.
Resolves: #2474

Move dbus announce plugin config in /usr/share

---

lib/rpmrc.c

The code to autodetect x86 CPU model runs the cpuid instruction after setting up 1 in eax. This gives the processor signature back in eax which encodes the model number.
As per Intel Application Note 485 and AMD publication #25481, when deriving model, we should look at both the base model in eax[7:4] and the extended model in eax[19:16]. However current code is only looking at base model and this causes some newer CPUs like Icelake(Model 0x6a) to be detected wrongly as Pentium 3(Model 0x0a).
Note that this code is only exercised when rpm is built as 32-bit binary because all of this is within a `#if defined(__i386__)`.
Because of this misdetection on Icelake, `setarch x86_64 rpm --showrc` has `pentium3` as the `installed arch` instead of the expected `x86_64`. It doesn't have `x86_64` as …

rpmrc: Fix how x86 models are derived

---

rpmio/rpmlua.c
tests/populate
tests/rpmmacro.at

The error handling of these Lua functions is wrong in so many ways I wont list them all here, but eg. rpm.execute() tries to find an strerror() string for an exit code of a process, returns a waitpid() error with code 0 and string "success" and rpm.redirect2null() always returns a failure despite success and never any meaningful error code. The latter probably did the right thing when it was in lposix.c but the pushresult() and pusherror() versions in rpmlua.c are rather different.
To sort the mess, handle the actual error code checking at call site and the pushfoo() functions do just that: push the result on the stack and nothing else. Add some test-cases to go.
Fixes: #2528

Fix error handling of rpm.execute() and rpm.redirect2null()

---

build/parseSpec.c

per package even if we do multiple parse passes. This is a quick fix for the dynamic spec feature that executes the parsing code multiple times.
This needs to be sorted out properly to only do the necessary things (for the build scripts) here and postpone everything else after the secondary parses. But that requires larger changes.

Only add arch, os and platform, self-provides once

---

lib/rpmrc.c

Just CPUID is not enough and neither is just __builtin_cpu_supports,
so use both.
Fixes: https://github.com/rpm-software-management/rpm/issues/2463
@fweimer Anything else this could possibly be missing?

Use __builtin_cpu_supports in x86-64 CPU feature level detection

---

build/parseScript.c

The return value is stored in the "res" variable which is set to the return value of parseLines early in the function. Past that point, any "goto exit;" caused the function to return success. This was introduced by 52ce88851abb ("Port parseScript() to use parseLines(), no functional changes"). To fix it, reintroduce the nextPart variable.
CC @pmatilai as author of the commit introducing the regression.
Before this change, script sections with parse error caused an error message during built but then were just ignored and are missing in the binary package:
```
> cat test.spec
Name: pkg
Summary: Nothing to see here
Version: 0
Release: 0
License: WTFPL
%description
.
%pre -p <magic>
world.issues = 0;
%files
> rpmbuild -bb *.spec
error: line 12: unsupported internal script: <magic>
Processing …
```

Actually return an error in parseScript if parsing fails

---

docs/man/rpm.8.md
docs/manual/spec.md
lib/rpmchroot.c
lib/rpmug.c
lib/rpmug.h
macros.in
tests/rpmi.at

There's no telling what sort of caching getpwnam() and friends perform behind the scenes, and worse, there's no way to explicitly reset those caches. This can lead to chrooted operations using user/group data from the host, which is simply wrong.
Do our own parsing of /etc/passwd and /etc/group to fix. Besides the chroot matter, we then only ever lookup local system users and groups and not something from eg network name services. Technically we should track chroot status for each lookup and flush the cache if the state changed, but this is an internal API and rpm usages only ever call it from one side of the chroot for a given operation.
Fixes: #882

Make user/group info reliable operation across chroot

---

CMakeLists.txt
macros.in

systemd-sysusers location does not depend on rpm's idea of %_bindir, use cmake to discover it along with the other tools we use. To handle this, we the need to translate the dash into an underscore in the variable name.

Fix systemd-sysusers helper path discovery

---

CMakeLists.txt
INSTALL
macros.in

By default cmake uses $PATH for find_program() lookups, which seems reasonable and even obvious until you start seeing things like /usr/lib64/ccache/cc in the macros file.
Have cmake use a sanitized path (the usual bins) by default and allow augmenting via MYPATH environment variable again (another thing temporarily lost in the cmake transition). This gives us more reasonable output even with ccache installed while still allowing flexibility for more custom setups.
In the autoconf days configure would AS,CC, CPP, CXX, LD and whatnot from the auto* environment directly, but cmake has no direct counterpart for many of those and for the rest, are equally infected by ccache hacks as find_program() is. Handle all the tool lookups with the same logic and same lookup. Also take care of c++ <-> …

Sanitize the helper tool search path in cmake

---

CMakeLists.txt
config.h.in
macros.in
platform.in

This is always in /usr no matter what prefixes are used either in rpm or systemd as it is package installed system configuration.
Setting this hard coded to not require systemd as a build dependency. Otherwise the sysusers_dir or sysusersdir pkg-config variable could be used.
Borrowing the _root_prefix idea from systemd for /usr independent of _prefix

Set %_sysusersdir independent from our prefix

---

tests/mktree.native
tests/mktree.podman
tests/mktree.rootfs

This ensures no single test can (accidentally or intentionally) alter the shared tree and influence the subsequent tests.
This also makes us comply with the following OverlayFS requirement which could otherwise be violated when running parallel tests:
Changes to the underlying filesystems while part of a mounted
overlay filesystem are not allowed. If the underlying filesystem is
changed, the behavior of the overlay is undefined, though it will
not result in a crash or deadlock.
Contrary to what I thought in commit
cf8716f204f1eed196ca7ae905288261e0c88c3b,
to make this work, all we need is to mount a new tmpfs at /tmp in the snapshot, as that's where some of the processes (patch(1) in particular) need to write.
Update the comment in mktree.rootfs accordingly, too.

Mount the common tree snapshot as read-only

---

lib/rpmscript.c
tools/rpmuncompress.c

These two headers were missing, and would break with implicit function declarations disabled. I assume glibc and friends includes these through other headers.
This should fix the build on macOS.

Fix missing includes on macOS

---

INSTALL
installplatform

By default, rpm installs a series of default platforms based on the CPU architecture names in subdirectories called `/usr/lib/platform/<arch>-linux`.
This is enough for regular Linux distributions. However, some distributions may use more specific platform names that refer to particular computer systems, like SBCs or specific CPU tuning when compiling.
If the platform subdirectory does not exist in `/usr/lib/platform` then rpmbuild does not work.
Allow creating such custom platform subdirectory with feeding the necessary data using external variables: `RPM_CUSTOM_ARCH`, `RPM_CUSTOM_ISANAME`, `RPM_CUSTOM_ISABITS`, `RPM_CUSTOM_CANONARCH` and `RPM_CUSTOM_CANONCOLOR`
Fixes #2578

Allow setting platform macro settings externally

---

tests/mktree.fedora

We actually do need this library in the test tree, in case the build is configured with -DWITH_IMAEVM=ON which links librpmsign to it, it's not a plugin.  We already include libfsverity for the same reason.
This is a fixup for commit 4c41faf7a592a5bb484cf7d645cc247d850d776a.

Add back ima-evm-utils to mktree.fedora, oops

---

.github/workflows/linux.yml

This should've been part of the previous commit, just got forgotten.

Bump actions/checkout from v2 to latest (v3)

---

rpmpopt.in

This is the only dependency on awk in the runtime commandline part of rpm, which is bloating minimal container images a bit. We can rewrite that into a single sed statement. We love you anyway, awk.

Rewrite --last to use sed for formatting

---

CMakeLists.txt

Unroll the loop to make it more like autoconf era checks, add the necessary alternatives.
For more details see commit messages.
Fixes #2608

Fix cmake transition regression on 7zip utility discovery

---

tests/Dockerfile
tests/atlocal.in
tests/local.at
tests/mktree.fedora

Mostly quality of life fixes and improvements to `make env` and a few other small bug fixes.

Mktree tweaks, volume II

---

CMakeLists.txt
macros.in

Commit cececfb6851234aca3e8d102de1c192c6bdf3e67 introduced %_root_prefix macro but this unnecessarily breaks widespread use in scl-utils: https://bugzilla.redhat.com/show_bug.cgi?id=2233454
Just query the value from pkg-config if available and otherwise use hardcoded value pointing to /usr instead. We don't need an intermediate global macro for this.

Revert recent %_root_prefix macro addition (RhBug:2233454)

---

lib/rpmrc.c

You're about to fall into a deep dark hole, proceed at your own risk.
When building for a target architecture with no defined %optflags (such as noarch), one would think that %optflags would be empty. Not so in rpm, instead we get %optflags for the detected architecture, and there are packages which rely on this behavior. And in this particular dark corner, buildarchtranslate is not applied so one can get drastically different %optflags than you'd get without an explicit --target, on the same system. Which can break builds.
None of this makes any sense whatsoever, but lets at least try to be consistent about it. When we fall back to detected architecture %optflags, at least use the ones after buildarchtranslate to return consistent data within a host.
This supposedly fixes the case where …

Behave more consistently when target arch %optflags are not defined

---

CMakeLists.txt
build/CMakeLists.txt
cmake/rpm-config.cmake.in
lib/CMakeLists.txt
rpmio/CMakeLists.txt
sign/CMakeLists.txt

This is a fair amount of annoying voodoo boilerplate compared to what I would've expected, but the ability to just `find_package(rpm)` is very nice on the (API) user side.
Fixes: #2471

Export our libraries as a cmake find_package() config

---

plugins/dbus_announce.c
plugins/systemd_inhibit.c
tests/atlocal.in
tests/mktree.fedora

With the fancy new container-based test-suite, we can actually enable plugins in the test-suite :partying_face: 
The first commit is required for doing this, the second is merely for consistency.

Run test-suite with plugins enabled now that we can

---

tests/atlocal.in

With the new container based test-suite we no longer need these hacks. Leaving the mknod conditional in place though as that may still be restricted.

Always run tests without --nouser and --nogroup, now that we can

---

tests/Dockerfile

rpm-sequoia >= 1.4.0 has been in stable updates for a good while now.

Drop no longer needed pull from updates-testing for rpm-sequoia

---

build/rpmfc.c
docs/manual/dependency_generators.md
fileattrs/elf.attr
tools/elfdeps.c

The first commits are just refactoring preliminaries, the beef is in the second-last commit which adds a new opt-in generator mode where all the files are processed in one go per extracted dependency type instead of launching a new generator for every file separately. 
This is a several orders of magnitude faster for even cheap generators (such as the ELF generator which gets multifile support in the last commit), even more so for heavy interpreters like Python/Perl and friends.
The new mode is opt-in because it requires a small change to the generator itself: rpm keeps track of dependencies on per-file level, so in the multifile "protocol", the generator needs to output the filename it's processing prepended with `;` before outputing the generated dependencies.

Support generating dependencies for multiple files at once

---

fileattrs/CMakeLists.txt
fileattrs/rpm_lua.attr

Some packages in Fedora provide shared RPM lua code that's used by other packages.
It would be nice to have automatic Provides for this code like we have for rpm macros themselves.
Usecase:
Recently, forge.lua that's used by go-srpm-macros and fonts-srpm-macros moved out of redhat-rpm-config.
I would like to be able to add `Requires: rpm_lua(fedora.srpm.forge)` to those packages instead of having to rely on it being implicitly pulled in by redhat-rpm-config or adding conditional dependencies on forge-srpm-macros.

Add a Provides generator for rpm lua modules

---

lib/poptALL.c
lib/rpmchroot.c
tests/atlocal.in

While the chroot call itself works nicely for a regular user with this, user/group mapping does not and cannot be made to work, because that requires a fork and we cannot very well fork the process from deep down here.
Better to put the irrepairable thing out of its misery, users are far better of wrapping rpm with the unshare command instead.

Axe the experimental non-privileged chroot support from b4c832ca

---

lib/CMakeLists.txt

The COMMAND for tagtbl.C generation dumps the file in the top-level build directory whereas the OUTPUT is specified in the current (lib/) directory.  This leads to unnecessary relinking of all the libraries on each make invocation because OUTPUT is always missing.
Fix this by outputting the file in the current directory where OUTPUT can find it.
No functional change, just makes rebuilds quicker.

Fix tagtbl.C placement in build dir

---

tests/rpmpython.at

I dialed up my Python debug settings, and got complaints about unclosed files on stderr, whis caused tests to fail for me.
This properly closes all the files the Python tests `open`.

Python tests: Close open files

---

tests/CMakeLists.txt
tests/atlocal.in

It's fairly amusing how various aspects of integrating autotest seems easier with cmake than autoconf/automake.

Simplify communicating crypto backend to the test-suite

---

CMakeLists.txt
docs/CMakeLists.txt
tests/CMakeLists.txt

Mark all the program and library path details as advanced, they're not something you need to be acutely aware of when compiling rpm. This way -L[H] actually shows the "user configurable" parts.

Make 'cmake -L' output meaningful

---

tests/CMakeLists.txt

Running the test-suite obviously requires on having the project completely built first. The test-suite was relying on the cli tools in the top level directory for this, but now that we moved the tools elsewhere there are zero targets at the top-level. Oops.
Update the property get_property() path accordingly, this should've been in commit 1c98b67911e19a5f92c7fa4492aaa1000a06edad. Rename the variable and add commentary on why we're doing this the way we are, it's not entirely obvious.
Suggested-by: Michal Domonkos <mdomonko@redhat.com>

Fix build-order regression from 1c98b67911e19a5f92c7fa4492aaa1000a06edad

---

tests/data/SPECS/simple.spec
tests/data/debugplugin/CMakeLists.txt
tests/data/debugplugin/debug.c
tests/data/debugplugin/macros.transaction_debug
tests/rpmdevel.at

Add an externally built debug plugin which outputs something from each hook. This serves as a generic plugin functionality test, both from the POV of developing one externally and the actual functionality.

Add a "plugin development" testcase

---

tests/CMakeLists.txt
tests/mktree.fedora
tests/mktree.podman

Minute cosmetic changes, just something that I stumbled across while working on #2691. Some of this preparatory work for #2691 though.

Minor test-suite tweaks/fixes, volume VI

---

CMakeLists.txt

Fixes `cmake --install` failing on these files as the working directory is "unexpected" from the trad. makefile POV.
Reported-by: Tomasz Kłoczko <kloczek@github.com>

Ensure proper working dir when processing rpmrc, platform and macros

---

tests/CMakeLists.txt

On Rocky Linux /etc/os-release contains not only ID="rocky", but also ID_LIKE="rhel centos fedora" and the grepping got that wrong. Let the shell do the work for us.
Reported-by: Dmitry Mikushin <dmitry@kernelgen.org>

Make test-suite os detection stricter

---

tests/Dockerfile

The main reason is to get real-world relevant warnings from the CI build, gcc with no optimizations seems to miss all sorts of things. Debug info is just handy to have around when developing.

Enable debug information and optimizations in the CI build

---

build/parsePreamble.c
build/parseSpec.c
build/rpmbuild_internal.h
include/rpm/rpmspec.h
tests/data/SPECS/dynamic.spec
tests/rpmbuild.at
tools/rpmbuild.c

as far as possible. This allows setting these tags during the build using the dynamic spec feature.
Move
copyTagsDuringParse
requiredTags
optionalTags
isMemberInEntry()
checkForValidArchitectures()
checkForRequired()
checkForDuplicates()
fillOutMainPackage()
copyInheritedTags()
from build/parsePreamble.c to build/parseSpec.c
Use an already existing main package in parsePreamble()
New function finalizeSourceHeader() to move some initialization after build.
Add RPMSPEC_DONTFINALIZE flag to delay package finialization after the build in rpmbuild. rpmspec and API parsing without the flag still finializes the packages right away.

Move checks and package initialization after build

---

tests/CMakeLists.txt
tests/mktree.fedora

Commit d4e808ebda3ec1d85fcdb176eae31901b74c6e91 added cmake caching for mktree so that we don't rebuild the tree on each "make check" invocation.  However, this means we can now easily miss some test dependencies being updated since we don't depend on everything, e.g. the data/ dir.
To fix this, instead of adding each and every file and directory as a dependency of the mktree.output command, just rebuild the tree every time.  The base image (made with DNF) is already cached anyway, and the added overhead is tiny and outweighs the (potential) engineering hours lost due to this.
The funny thing is, this was already fixed once in 2019: fc05045008d84429bf51154642e18fda70d3f256
Sometimes you've just gotta fix stuff twice before it sticks!
Fixes: #2725

Fix regression of mktree not always rebuilding

---

macros.in

Offer a generic way to place icons in the proper system dir
Resolves: #2196

Add %_iconsdir macro

---

docs/man/rpm-plugin-audit.8.md
docs/man/rpm-plugin-dbus-announce.8.md
docs/man/rpm-plugin-fapolicyd.8.md
docs/man/rpm-plugin-ima.8.md
docs/man/rpm-plugin-prioreset.8.md
docs/man/rpm-plugin-selinux.8.md
docs/man/rpm-plugin-syslog.8.md
docs/man/rpm-plugin-systemd-inhibit.8.md
docs/man/rpm-plugin-unshare.8.md
docs/man/rpm-plugins.8.md
docs/man/rpm.8.md
docs/man/rpm2archive.8.md
docs/man/rpm2cpio.8.md
docs/man/rpmbuild.8.md
docs/man/rpmdb.8.md
docs/man/rpmdeps.8.md
docs/man/rpmgraph.8.md
docs/man/rpmkeys.8.md
docs/man/rpmlua.8.md
docs/man/rpmsign.8.md
docs/man/rpmspec.8.md

While there is no generally agreed standard for this we should at least use only one. Comma separated lists are commonly used. Let's just pick *italic* for man pages.
Thanks to Frank Dana <https://github.com/ferdnyc> for pointing this out.
Resolves: #2731

Use uniform formatting for SEE ALSO sections

---

build/parsePrep.c
build/parseSpec.c
build/rpmbuild_internal.h
build/spec.c
include/rpm/rpmmacro.h
rpmio/macro.c
tests/data/SPECS/hello2-suid.spec
tests/rpmbuild.at
tests/rpmspec.at

This is a fun little series. Details in the commit messages, but briefly:
- Implement support for auxiliary macros, ie macros implemented in C outside the macro engine itself. Some renames + API exports required for this.
- Turn the deprecated %patchN into a hard error, this is the sacrificial lamb of this change :sheep: 
- Finally, convert %prep into a regular build scriptlet :partying_face:
Fixes: #2205

Convert %prep into a regular build scriptlet

---

build/parseSimpleScript.c
docs/manual/spec.md
tests/data/SPECS/append.spec
tests/rpmbuild.at

Allows %build, %install, %check, %clean and %generate_depends to be augmented arbitrary number of times by appending or prepending to them. The main use-case is to support automatic population of these sections (declarative builds) while still allowing packagers to easily tweak them, but could also be useful for complicated conditional specs and such.
%prep is missing from the list because it's way too special at the moment, it'll gain this capability when #2205 is fixed.
Related: #1087

Implement prepend and append modes for all our normal build scriptlets

---

tests/mktree.oci
tests/mktree.rootfs

Right now, if the podman image fails to build or rpm fails to build/install, we happily continue and run the test-suite, only to eventually fail with some cryptic error, such as:
error: cannot find rpm
Not too helpful, indeed.  Instead, just fail the whole tree preparation process if we encounter an error.
Fix the return code of unshared() so that we don't fail on that, though. Also, when building the RPM layer, use a proper cleanup trap instead of ignoring SIGINT since a failing make_install() can now terminate the script.
Fixes: #2667

Exit from mktree on failure

---

fileattrs/sysusers.attr
macros.in
tests/data/SPECS/klang.spec
tests/rpmi.at

Initially reported at https://bugzilla.redhat.com/show_bug.cgi?id=2246236 and also #2741. Details in the commit messages. Amazing how many bugs and oversights one can pack into such a tiny little macro :laughing:

Bunch of sysusers.d handling fixes

---

INSTALL
rpmio/rpmpgp_legacy/CMakeLists.txt
rpmio/rpmpgp_legacy/digest_openssl.c

Avoid the now deprecated RSA and DSA data types and use the generic EVP_PKEY
Resolves: #2294

Move OpenSSL code to newer API

---

macros.in

Configure traditionally sets it to %{_prefix}/com which RPM has followed so far. But this directory is not used anywhere and everybody changes the location to /var/lib. As we are only changing the macro and not the configure default this should be relatively save to do.
Resolves: #2092

Set %_sharedstatedir to %{_var}/lib

---

build/files.c
tests/data/SPECS/source_date_epoch.spec
tests/rpmbuild.at

Commit 11132fc21fb01ed63c621d852bc081a914d4f021 assumed that the value of 0 is never used in practice and thus used it to indicate "disabled", however that assumption has turned out to be wrong because ostree uses precisely that value as mtime in inodes, which in turn breaks existing workflows in this space (see the associated ticket).
Fix this by reverting the above commit (except leaving source_date_epoch initialized to 0, to prevent GCC warnings as mentioned in that commit).
As to why not just initialize source_date_epoch to -1: time_t happens to be a signed integer on most platforms but POSIX doesn't specify its signed-ness.
Add some accompanying tests too.
Fixes: #2679

Allow SOURCE_DATE_EPOCH=0 again

---

tests/Dockerfile.fedora

The fedora-repos-modular package is gone from F39.  This commit makes the Dockerfile work on a F39 host with the mktree.oci backend since we override the release with "podman build --from fedora:39 ..." there.

Adapt Dockerfile.fedora to F39

---

scripts/brp-compress

commit f3f763e54d introduced the use of 'read -d' which is bash specific.

Switch brp-compress to bash

---

lib/fsm.c
tests/rpme.at

glibc versions prior to 2020 know about AT_SYMLINK_NOFOLLOW but don't actually implement it for fchmodat() and returns ENOSYS when used. We don't check the return code in removeSBITS() so this silently fails on those older versions.
We already verify the thing is not a link in the fstatat() condition because cap_set_fileat() doesn't have any "dont follow" mode at all, so we can just as well drop it from the fchmodat() and make this work on more libc versions.
Add a test for the suid bit removal while at it.

Fix sbit removal if fchmodat() doesn't support AT_SYMLINK_NOFOLLOW

---

lib/fsm.c

The full path is visible in the actual file operations later, but the pre-flight disposition diagnostics is unreadable without the full path. This regressed in the switch to relative paths for the *at() API family for the symlink CVE fixes.

Emit full paths for file disposition diagnostics on --fsmdebug

---

rpmio/macro.c

"long int" on at least x86 Linux is exactly the same as a plain "int", so calculations can easily overflow. 32bit systems are not expected to have hundreds of gigabytes of memory but a 32bit process on a x86_64 can run into all sorts of funny things, such having 500GB system memory. At which point the type capable of addressing all of process memory is absolutely useless for calculating the total memory.
Use uint64_t in the memory calculations to make the size explicit. Of course one day we may cross that border too, but I hope to be retired by then.
Fixes https://issues.redhat.com/browse/RHEL-16557

Fix integer overflow in memory calculations on 32bit systems

---

build/build.c
build/files.c
build/parsePrep.c
build/rpmfc.c
lib/rpmug.h

There's no situation where rpmbuild should use uid/gid from either the filesystem or current user. The former made sense in the pre-historic times before Buildroot was a thing, but in the last 20+ years that's always the wrong thing to do. Always. The only user/group info rpm can legitimately use is the one that is explicitly specified in the packaging, and otherwise fallback to root/equivalent.
Besides fixing a long-standing annoyance with src.rpm file ownership, this also fixes a regression in 4.19.0 where a non-local or otherwise unresolvable user info could cause a segfault during rpmbuild (RhBug:2248763).
Fixes: #2604

Never use current user info or file ownership during build

---

CMakeLists.txt

Right now, we "leak" any local branch or tag names into the ChangeLog which is unnecessary (e.g. "experiment-foo-123") and also just pollutes the diff when comparing ChangeLogs between releases.  Only show the plain log.
Fixes: #2647

Don't include git refs in ChangeLog

---

docs/man/CMakeLists.txt

See the first commit for details.

Build all manuals regardless of enabled features

---

docs/manual/macros.md

The Macros documentation claimed that
```spec
0%{!?with_python3:1}
```
was a shorthand for
```spec
%{?with_python3:1}%{!?with_python3:0}
```
which 'is expanded to 1 if "with_python3" is defined and 0 otherwise'.
That's true of the latter, but not the former, which would expand to `1` (actually `01`) if `with_python3` is _not_ defined. Correct to `0%{?with_python3:1}`.

docs/macros.md: Fix expansion shorthand

---

lib/fsm.c

For normal debug output the basename of the files are sufficient as when debugging is enabled the directories are also printed. But here the warning is given without a debug flag so we need the full context right there.

Print full path if file removal fails

---

lib/fsm.c

There's no reason to complain about missing user/group for entities we don't create at all. It's cosmetical only, but "regressed" in the 4.17 fsm robustness rewrite.
Reported in https://issues.redhat.com/browse/RHEL-18037

Don't warn about missing user/group on skipped files

---

rpmio/rpmlua.c
tests/rpmmacro.at

Fix regression in Lua scriptlet runaway child detection
Commit a8107659ef3dd4855729bf65aa4d70f784cb5a5f moved the detection to parent using waitpid(), but this causes it to complain on any process in the same process group. In the usual rpm context we don't have any, but we can't very well tell API users not to have any children. And then failed to detect a runaway Lua child in one of our own tests. Uff.
rpmlog() in the child has the issues mentioned in the originating commit, but that's a problem that needs to be solved elsewhere. Revert back to issuing a warning when we actually *are* in the child process, so there are no false positive possible. Use EXIT_FAILURE like in the original version, dunno why I'd changed that.
Update the rpmlua test to expect the deserved warning, and use …

Fix regression in Lua scriptlet runaway child detection

---

CMakeLists.txt
build/CMakeLists.txt
config.h.in
include/rpm/rpmbuild.h
lib/CMakeLists.txt
misc/CMakeLists.txt
plugins/CMakeLists.txt
rpmio/CMakeLists.txt
rpmio/rpmglob.c
rpmio/rpmpgp_legacy/CMakeLists.txt
sign/CMakeLists.txt
tools/CMakeLists.txt
tools/rpm2archive.c

Should fix the issues brought up in #2807 - portability rot that inevitably happens when you only build on one target.

Fix unconditional uses of Linux-specific extensions

---

CMakeLists.txt

The build fails because of a missing include in cmake:
CMake Error at CMakeLists.txt:353 (check_symbol_exists):
Unknown CMake command "check_symbol_exists".
Include the needed file to fix the issue.

Add missing include

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Have a bit of structure for the bug reports to tell people what information is expected/necessary.
Point people to discussions for RFEs and have RFE tickets only be created after a course of action has been decided on.
Resolves: #2752

Create Issue templates for Bug reports and RFEs

---

python/rpmver-py.c
tests/rpmpython.at

Hello!
While I was working on another issue, I found that the inequality operator of python `rpm.ver` objects would not work as I was expecting to. `!=` would always return `True` if the compared objects were not the actual same python object. That was leading to situations as
```python
(v := rpm.ver('1.0')) != v        # False, we are comparing the object with itself
rpm.ver('1.0') != rpm.ver('1.0')  # True, although they hold the same version tag string
```
I'm not sure whether that was the intended behavior or not. It was not quite what I expected when I tried applying the operator. I didn't research the topic really exhaustively, but I couldn't find related issues at least in the PRs of this repo.
Anyway, this patch adds the `PY_NE` case to the `tp_richcompare` slot function and adds …

Return false when comparing different python objects holding the same version tag

---

python/rpmver-py.h
tests/rpmpython.at

Hi again,
I'm opening this PR due to the main issue I found when writing a `rpm.ver` subclass in python: Trying to compare different subclass instances would raise a `NotImplementedError` while it was supported on base class instances.
The reason behind that was that the `verObject_Check` macro checked for operand types to be the same as `rpm.ver`. A way to overcome that, is checking their types are subclasses of `rpm.ver`, or simply calling `PyObject_TypeCheck`.
I'm proposing this patch only targeting the `rpm.ver` type as I'm not sure if such behavior was intended in the first place. In fact, most of the python bindings seem to follow the same type check pattern. Moreover, although not directly related to `rpm.ver` (but `rpm.ts`), I found a similar proposal was made but not merged in …

Support rpmver-py comparison operator inheritance

---

CMakeLists.txt

This was lost in autotools -> cmake transition. The particular reason to make it explicit is that readline is gpl version 3 licensed, and in some builds components under that license need to be excluded.

CMakeLists.txt: restore readline support as an explicit option

---

lib/rpmrc.c
lib/rpmug.c

This seems like a huge overkill when in 4.19.1 there's exactly one rpmfiStat() call that unnecessarily invokes an rpmug lookup in a threaded scenario, but then rpmfiStat() and rpmfilesStat() are public APIs that people expect to be safe for use within the originating thread.
Collect all the caching data into a struct and allocate on per-thread basis, this seems like the path of least trouble in this case and git diff --stat agrees.
It's worth noting that this also simplifies the caching, we no longer keep separate name to id and id to name, totaling caches totaling four. We simply cache one id/name for for user and another for group data. Also, reset ids to 0 rather than -1, this is far more obviously a safe value as we have special cases to handle id 0.
rpmugUname() and rpmugGname() are …

Make user/group lookup caching thread-safe

---

scripts/perl.req

match any <<MARKER providing:
- it is not in comment (not preceded by #)
- it can't be string literal (not preceded by ' or ")
- as a sanity check it must be preceded by either whitespace, comma or equals sign
adds support for
return <<"EOS";
fun(arg, <<"EOS");

perl.req: make heredoc block matching more generic

---

docs/manual/file_triggers.md
lib/psm.c
lib/rpmtriggers.c
lib/rpmtriggers.h
tests/data/SPECS/parallel.spec
tests/rpmscript.at

This adds the first argument to file trigger script calls, just like with regular triggers. The second argument will be added in a separate commit.
Related: #2755

Pass arg1 to file trigger scripts

---

CMakeLists.txt
rpmio/expression.c
tests/Dockerfile.fedora

Similar to ASAN, now that we can this is a nice and cheap way to keep compiler gremlins at bay.

Add a build option for enabling undefined behavior sanitizer, use for CI

---

tools/CMakeLists.txt
tools/rpmdump.c

This started life as pkgdump.c written way back when I needed to analyze some low-level issues with malformed packages and the like. Since then it's proven necessary every once in a blue moon, so might as well include it in the rpm codebase where it may actually be kept up to date and even evolve a bit. Since this is not an end-user tool, stash it away in /usr/lib/rpm.

Add a low-level package dump utility

---

docs/manual/file_triggers.md
lib/psm.c
lib/rpmtriggers.c
lib/rpmtriggers.h
lib/transaction.c
tests/data/SPECS/filetriggers.spec
tests/rpmscript.at

This is the other half of #2755 adding the second argument to file trigger scripts.

Pass arg2 to file trigger scripts

---

docs/manual/conditionalbuilds.md
macros.in
tests/rpmbuild.at

The bcond mechanism of rpm allows to specify a default for a feature in a spec file, which can be overridden with the command line. SUSE wants to build packages with the same source in different projects. Thus we need a way to specify a default via an rpm macro.
Our first try was to misuse the command line feature by putting `%_with_foo 1` in the macros. But that has two disadvantages: it breaks the command line and it makes it impossible to change the default in a derived project, as rpm cannot undefine macros in a macrofile and the bcond implementation only checks for definedness.
So here's a small addition that makes it possible to set feature defaults: Feature `foo` can be enabled by adding
the macro
```
%bcond_default_foo 1
```
The mechanism uses expression evaluation, so it is …

Allow to specify a default for bcond features in a macro file

---

build/rpmfc.c
tests/data/SPECS/interact.spec
tests/rpmbuild.at

Even max-rpm philosophy section points out that rpm builds are unattended, but then we do nothing at all to prevent it? I first though maybe this regressed when we switched the build scripts to use rpmfcExec() a few years ago, but there wasn't anything before that either. Weird.

Run build scriptlets with closed stdin to enforce unattended builds

---

CMakeLists.txt
tools/CMakeLists.txt

BYPRODUCTS is only relevant for Ninja generator which we officially don't even support, but on which these usages cause Ninja to error out with "phony target names itself as an input" messages.
I don't remember why exactly I put these BYPRODUCTS in there, but I know it was NOT to support Ninja explicitly. Probably it seemed somehow relevant to this cmake newbie and since it didn't harm anything ... on the make generator. Taking them out makes Ninja happy except for the test-suite. The make generator is still the only officially supported one though.
Reported-by: Timothy Brackett <brackett.tc@gmail.com>

Drop erroneous BYPRODUCTS uses from the cmake files

---

tests/CMakeLists.txt
tests/README.md

Ninja doesn't support passing environment as command line arguments like make does, access TESTOPTS through environment instead of the make syntax to make it work for both generators.

Use Ninja-compatible syntax for passing TESTOPTS

---

build/rpmfc.c
docs/manual/dependency_generators.md
tests/rpmbuild.at

Allow declaring file attributes from the spec via %_local_file_attrs macro. This allows enabling file attributes and their dependency generators even if they are only shipped in the package itself and are not yet installed.
The names need to be separated by colons (:).
Co-authored-by: Florian Festi <ffesti@redhat.com>
Resolves: #782

Add support for spec local file attributes and generators

---

docs/man/rpm.8.md
include/rpm/rpmtd.h
lib/formats.c
lib/headerfmt.c
rpmpopt.in
tests/rpmquery.at

The existing --xml output is extremely useful when inspecting oddities but the format is such an eyesore. JSON is much saner to look at.
Details in the commits and their messages, but the first commits are just refactoring to make this feasible. The actual feature in the last commit is quite small, as often happens the tests are bigger than the actual patch.

Implement --json query format

---

lib/rpmfi.c

%config is only allowed for regular files and links. While rpmbuild won't produce package with other files with %config other tools might. Handle these cases gracefully by ignoring the %config flag.
Resolves: #2890

Ignore %config flag where not supported

---

docs/man/rpmkeys.8.md
tests/rpmdb.at
tools/rpmkeys.c

This is a  bit of a hack as it manipulates the parsed cli parameters to
to the "right thing" and then calls rpmcliQuery and rpmErase.

Add --list-keys and --delete-key to rpmkeys 

---

macros.in

When %autosetup -S git is used, a bunch of git commits are created. Without an override, their metadata will include the current time. Many projects include the git hash of HEAD in the build information, which means that the build result is not reproducible. Since we're creating a scratch repo ourselves, this hash doesn't have any meaning outside of the build. If $SOURCE_DATE_EPOCH is set, use that as the commit timestamp instead. (If $SOURCE_DATE_EPOCH is _not_ set, use the current timestamp as before. When $GIT_{COMMITTER,AUTHOR}_DATE are empty, git ignores them.)
For projects which somehow make use of the git commit information, this fixes an irreproducibility. For projects which don't care about the git hash, this should make no difference.
Fixes …

Set git commit dates based on $SOURCE_DATE_EPOCH

---

build/build.c
docs/manual/spec.md

This is useful for consistently setting timestamps within build scriptlets, in particular when doing reproducable builds.

Expose build time to package build scriptlets via $RPM_BUILD_TIME

---

build/build.c

Despite openSUSE packages having a %changelog section at all times, rpm throws this error.
Turns out it's just terribly worded. Fix that.

build: reword "%changelog is missing"

---

build/parsePreamble.c
build/parseSpec.c
build/rpmbuild_internal.h
docs/manual/dynamic_specs.md
tests/data/SPECS/dynamic.spec
tests/rpmbuild.at

Many things need to be known before the build can be started. Make
declaring these sections or directives an error when encountered parsing
the generated Spec parts.
Resolves: #2693

No build directives in generated spec parts

---

rpmio/macro.c
tests/rpmmacro.at

Strip trailing "/"
Keep "." and ".." untouched
Keep root dir for files in the root dir
Return "." for files without directory and empty strings
See man 3 dirname
Resolves: 2928

Make %dirname behave like dirname (3)

---

build/rpmfc.c

If a dependency generator dies while we're still writing to its stdin, it causes us to die rather randomly. Typically happens with fake dependency generators that don't actually bother reading their input and/or write anything back. This is almost certainly the ghost failure we've occasionally seen in the test-suite too (#2470).
Resurrect the explicit SIG_IGN that got removed apparently in commit 375a6b5630b8e37e1d3f0c7ecbe10fe460c4d420. The matter was further confused by NSPR (which we once relied on) always setting SIGPIPE to SIG_IGN.
Suggested-by: Michael Schroeder <mls@suse.de>
Fixes: #2949

Fix dependency generators sometimes dying with SIGPIPE

---

rpmio/macro.c
tests/rpmmacro.at

Issue a warning when passing arguments to non-parametric macros

---

build/build.c
build/files.c
build/parsePreamble.c
build/parseSpec.c
build/policies.c
build/rpmbuild_internal.h
build/spec.c
docs/manual/buildprocess.md
docs/manual/dynamic_specs.md
include/rpm/rpmbuild.h
macros.in
tests/data/SPECS/simple.spec
tests/rpmbuild.at
tests/rpmspec.at
tools/rpmbuild.c

In our ancient wacko setup, %_builddir is shared by all your packages, under which a package may create %buildsubdir - if it uses %setup that is. In other words, there's no safe and sane place for rpm to place per-build material. Introduce a new intermediate directory between the two, created in a newly added (internal) %builddir build step, to give rpm that place. This opens up all manner of opportunities, to be explored in later commits.
A new build-time macro %pkgbuilddir is added for the absolute path of this new directory, but in addition we override %_builddir to the same value for maximum compatibility with existing specs - a LOT of packages reference %{_builddir} for all sorts of (mostly bad) reasons and we don't want to deal with the carnage that would follow from breaking it. A …

Introduce an rpm-controlled per-build directory

---

.github/workflows/linux.yml

Some of our Python tests started suddenly failing semi-consistently, this turned out to be an issue in the most recent GH runner image kernel where ADSL runs with more entropy than before, and this clashes with ASAN. Revert the runner VM to the former values to fix for now.
Oh and don't think I figured this out by myself, this workaround was suggested by @igsilya in
https://github.com/actions/runner-images/issues/9491, cheers!

Work around ASAN incompatibility with GH runner image >= 20240310.1.0

---

build/parsePreamble.c
build/parseSpec.c
build/rpmbuild_internal.h
build/spec.c
docs/manual/buildsystem.md
tests/data/SPECS/amhello.spec
tests/rpmbuild.at

Verify all required sections (%conf, %build and %install) are covered by the requested buildsystem, error out with a proper error message if not.

Validate Buildsystem definitions, error out on unknown

---

build/parsePreamble.c
docs/manual/spec.md
tests/data/SPECS/hello.spec
tests/rpmspec.at

Update to the documentation is still needed
Resolves: #2927

Allow whitespace before directives in the Preamble

---

tools/rpm2archive.c

In the "newc" cpio format the content of hardlinked files is supposted to be stored with the last hardlink and not the first.
Fixes issue #2974

rpm2archive: fix hardlink handling in cpio output

---

build/build.c
build/parsePrep.c
build/parseSpec.c
include/rpm/rpmfileutil.h
include/rpm/rpmmacro.h
lib/backend/bdb_ro.c
lib/backend/dbi.h
lib/backend/dummydb.c
lib/backend/ndb/glue.c
lib/backend/sqlite.c
lib/rpmdb.c
lib/rpmfi.c
lib/rpmfs.c
lib/rpmfs.h
lib/rpmrc.c
lib/tagexts.c
lib/tagname.c
lib/transaction.c
plugins/dbus_announce.c
plugins/fapolicyd.c
plugins/fsverity.c
plugins/ima.c
plugins/selinux.c
rpmio/rpmmalloc.c
sign/rpmgensig.c
sign/rpmsignfiles.c
sign/rpmsignverity.c

Int vs enum type mismatches, initialization order consistency and other "fascinating" trivia.

Spring cleaning!

---

lib/backend/sqlite.c

This one is a particularly bad case of int/enum abuse. Not so suprisingly, using separate variables for sqlite and rpm side returns makes the stuff much saner. I can kinda remember this even: "Just make it work now, I'll clean it all up later" and this is payback time.

Sqlite backend spring cleaning

---

tests/README.md

This is entirely non-obvious as one would assume that any exported env vars are inherited by the runroot() subprocesses.  Yet they aren't because we intentionally reset the environment in the bwrap containers with --clearenv (see atlocal.in).  It's a common use case, though, so deserves a proper note.

Add a note about --setenv to test README

---

docs/man/rpm.8.md

These two commits, ready for inclusion, document that the `--macros` option accepts globs as well and fix a warning caused by groff not being able to adjust (justify) the line(s) with the default value for the `--macros` option.

Fix "cannot adjust line" warning in rpm(8) man page

---

docs/manual/macros.md
include/rpm/rpmfileutil.h
lib/rpmrc.c
rpmio/rpmglob.c
tests/rpmmacro.at

Look for per-user macros primarily in ${XDG_CONFIG_HOME}/rpmmacros but fall back to traditional ~/.rpmmacros iff it exists and there's no config in the XDG location. As per the XDG spec, if ${XDG_CONFIG_HOME} is not set, it defaults to ~/.config
Fixes: #2153

Support per-user macro configuration in XDG_CONFIG_HOME

---

tests/rpmvercmp.at

There's no reason each of these needs to perform their own test setup and cleanup when they're not even writing anything. Doesn't change what gets tested, just less useless chatter in the test output.

Lump version comparison tests into a single test-group

---

build/rpmfc.c
tests/data/SPECS/stdin.spec
tests/rpmbuild.at

Commit e5d7a823c99b84d65ecbf3810b68aab372ef5d14 broke builds relying on libtool (and no doubt some others as well) because libtool redirects stdin in some of its tests and this fails if stdin is closed. Instead of closing, pass the write-only end of the pipe as the stdin to build scriptlets. This way the descriptor is there and can be further redirected, but any attempt to read from the (unredirected) stdin will error out. Add a test-case too.

Use a less intrusive unattended enforcement in rpmbuild

---

build/parseSpec.c
docs/manual/spec.md
tests/data/SPECS/eliftest.spec

Still issue an warning for everything else. Now that comments are allowed again may be we should issue an error for those cases.
Resolves: #829

Allow comments after conditionals

---

CMakeLists.txt

Doxygen is absolutely not required for building rpm, it's only required for building dist tarballs which come with the documentation pre-built.
Fixes: 26a1ccf2819ab148aef3cd354e1cbdb70a9fe5b7

Revert doxygen as a default build requirement

---

CMakeLists.txt
tools/rpm2archive.c

Our headers are always useing utf8 and the pax standard also requires utf8 strings. So do this nasty little locale switching to make libarchive not depend on the active locale.

Set the charset of the libarchive strings to utf8

---

include/rpm/rpmpgp.h
lib/rpmvs.c

rpmvs.c is the only one using it in the rpm source and it can be trivially rewritten.

Get rid of pgpGrab()

---

macros.in
tests/data/SPECS/amhello.spec
tests/rpmbuild.at

The new %(auto)setup -C option complements the declarative buildsystem very nicely: this is a trivial detail, don't bother the packager. While we can't default to it everywhere, Buildsystem is a great opportunity to do so.
Suggested-by: Miro Hrončok <miro@hroncok.cz>
Fixes: #2998

Default to automatic build directory path on declarative builds

---

build/build.c
build/files.c
build/pack.c
build/parseSpec.c
lib/headerutil.c
tests/rpmquery.at
tests/rpmspec.at

The two commits improve source and binary package header detection right after spec parse, fixing #2819 in the process. Details in commits.

Ensure binary and source headers are identified as such after parse

---

build/files.c
build/parsePreamble.c
build/parsePrep.c
build/parseSpec.c
build/rpmfc.c
include/rpm/rpmds.h
lib/depends.c
lib/formats.c
lib/fsm.h
lib/psm.c
lib/relocation.c
lib/rpmds.c
lib/rpmug.h
rpmio/macro.c
rpmio/rpmio.c
rpmio/rpmio_internal.h
rpmio/rpmlua.c
rpmio/rpmlua.h
rpmio/rpmpgp_sequoia.c
sign/rpmsignfiles.c
sign/rpmsignfiles.h
tools/cliutils.h
tools/rpmlua.c
tools/rpmsort.c

Another batch of delightful trivia to appease c++.

Type pedantry and similar cleanups in preparation for c++

---

include/rpm/rpmpgp.h
rpmio/rpmpgpval.h

This subpacket is an alternative to the "issuer keyid" subpacket. It contains the pubkey version plus the complete fingerprint.
I would prefer to drop all the subpacket definitions from the rpm code, as rpm has no business dealing with subpackets. Unfortunately `pgpValString(PGPVAL_SUBTYPE, val)` is in the public API...

Add the "issuer fingerprint" subpacket type

---

include/rpm/rpmds.h
lib/psm.c
lib/rpmds.c
lib/tagexts.c
python/rpmds-py.c
tests/rpmpython.at

De-duplicate the code between psm and tag extensions and let API users into the loop too. More details in commit messages.

Add + use rpmdsIsSysuser() API for testing and decoding sysuser provides

---

build/files.c
tests/data/SPECS/caps.spec
tests/rpmbuild.at

This leak has been there ever since rpm 4.7.0, so pretty close to 15 years. ASAN would've caught it, if it had it been tested. Oops. Of course, in the fakechroot era we couldn't have tested installation but we could've at least tested the parsing side.
Add tests for parsing, query and install functionality, and fix the leak that is now very visible.

Fix an ancient memleak on %caps() parsing, add tests

---

build/build.c

As we need to check all file lists we need to have them parsed - even if %build and %install have not been run due to --short-circuit
Tested manually with #3040. There is fixes test 334.

Parse dynamic spec parts for rpmbuild -bl

---

include/rpm/rpmpgp.h
rpmio/rpmpgpval.h

This type is needed to verify the primary binding signature embedded in subkey binding signatures.

Add the "Primary Binding" pgp signature type

---

include/rpm/rpmtypes.h
rpmio/digest.c
rpmio/digest_libgcrypt.c
rpmio/digest_openssl.c
rpmio/expression.c
rpmio/macro.c
rpmio/rpmio.c
rpmio/rpmkeyring.c
rpmio/rpmlog.c
rpmio/rpmlua.c

Convert a bunch of dynamic allocations in librpmio to native C++ new/delete to enable use of native structures in those structs and then take advantage of it. Misc other string/vector conversions too.
This is a pretty petty random stuff, the primary points being to bring the number of raw C allocations down, and at least as importantly, just to get the first real step into the C++ land over with.

Convert a bunch of librpmio stuff to native C++

---

build/parsePreamble.c
build/parseSimpleScript.c
build/parseSpec.c
build/rpmbuild_internal.h
build/spec.c
docs/manual/spec.md
tests/data/SPECS/amhello.spec
tests/rpmbuild.at

The append and prepend modes got added before the declarative Buildsystem, and did not get thoroughly tested with it. The existing %build -a test didn't actually work but automake handling the build in %install masked the issue embarrasingly. As the Buildsystem is parsed after everything else, there's no way the previous append/prepend implementation could work correctly with it.
Do what we should've done from the start: collect any prepend/append stuff into separate data structures and apply them after everything else has been parsed. This also lifts the artificial sounding restriction wrt the corresponding main section:it's really the right thing to do, even if it's a bit more code.
Make the tests wrt buildsystem much more thorough to ensure it all really works, blush.
Fixes: #3024

Fix build scriptlet append/prepend interaction with Buildsystem

---

tests/CMakeLists.txt
tests/rpmi.at
tests/rpmsigdig.at

We define two new test macros RPMOUTPUT_SEQUOIA and RPMOUTPUT_LEGACY to make it easier to write parser dependent test output in the test cases.

Adapt tests to current state of the "legacy" parser

---

rpmio/macro.c
tests/rpmmacro.at

freeArgs() only popped any local macros once, so if a local macro was pushed multiple times, whether through %define or multiple identical options getting passed, we leaked any remaining macros to the outside scope.
Simply pop the local macros in a loop to fix. Have the internal popMacro() return the previous pointer (if any) to simplify the job. We even had an expected-fail test for this, which now passes.
This bug was circa 26 years old. Some might call it vintage at this point.
Fixes: #3056

Fix multiply defined local macros escaping scope

---

lib/backend/dbi.h
lib/cpio.c
lib/fprint.c
lib/header.c
lib/psm.c
lib/rpmdb.c
lib/rpmds.c
lib/rpmfi.c
lib/rpmfs.c
lib/rpmgi.c
lib/rpmlock.c
lib/rpmplugins.c
lib/rpmprob.c
lib/rpmps.c
lib/rpmscript.c
lib/rpmtd.c
lib/rpmte.c
lib/rpmts.c
lib/rpmvs.c

Nothing hugely interesting in here, see commit 0d1071b99ada2df920ba657d9e015e0c2259d4b6 for rationale.
There are bits and pieces to finish in librpmio side still but moving on to librpm as some of this stuff is linked, eg string pool cannot use C++ containers before rpmds is updated to clean up after itself, otherwise there will be an unfixable indirect leak from rpmlibProvides_s struct on process exit :zany_face:

Convert a bunch of librpm stuff to native C++ allocation (and containers)

---

build/parseSpec.c
tests/data/SPECS/macrosource.spec
tests/rpmbuild.at

If sources or patches in the spec are defined via a macro that does not yet exist, it'll still work for building if the macro has been defined by that time as there's another round of expansion there. But this can leave the source/patch names inserted to the header disagreeing with what actually ended up in the source package, eg in the testcase you'd previously get '%{somemacro}-2.0.tar.gz' in the header whereas the src.rpm had the right contents.
While defining sources this way seems mad and brittle, it does actually work for building rpms and there's a whole ecosystem of packages relying on it in Fedora. So lets at least be consistent about it, and re-expand the source paths once more before inserting in the header, because that's what happens for them in the actual build as well. …

Fix header source/patch names disagreeing with src.rpm contents

---

build/parsePreamble.c
tests/rpmbuild.at
tests/rpmspec.at

This causes more issues than it solves, at least presently. For one, when BuildArch is used it typically causes the path to disagree with the actual arch (eg on noarch packages). Which looks weird and causes yet other issues in turn. The other issue, raised by Neal Gompa, is that it can cause superfluous path differences in noarch subpackages, which sharing the noarch package across multiple architectures in at least koji.
Use -build suffix instead of %{_arch}. -build may seem redundant since by default it's in BUILD directory already, but this makes it more obvious in cases where the default is overridden (eg fedpkg overrides to current directory), and helps differentiating it from the %buildsubdir directory commonly created by %setup.
Suggested-by: Neal Gompa <neal@gompa.dev>

Drop architecture from %builddir path

---

tests/data/SPECS/templ.spec
tests/rpmbuild.at
tools/rpmbuild.c

When BuildArch is encountered during spec parse, rpm recurses the parse, but this doesn't reset/reload the global configuration and macros to match. So eg a "BuildArch: noarch" package gets built with a dramatically different macros depending on whether "--target noarch" was used or not, whereas people expect it to be the same - after all we give zero indication that anything might be wrong when --target wasn't specified.
Automatically detect and handle this condition in the rpmbuild tool: if the spec parse architecture disagrees with our loaded configuration, request a reparse with reloaded configuration for the matching target. This ensures 'rpmbuild -bb noarch.spec' and 'rpmbuild -bb --target noarch noarch.spec' run with the same exact configuration. 
Doing this also fixes the …

Automatically reload rpm configuration on mismatching BuildArch

---

build/build.c
build/parsePrep.c
tests/rpmbuild.at
tests/rpmspec.at

There's no reason %specpartsdir should be dependent on %setup use, just create it when we create the build directory too. Update tests accordingly.
The spec parse test is noteworthy, the specparts dir creation no longer shows up in spec parse output, which certainly is the way it should be: this is rpm internal infrastructure stuff and nothing to do with spec *parse*, this all only takes place during builds.
Fixes: #3063

Always create %specpartsdir on build

---

installplatform
macros.in
platform.in
tests/data/SPECS/specstep.spec
tests/data/macros.debug
tests/rpmbuild.at

All these years, enabling debuginfo has required distros to hijack the spec %install section with a macro like this:
%install %{?_enable_debug_packages:%{?buildsubdir:%{debug_package}}}\
%%install\
%{nil}
This for a widely used, longtime upstream supported feature is just gross, and also very non-obvious, feeble and whatnot. And totally prevents the new append/prepend options from being used with %install.
Take advantage of several newish features to make this happen: we need expressions to properly handle the numeric %_enable_debug_packages value from a macro, and if enabled, output the debuginfo template as a dynamic .specpart.
Enable debuginfo on Linux by default in the platform configuration. Notably noarch should not have debuginfo so it's disabled in the platform configuration - …

Add proper logic for debuginfo enablement

---

build/pack.c

This keeps the old behaviour of overriding the cookie. This may not me correct as the code looks like it reads the cookie from the srpm when doing rpmbuild --rebuild for the purpose of preserving it. Otoh the current behaviour with overriding it even in this case has been around for years. This whole cookie business seems to have some other issues, too, and needs further investigation. Here we are only trying to fix the memory leak.

Free old cookie value to prevent a memory leak

---

platform.in

Move the enablement logic to %__spec_install_template where it can be buried with relatively little danger of being overridden by distros or packagers. It's moderately annoying as the logic isn't no longer neatly in one spot, but %__spec_install_post is commonly overridden by distros and even packages, and in particular we don't want to have packages copy-paste all this stuff along, because that makes making any changes to this stuff even harder than it already is.
This should be entirely backwards compatible with all the pre-existing %__spec_install_post overrides.
Co-authored-by: Florian Festi <ffesti@redhat.com>

Improve the debuginfo enablement backwards compatibility

---

build/files.c
build/misc.c
build/pack.c
build/parsePreamble.c
build/parseScript.c
build/parseSpec.c
build/policies.c
build/rpmbuild_internal.h
build/rpmfc.c
build/spec.c

Details in the commits, in brief this brings the major data structures of librpmbuild under C++ native allocation and initialization, making it possible to use native data types in said structs.
A few "obvious" cases converted to STL too, but plenty more to do on that department.

Convert major librpmbuild structs to native C++ allocation / initialization

---

build/rpmfc.c
tests/rpmbuild.at

Commit ce6c3812af4c2a9e9fc6c2dc77e00e1e1487bb83 accidentally changed this namespace string literal too, oops. Possible because there was no test on it, so add one.

Fix a regression on dependency generator namespace directive

---

INSTALL

This should've been part of commit
200c91ff72ecfdf4751913e672660ffc0a680ff6.

Update OpenSSL requirement in INSTALL too

---

lib/rpmfi.c

This was a fairly tricky one, details in commits.

Replace rpmfi(les) hardlink discovery + lookup with STL containers

---

tests/rpmbuild.at
tools/rpmbuild.c

Commit 9d35c8df497534e1fbd806a4dc78802bcf35d7cb added a new step into the build process but I literally wasn't even aware we have a --noprep switch in rpmbuild, much less that it's used. Quite widely even, by mock.
Luckily this seems simple to fix, just skip %mkbuilddir in --noprep. Extend the dynamic buildrequires test to mimick what mock does.
Fixes: #3121

Fix --noprep regression from introducing %mkbuilddir

---

build/parsePrep.c
tests/rpmbuild.at
tools/rpmbuild.c

Instead of skipping everything in %setup, take advantage of it: we shouldn't unpack any sources but otherwise we can just let it fall through it, defining buildsubdir and everything, if we let rpm do its normal %mkbuilddir thing and just symlink to the in-place tree from rpm's %builddir. This way it's not such an ugly duckling interfering with how normal rpms are built, and even honors %setup flags to a degree.
This fixes two regressions: one introduced when adding %mkbuilddir that nukes your current directory with no questions asked if --build-in-place is used before it even starts, and an earlier one from commit b34333fa021c0ee7215714eeef96d1a2843ea08e that would nuke your precious in-place directory afterwards. And as a side-effect of all this, debuginfo generation also now works with …

Make --build-in-place much less of a hack and also, work

---

tests/rpmbuild.at
tools/rpmbuild.c

Since 9165963de8bb5d5ad0a24ea4656d6d04d733f6bc, the main header wasn't getting properly filled on plain src.rpm build modes like -bs. So a lot of things was missing, but spotted in particular because %packager wasn't getting set as per macros in Koji. Fix by letting rpm finalize the spec after parse when no dynamic spec parts are to be executed.
Add a bunch of tests around this - we can't possibly test every single build scenario but this should cover at least the most common ones pretty well.
Reported-by: Miro Hrončok <miro@hroncok.cz>

Fix incomplete header on plain src.rpm build modes regression

---

build/build.c
tests/rpmbuild.at

All the work we now do to get target platform right gets thrown away by mock apparently always passing "--target $(uname -m)" equivalent to rpmbuild, causing %_target_cpu and all that stuff be wrong during build scriptlet execution. Those are right during the initial spec parse so the old implementation just barely scraped through it all.
Hammer in a C-side test based on the package arch to disable debuginfo packages on noarch no matter what. Pfft.
Fixes: #3115

Hammer in "no debuginfo for noarch packages, damn it" rule

---

build/files.c

Didn't bisect but this is probably due to mucking around with the src.rpm name generation in dc47a50c6345a25b861305d8aa8ae464098834ff, but it's also much saner this way: the info should be copied from the main debuginfo package along with all the other similar stuff.

Fix regression on subpackage debuginfo RPMTAG_SOURCERPM missing

---

build/parsePreamble.c
build/parseSpec.c
docs/man/rpmbuild.8.md
include/rpm/rpmbuild.h
tests/data/SPECS/brtest.spec
tests/rpmbuild.at
tools/rpmbuild.c

Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=2284124:
cpack RPM generator uses --buildroot, which we axed in 9d35c8df497534e1fbd806a4dc78802bcf35d7cb a little too eagerly. We can't just break cpack so bring it back until cpack moves to something else.
On a related finding (@soig ), various specs use %{_buildrootdir} in ways that they really shouldn't, but since compatibility is cheap, we can bring it back but define it on our own terms: it's simply always the parent directory of %{buildroot}, rather than the other way around of %{buildroot} being a subdirectory of %{_buildrootdir}.

Minimally bring back --buildroot and %{_buildrootdir}

---

platform.in
tests/rpmbuild.at

One of the intentions with the debuginfo enablement rework in 4.20 was to allow debuginfo generation on packages that don't use %setup, or in other words, don't have %{buildsubdir} defined. Turns out there's just so many things out there, relying on all these exact bits and pieces to be JUST SO, this causes more harm than its worth.
So bring back the requirement of %{buildsubdir} macro to be defined for debuginfo generation to take place, update the caps testcase to cover both. At least we can now just define buildsubdir from the spec or even command line, so the promise to have debuginfo without %setup still holds, it's just not automatic everywhere.

Require %{buildsubdir} to be defined to get debuginfo packages again

---

build/parsePreamble.c
build/parseSpec.c
tests/data/SPECS/mydir.spec
tests/rpmbuild.at
tests/rpmmacro.at

Yet another %{_builddir} related quirk: it's not uncommon for packages to do things like this at the top of the spec:
%global vpath_build %{_builddir}/%{buildsubdir}/vpathbuild
The problem here being use of %global, long before these macros are defined at all. If %define was used this was no problem at all, but it only works with %global if these macros are either in their final value, or not defined at all. And with our new fancy intermediate builddir hackery, %{_builddir} is neither, which makes the behavior inconsistent.
%global and %define *are* different and no amount of trickery can (or should) make that go away, but as this breaks existing users it's worth trying to bend over a bit. So funnily enough, the best fix for this is to UNDEFINE %{_builddir} for the initial spec parse …

Improve %{_builddir} backwards compatibility

---

sign/rpmsignfiles.c

The sneaky construct hid more than just values starting from 1: there's no value 4 in rpmHashAlgo enum, so skipping that causes all the later hash names to be off by one.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2291183

Fix signfiles regression from 13a02b15d6552bc8e440235b846ea5257514d397

---

lib/backend/bdb_ro.c
lib/backend/dbiset.c
lib/backend/dbiset.h
lib/backend/ndb/glue.c
lib/rpmdb.c
tests/rpmbuild.at

Force all callers through the internal API instead of mucking with internals - preliminary heave to make moving it to C++ easier.

Refactor dbiset and callers to hide implementation

---

build/parseSpec.c
tests/data/SPECS/autosetup-noroot.spec
tests/data/SPECS/autosetup-singleroot.spec
tests/data/SPECS/dynamic.spec
tests/rpmbuild.at

Generating mandatory tags dynamically has them missing in SRPMs if build with rpmbuid -bs or such. To prevent this from happening check the source header right after the initial parse rn of the spec file. This is more strict than before relaxing this for dynamic spec feature as now errors can come up even if no package is actually build.

Check for mandatory tags after parsing the Spec the first time

---

docs/man/rpmsign.8.md

In the past handling signatures was done by the rpm / rpmbuild binaries directly. When this functionality was split into rpmsign the man page was not adjusted accoringly. This is the long overdue update.
Resolves: # 3125

Talk about rpmsign in the rpmsign man page

---

build/parsePreamble.c
tests/data/SPECS/weirdnames.spec
tests/rpmbuild.at

%setup always defaulted to %{name}-%{version} as the directory name, but most projects would only have regular characters in their tarball path components (and those that did, could be expected to deal with it). And when using tilde/caret in Version you'd use `%setup -n <path>` instead. This changed with the new %builddir in 4.20 where caret and tilde from version leak into build paths, and nowhere near all build systems, helper scripts and whatnot properly escape/quote all the paths they handle. Such as apparently ninja-build, reported in https://bugzilla.redhat.com/show_bug.cgi?id=2290987
Convert ^ and ~ in builddir to underscores. Note we specifically only convert that for the per-package %builddir we create, if somebody sets the top build directory to a path that includes such …

Avoid special characters from %{VERSION} in %builddir

---

include/rpm/rpmkeyring.h
include/rpm/rpmpgp.h
lib/rpmts.c
rpmio/rpmkeyring.c
rpmio/rpmpgp_dummy.c
rpmio/rpmpgp_sequoia.c

This currently only makes a difference if the "legacy" backend is used.

Implement merging of new key material when importing pubkeys

---

lib/backend/dbiset.c

This subtlety in commit 52f311e224254d7cb28bf2ced22db7b50e1a2653 resulted in not-so-subtle crash due to sort going out of bounds.

Fix a subtle thinko in dbiIndexItem less-than comparison

---

rpmio/url.c
tests/rpmgeneral.at

Rpm allows URLs as cli parameters. The files are then automatically
downloaded with %_urlhelper which defaults to curl(1). For far failures
have been ignored right away and error messages are generated later when
the file was not found on disk.
Issue a meaningful error message at least when the help program is
missing. This allows not to ship curl with rpm while still giving the
user a chance to find out what is going on.
Related: rhbz#2216754

Add error messages for url helper calls

---

include/rpm/rpmkeyring.h
include/rpm/rpmpgp.h

Otherwise these create warnings which fail the build if treated as errors.

Fix doc strings

---

tests/Dockerfile.fedora

Doxygen is present in the CI image but no longer automatically enabled since commit 26a1ccf2819ab148aef3cd354e1cbdb70a9fe5b7.

Explicitly enable Doxygen on our CI builds

---

tests/rpmgeneral.at

In some cases like the default /usr/local the build prefix leaks to %_tmppath. /usr/local/var looks rather wrong anyhow but that's another issue, just strip it out of the test result to avoid bogus build failures with other prefixes.
Fixes: 4c1f71ec9e171dcf29079ff80bab68d86d7d1856

Make the urlhelper test prefix-agnostic

---

tools/rpmuncompress.c

The ZIP format has no notion of time zone, so timestamps are only meaningful if it is known what time zone they were created in. Pass UTC to prevent time stamps to depend on local time zone setting and make builds from sources in zip files (more) reproducible.
Tested manually with Fedora's xz-java-1.9.zip as mentioned in the issue.
Resolves: #2955

Pass TZ=UTC to zip in rpmuncompress

---

build/build.c
build/parsePrep.c
rpmpopt.in
tests/rpmbuild.at
tools/rpmbuild.c

See commit messages for details, but this partially reverts d1075106bb315913574e1acac921058d23dd5130 to avoid a dependency on %setup that seems ... wrong for what --build-in-place is. Also, take advantage of rpm macro setup to handle this, so the rpmbuild command doesn't need any logic in it. Which also means %_build_in_place can be set from a spec directly.
Related: #3123

Another attempt at restoring + sanitizing --build-in-place

---

lib/backend/bdb_ro.c
lib/backend/dbi.c
lib/backend/dbi.h
lib/backend/ndb/glue.c
lib/backend/sqlite.c

I thought I already did these but looks like got side-tracked by the dbiset stuff...

Natively allocate database remaining backend layer structs

---

build/files.c
build/rpmbuild_internal.h
build/rpmfc.c
lib/backend/dbi.h
lib/depends.c
lib/rpmal.c
lib/rpmdb_internal.h
lib/rpmfi.c
rpmio/macro.c
rpmio/rpmhook.c

typedef's prevent const correctness and have various other issues, "using" is the native modern version. When in Rome...

Replace typedef's with using = for new internal C++ constructs

---

macros.in
tests/data/SPECS/hello-autopatch.spec
tests/rpmbuild.at

It is possible that the range given to %autopatch is not matching any actual patches. Issue an warning to give the packager a chance to realize that there is something fishy. Not turnng this into an error to not break existing builds.
Resolves: #3093

Add warning for %autopatch not applying anything

---

fileattrs/sysusers.attr

Without the newline, a sysusers file like
```
u saned - "SANE daemon user" /etc/sane.d /bin/false
m saned cdwriter
m saned usb
m saned scanner
```
Results in "funny" requirements
```
group(cdwriter)user(saned)
group(usb)user(saned)
```

Add missing newline in sysusers Requires

---

build/parseSpec.c
tests/data/macros.buildsystem
tests/rpmbuild.at

Give different errors depending on a build system not existing at all or not be defined properly. This makes it easier to detect issues in the build system declaration and no longer requires developers of new build system macros to pass --verbose to get meaningful messages.
Resolves: #3190

Better error for build system issues

---

tests/rpmmacro.at

Solves #3106
We should probably understand why the urlhelper tests are racy before merging.

Sort output for test case to avoid race condition

---

docs/manual/dependency_generators.md

Looks like people were confused by the fact that having a file attr not matching anything was legal. Be more explicit what is expected to make them actuaqlly useful.
Resolves: #2951

Make "minimal" file attr more clear

---

docs/manual/spec.md

Alternatively, we can keep it, but say `(removed in rpm >= 4.20, do not use)`

Undocument %patch1

---

rpmio/macro.c
tests/rpmmacro.at

$ rpm --define 'aaa %[%aaa]' --eval '%aaa'
let to a core dump due to a stack overflow. This was cause by the generation of the error message failing due to being too deep in the recursion of the macro expansion - creating more error messages.
Resetting the depth counter allows rendering the error message. As we are failing and breaking off the parse run this is fine to do.
Thanks to Miro Hrončok for reporting
Resolves: #3197

Reset recursion depth for error message

---

lib/rpmts.c
rpmio/CMakeLists.txt
rpmio/rpmpgp_sequoia.c

#3202 is failing due to a memory leak in existing code previously not exercised by CI, lets see if there's more stuff needed...

Fix(es) needed for moving to rpm-sequoia >= 1.7 

---

docs/manual/macros.md

This PR, in separate commits, updates the macros documentation to fix one formatting issue I'd noticed on the docs site, reformats two code blocks into markdown tables, and updates the formatting of all other tables in the doc.
1. **Unindent fenced code blocks** — I noticed on the docs page that they looked _terrible_  with the leading indents, which are very visible inside the fenced blocks. (Blocks are already indented, so it's not needed.) I don't know why I didn't fix this in #2251.
2. **Convert expansion explanation to table** — The explanation for how a macro is expanded was formatted as a code block with two columns. That screamed for a table, so I made it one. Note the choice to use "→" to replace the indent on a couple of the lines, since Markdown doesn't support column spans or …

More formatting fixes for macros doc

---

tools/elfdeps.c

Assume that the section does not hold a table if sh_entsize is 0 (as specified in the elf(5) man page) and just skip it if that's the case.

Fix division by zero in elfdeps (RhBug:2299414)

---

build/CMakeLists.txt
lib/CMakeLists.txt
rpmio/CMakeLists.txt
sign/CMakeLists.txt

Each library target's exported `INTERFACE_INCLUDE_DIRECTORIES` list, as written into the `rpm-targets.cmake` export file, is controlled by the `PUBLIC` arguments supplied to `target_include_directories()` for the library target.
* Directories scoped with the `$<BUILD_INTERFACE>` generator expression will be included in the export file written to the build dir by `export(TARGETS...)`
* Directories scoped with `$<INSTALL_INTERFACE>` will be included in the `rpm-targets.cmake` file installed into the `${CMAKE_INSTALL_LIBDIR}/cmake/rpm/` configuration directory.
Providing `PUBLIC` include directory paths for both the build and install contexts is important, because without them the exported CMake configuration is useless to library consumers.
(If the build is installed into `/usr/` or …

Build: Add include dirs to exported lib targets

---

lib/relocation.c
tests/README.md
tests/atlocal.in
tests/data/SPECS/rootfs.spec
tests/local.at
tests/rpmi.at

Unbreak installation and removal of relocatable packages that own the `/` path (like in [RHEL-28967](https://issues.redhat.com/browse/RHEL-28967)). This happened to work before #1919 but just by "accident", see the commit messages for details.
Fixes: #3173

Fix root relocation regression

---

.editorconfig
CONTRIBUTING.md

After reading the formatting instructions in [CONTRIBUTING](/CONTRIBUTING.md), I realized that the repo was crying out for an `.editorconfig` file to define the appropriate settings.
[EditorConfig](https://editorconfig.org/) enjoys _wide_ support across all text editors commonly used for coding (and plenty that aren't), either via built-in integration or through an appropriate extension/plugin. It uses an ini-style syntax to set formatting rules for various files (which can be named or wildcard-matched, typically by extension). Like `.gitignore` or other configuration files, `.editorconfig` files are hierarchical, meaning they can be installed at multiple levels in a directory tree to recursively merge rules at various levels. (A feature not currently used here.)
While the supported rules …

Add .editorconfig, and note in CONTRIBUTING doc

---

tests/rpmgeneral.at

/bin/false exits so fast that racing with the parent output order is a fifty-sixty situation at best. Use a purpose-made shell script that does a bit of IO and even sleeps a bit, which together with shell startup time should be plenty enough to guarantee stable output for most practical purposes. If it *still* bugs us after this, we can always sort the output.
Fixes: #3210

Make the second urlhelper test much less racy

---

macros.in
tests/data/SPECS/hello-auto.spec
tests/rpmbuild.at

Add file and line number to the warning.
Suppress the warning when called from %autosetup and offer -q to
suppress the warning in general.
Resolves: https://github.com/rpm-software-management/rpm/issues/3230

Better warning for %autopatch without patches

---

installplatform

Eases debugging problems when creating platform files, especially on exotic architectures

installplatform: log when a platform file is created

---

rpmio/rpmlua.c
tests/data/SPECS/filetriggers.spec
tests/rpmscript.at

Reset the Lua stack on return from rpmluaRunScript() to discard any unhandled returned data from the scriptlet. This may happen if there's eg "return 0" from a non-macro scriptlet.
We could check for a numeric return value here and treat it as an exit code, but then what to do with other kinds of returned data? Our documentation states errors in Lua scriptlets should be signaled with Lua error() function, it seems better to stick with that and avoid introducing ambiguities and incompatibilities.
Update the existing file trigger tests to cover this case.
Fixes: #3029

Fix crash on Lua file trigger exiting with return'ed data (#3029)

---

tools/rpmsign.c

Found by Coverity.
Fixes: RHEL-37564

Fix memory leak in rpmsign

---

tests/rpmgeneral.at
tests/rpmmacro.at

Both these tests (currently 12 and 90) are flaky and sometimes fail with the trailing newline at the front, eg test stderr showing:
+
warning: posix.fork(): .fork(), .exec(), .wait() and .redirect2null() are deprecated, use rpm.execute() instead
warning: posix.wait(): .fork(), .exec(), .wait() and .redirect2null() are deprecated, use rpm.execute() instead
warning: runaway fork() in Lua script
-
It's all the more bizarre since we're NOT expecting that trailing an empty line after the messages in the first place.
Let's try another trick from autotest: just grab the stderr into a file that we process in the next test. Autoconf manual says "This action is often used when it is desired to use grep to look for a substring in the output, or when the output must be post-processed to normalize …

Another attempt at stabilizing posix.fork() and url retrieve tests

---

build/parseSpec.c
tests/rpmbuild.at

The idea behind making it mandatory was that surely every real buildsystem implements a configuration step, right? Well, at least Python setuptools only has build and install, and for our purposes it certainly qualifies as a buildsystem. And where there's one, there'll be more.
Suggested-by: Miro Hrončok <miro@hroncok.cz>
Fixes: #3244

Make Buildsystem %conf section optional

---

tests/rpmbuild.at

Turns out it's not just the two fork-related tests mentioned in commit 2931cbd7b1281395d18ff88e40e024659b4cfbf5 that are unreliable, it's the bash-specific >() subshell redirect that causes those unexpected extra newlines moving around in the test-suite, and here are two more tests that occasionally now fail.
Adjust the tests to avoid that construct, which should be considered banned in the test-suite from here on...

>() redirects considered harmful, part II

---

tests/rpmmacro.at

Argh, commit 2931cbd7b1281395d18ff88e40e024659b4cfbf5 forgot to remove the redirect. This new combo also evoked new tricks: now the entire stderr output goes missing sometimes.

>() redirects considered harmful, part 1.5

---

lib/order.c

This is all a rather crude, mechanical conversion, I bet there's tonnes of further sanity + cleanup possible.
The main point here is to get rid of C-side allocations.

Refactor ordering code to use STL containers

---

build/build.c
tests/rpmbuild.at

In rpm >= 4.20 we always have to have the build directory. Commit c74ab58f081937eefd0f79af8d0310495d321864 linked its creation to --noprep but that was under the assumption of normal builds where %prep has already been executed, and we're re-entering the already created directory structure for another build stage.
--build-in-place being what it is, there's basically nothing to do at %prep so it seems natural that this should work. The linux kernel upstream packaging uses this to allow quickly building "dirty" rpm from a git repo directly, but faciliate a full regular rpmbuild from an src.rpm built this way. It seems like a reasonable thing, in fact this makes me think that --build-in-place should imply skipping %prep, but lets not go there yet...
Make sure %mkbuilddir gets run if we …

Restore --build-in-place with --noprep functionality

---

python/examples/rpm-e.py
python/examples/rpm-i.py
python/examples/rpm-q.py
python/examples/rpm-qa.py
python/examples/rpm-qi.py

See https://github.com/rpm-software-management/rpm-web/pull/54

Add real-life examples of Python RPM

---

build/build.c
build/parsePrep.c
docs/man/rpmbuild.8.md

Defining in-place builds to skip %prep suddenly makes this feature start looking supportable, because it's no longer ambiguous every which way: %setup is supposed to have all manner of side-effects that in-place builds would skip, including cd'ing to %buildsubdir. It's not possible for calling %setup to both have and not have side-effects.
Besides %setup ambiguity, %prep typically contains patch applications and those cannot be meaningfully done on in-place build because then the build is no longer repeatable.
Update the man page description to describe the new %buildsubdir based behavior, and make %prep skipped on in-place builds no matter what other options got passed. This WILL break some existing users if they rely on %prep getting partially executed, but that's how it is with …

Define --build-in-place in more clear and actually supportable way

---

lib/fsm.c
lib/rpmfi.c
tests/rpmi.at

Based on #3175 by @ffesti, main differences being:
- split the fsmOpenat() return change to a separate refactoring *and* update callers accordingly
- clean up the error handling in fsmOpenat() and ensureDir()

Report unsafe symlinks during installation as a specific case

---

docs/manual/lua.md
rpmio/lposix.c
rpmio/rpmlua.c
tests/rpmmacro.at

Turns out real-world usage needs more control than rpm.execute() delivers. This could be crammed into rpm.execute() but it'd be forward incompatible in a somewhat non-obvious way, we might just as well add a separate function for it.
Supports redirecting stdin, stdout and stderr to a given path, support for file descriptors, other actions and spawn attributes can be added later.
Fixes: #3192

Add rpm.spawn() Lua API

---

build/files.c
macros.in
tests/data/SPECS/hello-debuginfo.spec
tests/rpmbuild.at

This is @ffesti's fix from #3061, with an added fix needed for %__debug_package to be consistent enough to be used for the purpose. The benefit is that it supports both the de-facto "%global debug_package %{nil}" method in existing packages and the more formal %_enable_debug_packages switch. Delightful details in commit messages.
This fixes what must be a years old regression that prevents manual creation of -debuginfo subpackage.

Support manual debuginfo packaging again

---

rpmio/lposix.c
rpmio/lposix.h
rpmio/rpmlua.c
tests/rpmmacro.at

Commit 46bd0ed2a9e70f942e7c58f953f30a66d30a5142 did document rpm.redirect2null() as deprecated but failed to add an actual warning on it. Meaning no existing user will notice it being deprecated, unless they were also using some of the other deprecated items too.
Turn check_deprecated() into an actual function for better control, we'll have use for that later on.

Issue deprecation warnings for rpm.redirect2null() too, oops

---

tests/data/SPECS/filetriggers-prefix.spec
tests/rpmscript.at

Funnily enough, we never tested multiple prefixes.  No wonder there were some bugs lurking in the dark corners (see #3048 and #3267)!
- Add yet another test spec for triggers! (There's never enough of them)
- Have the scripts print the prefix(es) that triggered them
- Add an unused /etc prefix to test just that - an unused prefix
- Shuffle the prefixes randomly in some scripts, to make it more interesting (and to verify that the order doesn't affect anything)
- Rename the existing "basic file triggers 2" to make it better reflect its main goal (which is "runtime arguments") and to make it more consistent with the newly added one

Add tests for multiple file trigger prefixes

---

build/parseScript.c
lib/rpmtriggers.c
lib/rpmtriggers.h
tests/rpmscript.at

The first commit is just a consistency/safety thing spotted while looking for the second one, which is the main course here: fix %transfiletriggerpostun only matching on the first prefix even when the trigger has multiple.
Draft only for now due to lacking reproducer in the test-suite - we lack *any* tests for the multiple prefixes case, oops...

File trigger fixes

---

tests/Dockerfile.fedora

gdb 15.1 causes our "rpmbuild debuginfo gdb index included" to fail because no index is created. Reported to Fedora bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2310156
Related: #3278

Force older gdb version in CI due to index create regression in 15.1

---

tests/Dockerfile.fedora

The main convoluted reason for this change is that our build process primarily looks for 7za and falls back to 7z if not found. Which is all fine except when running the test-suite locally with p7zip installed, which will causes the uncompress tests to fail for no good reason.
p7zip-plugins contains the command 7z but we 7za from the main package handles this format just fine AFAICS, and is slightly smaller too so there's an additional reason to favor it in CI.

Pull in the main p7zip package to CI image instead of p7zip-plugins

---

tests/rpmsigdig.at

Using "*.secret" may cause "rpm --addsign" to fail, and the testcase is actually related only to rpm.org-rsa-2048-test.secret.
Fix https://github.com/rpm-software-management/rpm/issues/3277

Specify the private key in "rpm --addsign"

---

sign/rpmgensig.c
tests/rpmsigdig.at

More details in commit messages, executive summary:
Use the OpenPGP standard name or the configured+parsed signing command in messages as appropriate.
Refactor a bit to make that possible + add some error checks + tests while at it.
Fixes: #3274

Eliminate hardcoded GPG references from user visible messages

---

sign/rpmgensig.c

Commit 2c9ad2bbc1d00010880076cd5c73e97ffcb946ed added this new helper function for internal use and depite a missing declaration, the compiler defaulting to WITH_CXX=ON on master chugged along just fine... only until porting the same commit to a C-only branch (hello rpm-4.20.x) where it now produces a warning.

Declare signCmd() static

---

tests/data/SPECS/filetriggers-prefix.spec
tests/rpmscript.at

Commit 0988ccb53abf426587d228df5c60c4042da71999 fixed the case where any matching %transfiletriggerpostun would cause all of them to run.  Add a second trigger instance to the respective test spec to cover that.
To differentiate the instances, print the triggering prefix (this is not passed via stdin to this trigger type but we know which one it is here).
In the spirit of commit 3f1d05eae9079501ce94a106be40b9a18cd40018, add an unused prefix /opt so that /foo is the second argument.
Fixes: #3272

Add test for spurious %transfiletriggerpostun runs

---

tests/Dockerfile.fedora

The one from commit 8ce8afe4f9b303ddb347def7389676b5cf715b38 doesn't work on Fedora 39, but since dnf appears to merrily take a version range on the cli...

A more compatible kludge for #3278

---

macros.in
tests/data/SPECS/manualdebug.spec
tests/rpmbuild.at

Apparently rpmfluff creates specs that invoke the %debug_package macro directly, and commit 1a9803d0f8daf15bb706dc17783ab19589906487 broke that: when the literal unexpanded %global ends up inside a spec, it'll trigger various errors depending on the exact context.
rpmfluff is using this manual method because there's no %setup in the produced spec and so, no %buildsubdir is defined and so, no debuginfo packages produced. Conditionalize writing the escaped %global on %buildsubdir being defined, a condition where automatic debuginfo packages normally would be generated anyhow. It may not be ideal but I think it'll do for now.
Fixes: #3290

Fix regression preventing manual %debug_package usage

---

CMakeLists.txt
docs/man/rpmsign.8.md
macros.in
sign/rpmgensig.c
tests/Dockerfile.fedora
tests/rpmsigdig.at
tools/rpmsign.c

Add new %_openpgp_sign macro to select between implementations, currently "gpg" for GnuPG and "sq" for Sequoia are supported. Also introduced is a new macro for specifying the signing key in the configuration: %_openpgp_signer. Whereas GnuPG allows arbitrary string match to be used for key selection, Sequoia requires a keyid or fingerprint to be specified. So %_gpg_name is an ill-fitting name for the configuration, both for being GPG-centric and "name" being misleading. Explicitly specifying the keyid/fingerprint is less ambiguous anyhow.
Minimally preserve backwards compatibility for %_gpg_name (the only configuration people normally need) by setting %_openpgp_signer to %_gpg_name by default, and still defaulting to the gpg implementation.
Update rpmsign manual to cover the new macros …

Support signing with Sequoia through a simple macro switch

---

scripts/brp-remove-la-files
tests/CMakeLists.txt
tests/rpmbrp.at

As we check for file contents delete symlink before looking at regular files.
Resolves: #3304

brp-remove-la-files: Remove symlinks, too

---

build/policies.c

Fix memleak when process policies

Fix memleak when process policies

---

docs/man/rpm-plugin-unshare.8.md
plugins/unshare.c

Disable private mounts in chroot'ed operation in the unshare plugin
mount("/", "/", NULL, MS_REC | MS_PRIVATE, NULL) inside a chroot fails with EINVAL. Apparently this is because "/" inside the chroot is not (necessarily) an actual mount point and ... then it starts getting more complicated. It should be possible to handle but not something we want to attempt just before a release candidate.
Related: #3187

Disable private mounts in chroot'ed operation in the unshare plugin

---

CMakeLists.txt

Jan Engelheart [pointed out](https://github.com/rpm-software-management/rpm/discussions/2983#discussioncomment-10724355) that with -fno-exceptions `new` failing will return a nullptr. Which seems fine until you realize that all of rpm is built on the notion that allocations never fail, they terminate the program instead. Only with the C++ refactorings, a significant portion of the code is now relying on `new` and not checking its return. Ooops.
Uncaught exceptions will terminate an unsuspecting program anyhow, let that happen. We'll be adding catches over time...
Besides allocations, not being able to deal with exceptions in the C++ side of things would put us at severe handicap all over the place - they are an essential part of the language and STL.

Enable C++ exceptions on the codebase

---

CONTRIBUTING.md
docs/CMakeLists.txt
docs/manual/about.md
docs/manual/index.md
docs/manual/philosophy.md

Reference Manual: RPM's Philosophy

---

include/rpm/rpmkeyring.h
lib/rpmvs.c
lib/rpmvs.h
rpmio/rpmkeyring.c
rpmio/rpmpgp.c
tests/rpmi.at
tests/rpmquery.at
tests/rpmsigdig.at
tests/rpmvfylevel.at

This does not yet adjust the test cases. So 198 209 216 217 220 221 222 223 226 227 are failing due to unexpected key finger prints.
Can probably be used in combination with #3292 as this does not touch the keyid output. Although we might want to skip the key id for verified signatures.
Related: #2403

Add Key Fingerprints to rpmsinfoMsg()

---

docs/manual/macros.md
docs/manual/spec.md

We speak about (built-in) macros and their expansion in various parts of the spec page but never care to actually mention to the reader that there's a dedicated page on macro syntax.  Add a bunch of links where appropriate, and since one of those places mentions %dnl, also add %dnl to the macro page (this used to be there, just got missed in the reformatting commit 015c829c7670c606b952bb34ef69debb60f5985a).
Fixes: #3331

Link to macro syntax page from spec syntax page

---

lib/rpmts.cc
tests/rpmsigdig.at

This was previously papered over in the test-suite.

Ensure the keyring directory exists when importing to fs keyring

---

docs/man/rpmkeys.8.md
include/rpm/rpmkeyring.h
include/rpm/rpmtypes.h
rpmio/rpmkeyring.cc
tests/rpmdb.at
tests/rpmsigdig.at
tools/rpmkeys.cc

Use keyring to implement rpmkeys --list
This changes the output of keys --list to show the full fingerprint. It
also requires the use of the fingerprint or full key ID for querying
specific keys.
Note that this only allows fingerprints or long keyids as identifier. So it kinda assumes #2403 fixed.

Use keyring to implement rpmkeys --list

---

docs/man/rpmsort.8.md

In the EXAMPLES section the backslash and apostrophe need escaping to produce command that is actually usable.

Fix formatting in the rpmsort man page.

---

lib/backend/dbi.hh
lib/header.cc
lib/psm.cc
lib/rpmdb.cc
lib/rpmds.cc
lib/rpmfi.cc
lib/rpmprob.cc
lib/rpmps.cc
lib/rpmts.cc
lib/rpmts_internal.hh
rpmio/rpmio.cc
rpmio/rpmkeyring.cc
rpmio/rpmstrpool.cc

Throughout the code base reference counting is done in a thread-unsave way. A few places use the content lock (aka mutex) to also protect the reference counter. This is wrong and complicates freeing interconnected data structures. This lock should only protect the content of the instance.
Turn all nrefs members into atomic_int so they are thread-save themselves.
Make sure to only use ++ and -- operators and avoid non atomic combinations of reading and writing. Drop all the static *Unlink functions that are involved in this.
Make sure the data lock is not aquired while updating the nrefs members.
Technically the *Free() functions should *Link() the instance after the ref count has reached 0 and the decision to free it has been made. Otherwise the cleanup code linking and freeing to will …

Turn nrefs into atomic_int

---

tests/rpmdb.at
tests/rpmsigdig.at
tools/rpmkeys.cc

...any more than "ls" in an empty directory is. We should fix this in 4.20 too before people start making assumptions about this behavior.

Having no keys imported is not an error

---

include/rpm/rpmts.h
lib/rpmts.cc
tests/rpmdb.at
tests/rpmsigdig.at
tools/rpmkeys.cc

This is a follow up to #3369  and #3368.
The new cliMatchPubkeys() will become handy for #3366, too

Pass rpmPubkey instance to rpmtxnDeletePubkey

---

include/rpm/rpmkeyring.h
lib/rpmts.cc
lib/rpmvs.cc
rpmio/rpmkeyring.cc
tools/rpmkeys.cc

Store both the keyid and fingerprint in hex format inside the key, so we can return const pointers to them.
Makes them nicer to use from C.

Make rpmPubkeyFingerprintAsHex() and rpmPubkeyKeyIDAsHex() nicer to use from C

---

CMakeLists.txt
INSTALL
tests/Dockerfile.fedora

Despite being bound to "make check" and reasonably fast, our tests sit at least one level above what you'd normally call "self tests" or "unit tests" and require external container tooling to run.
Therefore, disable them by default, they're only really useful for RPM development, certainly not for building RPM itself, e.g. from a release tarball.  Update the INSTALL file accordigly.
Fixes: #3388

Default to test-suite disabled in cmake

---

lib/fsm.cc
tests/data/SPECS/pamupdate.spec
tests/rpmi.at

On install/update, most files are laid down with a temporary suffix and if the update fails, removing those at the end of the loop is the right thing to do. However FA_TOUCH'ed files were already there, we only update their metadata, and we better not remove them!
AFAICS this all versions since rpm >= 4.14 in one way or the other. If %_minimize_writes is enabled then it affects way more than just unmodified config files.
The test is a simplified version of pam update failing in the original report.
Fixes: RHEL-54386
Fixes: #3284

Fix FA_TOUCH'ed files getting removed on failed update

---

lib/package.cc
lib/rpmvs.cc
lib/rpmvs.hh
tests/rpmsigdig.at

Just use the actual hex string, it's what the user needs to see and makes no difference to the computer. Add a test as well.
Fixes: #3333

Use full keyid for the unknown keyid warning message tracking

---

lib/CMakeLists.txt
lib/keystore.cc
lib/keystore.hh
lib/rpmts.cc
lib/rpmts_internal.hh

Details in commit messages, but short summary is that this is all just refactoring prep-work for #3342. 
The added API of keystore Load, Import and Delete functions sort of achieves the abstraction but this exact API shouldn't be seen as any final state of affairs, it's just a milestone along the road.
This looks big but the actual code changes are rather minimal, on purpose. Once this lands, the next steps will be isolating the header fubar into the rpmdb keystore and making the keystore an actual type (think object) instead of just being ifs around keyringtype number.

Refactor keystore operations to a separate source + internal API

---

lib/keystore.cc
lib/rpmts.cc
rpmio/rpmkeyring.cc

Remove all other subkey handling code
Inline the remaining few lines of keyringAdd in keystore.cc
This slightly changes the DEBUG messages as the keyring does not have
access to the origin of the keys. So rpmtsLoadKeyringFrom* still gives
the location the keys came from while the keyring only lists the
fingerprint of the primary keys and the number for the sub keys.
This changes the return value of rpmKeystoreLoad to the number of
primary keys and no longer accounts for the subkeys.
Subkeys are covered by multiple test already - including merging a newer
key. So this does not add additional tests.
Resolves: #3350

Handle subkeys in rpmKeyringModify

---

rpmio/macro.cc
tests/rpmmacro.at

Make sure (text editor) backup files, such as those with the tilde (~) at the end, aren't processed by our macrofiles globs.  These can appear while editing a macro file in place and may result in confusing behavior where an old version of a macro overrides the one being written, like seen in the ticket #3373.
Rather than enumerating any specific suffixes, just mandate that macro files end with alphanumerics.  That's more of a name sanity check than anything but fits the bill here.

Require macro filenames to end in alphanum char

---

lib/keystore.cc
tests/rpmsigdig.at

Pass pubkeys down to the keystore on import, and let the keystore handle the actual format. For rpmdb keystore this remains the header, so it's a no-op there, but on the fs keystore we drop the trailing "time or something" hex garbage from the filename because we no longer have it at hand but also because it's just not relevant for anything. The key load glob is relaxed enough that we still pick the old format keys too.
Related: #3342

Drill pubkeys one level deeper into the keystore APIs

---

lib/keystore.cc
lib/keystore.hh
lib/rpmts.cc
lib/rpmts_internal.hh

The beef is in the second commit, the other two are just minor refactoring (so yeah there *was* one more of those :smile: )
Fixes: #3342

Implement an abstract keystore class + port fs + rpmdb keystores to it

---

build/parseSpec.cc
tests/rpmbuild.at

Dynamic spec parsing emits "Reading <path>" messages to make it clear something out of the ordinary is going on, but this is undesireable on rpmspeq queries. Luckily there's a trivial solution: rpmbuild where you want these messages runs in verbose mode by default whereas rpmspec does not. So just moving the message to INFO level does exactly the right thing in both the above cases and as an added bonus, rpmbuild --quiet too. Add a test to go.
Fies: #3413

Silence extra output on rpmspeq query on Buildsystem specs

---

lib/fprint.cc

One of the busiest functions in rpm was getting passed a new copy of a big unordered_map on each call during fingerprinting because "somebody" forgot a & in commit 08a6a5e848f007c2e8d83fc1df8712d1a43229f4. This isn't even noticeable in the test-suite or daily "update a few dozen packages" operation but when attempting to install/update a few thousand packages dragged this little buglet to the light...
Why oh why C++ do you behave in such an idiotic manner in the face of stupid mistakes. Raw pointers at least give you a compiler error.

Fix a horrible performance regression caused by missing &

---

lib/package.cc
lib/rpmts.cc
rpmio/rpmlog.cc
rpmio/rpmlog_internal.hh
tests/rpmpython.at

These are internal only for now to allow us gain soem more confidence on the design.
rpmlogOnce allows showing a log message only once. rpmlogReset allows purging the list of known message keys for a given domain. This allows for different live times e.g. per transaction or per package.
Use in handleHdrVS. This does not add a new test case but various existing test cases fail when the NOKEY message is omited or shown more than once. The code uses the pointer to the rpmts object as a domain and resets it when the rpmts is freed.
Resolves: #3336
Resolves: #3395

Add rpmlogOnce() and rpmlogReset()

---

lib/rpmvs.cc
rpmio/rpmpgp.cc
tests/rpmi.at
tests/rpmpython.at
tests/rpmquery.at
tests/rpmsigdig.at
tests/rpmvfylevel.at

The signature and key related messages are a historical mess of inconsistency, we have at least the following in closely related messages that happen under slightly different circumstances:
- Header V4 RSA/SHA256 Signature
- RSA signature: NOTFOUND
- signatures OK
- key ID
- Key Fingerprint
Just use lower case consistently for everything but acronyms, so the above becomes
- Header V4 RSA/SHA256 signature
- RSA signature: NOTFOUND
- signatures OK
- key ID
- key fingerprint
This will no doubt break somebody's fine-tuned script but we're breaking them in 6.0 anyhow so this is the right time for this kind of cleanup.

Use consistent case in signature and key messages

---

rpmpopt.in
tests/rpmsigdig.at

Commit d99186f2ef6fc0dfaaefe599a98492a84fd18940 failed to update the popt alias to the new macro. So --key-id worked only if you hadn't set %_openpgp_sign_id in your rpm macro config - the prime case for wanting to use --key-id to override that choice. Doh.  Just goes to show what you don't test, really is broken by definition...

Fix rpmsign --key-id regression

---

tools/rpmdump.cc

`rpmdump` prints the OS type field as architecture type.  
Print the correct value.

fix rpmdump output

---

CMakeLists.txt
rpmio/rpmlog.cc

Commit 547ba089313be46861fe1f5b21fbe887205697c2 broke the build with -Wformat-security. Add the trivial fix and ensure it stays that way by adding -Wformat-security to our normal build flags.

Fix build regression with -Wformat-security

---

lib/rpmvs.cc
tests/rpmi.at
tests/rpmpython.at
tests/rpmquery.at
tests/rpmsigdig.at
tests/rpmvfylevel.at

This adds the following to verbose mode signature verification:
- OpenPGP string to all signatures (these are not raw DSA/RSA/etc but OpenPGP)
- Header+payload signatures and digests are now prefixed Legacy to make it clear what they are
Both needed to pave way for the multiple signature stuff.

Another signature verification verbose message update

---

tests/rpmsigdig.at

This indeed does work with the fs backend nowadays. Since 42985d54824fc518b203aebfaf12e1daa3bb994a actually.

Use rpmkeys --list in test cases

---

docs/man/rpmkeys.8.md

Drop all references to pre-historical Red Hat keys, short key-ids and gpg-pubkey packages. Use the term fingerprint consistently everywhere. Add a brief explanation of the --list format and usage example for --export too.

Fixes + cleanups to rpmkeys manual

---

lib/keystore.cc
lib/keystore.hh
lib/rpmts.cc
tests/rpmsigdig.at

Refactor code from the fs backend into shared helper functions
This does implement the layout on the file system and the write lock of the openpgp.cert.d proposal according to
https://www.ietf.org/archive/id/draft-nwjw-openpgp-cert-d-00.html but not the Trust root, Petname mapping or Trusted introducers.
This still is a mess of C and C++ style strings that we want to clean up later by adding C++ string based path handling and may be using the filesystem C++ library.
Resolves:  #3341

Implement openpgp.cert.d based keystore

---

tests/Dockerfile.fedora

* Drop support for F39
* Fix "unpack error" in subsequent dnf transactions

Minor Dockerfile fixes

---

build/files.cc
include/rpm/rpmfileutil.h
lib/relocation.cc
rpmio/macro.cc
rpmio/rpmfileutil.cc
rpmio/rpmmacro_internal.hh

The interesting part of this PR are new rpm::join_path(), rpm::expand_path() and rpm::normalize_path() functions which are more powerful C++ native counterparts of rpmGenPath(), rpmGetPath() and rpmCleanPath(), and hopefully with more meaningful names too. 
rpmGenPath() and rpmGetPath() use the C++ versions internally now, which "proves" they work as promised. rpmCleanPath() can't do so because it expects to manipulate the C string buffer passed to it. We'll deprecate it as soon as we get rid of it.
The latter commits replace a few uses of rpmCleanPath() and related C-side functions with C++ native versions to further prove these work as intended, but technically they wouldn't need to be in this PR.

Add internal C++ native path manipulation functions

---

tests/atlocal.in
tests/data/macros.testenv
tests/local.at
tests/mktree.common
tests/pinned/common/buildrepr.sh
tests/rpmbuild.at
tests/rpmdb.at
tests/rpmi.at
tests/rpmmacro.at
tests/rpmquery.at
tests/rpmspec.at
tests/rpmvercmp.at

Details in commit messages, but short summary: move the test-suite rpm configuration from --define's to a permanent file, and setup_env calls from the wrapper functions to RPMTEST_CHECK*(). As a result, run() becomes entirely redundant can be removed - that is, for a large class of tests, you can just use commands directly without any extra fubar.

Eliminate the need for run() wrapper in the test-suite

---

lib/backend/sqlite.cc
tests/rpmdb.at

Check if there is 20MB in free pages and then execute a VACUUM command. The threshold can be controlled by the _sqlite_vacuum macro. Don't add this to the macros file on purpose as we don't want people to get involved with such details. Here it is mainly used for testing.
Using a 20 MB threshold should prevent the vacuuming to happend too often while still triggering after large transactions. As we install new headers first and then remove the old ones transactions leave behind large amounts of free pages.
We do not use PRAGMA auto_vacuum here as it does not defrag the database and only frees empty pages. So it still requires running VACUUM from time to time. Freeing the empty pages would get rid of the condition we use here for running VACUUM.
Using pure C for the macro expansion on …

Vacuum the sqlite rpmdb if necessary

---

rpmio/macro.cc
rpmio/rpmmacro_internal.hh

While we can't change the C API there is really no reason to add a new 32 bit API. Changing now while it is still internal.

Make macros::expand_numeric return int64_t

---

COPYING

The postal address of the FSF in there is no longer valid. Use license files currently available at
https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt https://www.gnu.org/licenses/old-licenses/lgpl-2.0.txt
There are minor formatting changes. The license the code is under is not changed.
Resolves: #3456

Update GPL and LGPL in COPYING

---

tests/Dockerfile.fedora

We basically always want to run the latest stable release, but the newer the release the more update churn there is, and that sort of instability is bad for CI. To counter that, disable updates by default. If and when we need specific updates to components, we now do it explicitly. This seems like the best of both worlds really.
Technically this is two different changes, one to bump the Fedora version and another to disable updates, but if they are separated then time goes backwards for that one commit so I think it's better to just have this as one commit.

Update CI to Fedora 41, disable updates by default

---

CMakeLists.txt

Another cmake fallout - we even have the define in config.h.in but the actual test was missing, causing us to never use the compression aware dwelf_elf_begin() version.
The only reproducer I'm aware of is a kernel module, and we don't want to pull in the huge kernel-devel to the test CI for this. Manually verified that cmake looks for and finds it:
-- Looking for dwelf_elf_begin in dw
-- Looking for dwelf_elf_begin in dw - found
And building kernel module, before:
$ rpm -qpl /home/pmatilai/rpmbuild/RPMS/x86_64/kmod-lkm_example-1.0-1.x86_64.rpm /lib/modules/6.11.8-300.fc41.x86_64/lkm_example/lkm_example.ko.xz
After:
$ rpm -qpl /home/pmatilai/rpmbuild/RPMS/x86_64/kmod-lkm_example-1.0-1.x86_64.rpm /lib/modules/6.11.8-300.fc41.x86_64/lkm_example/lkm_example.ko.xz /usr/lib/.build-id …

Fix regression on build-id generation from compressed ELF files

---

tests/mktree.common
tests/rpmsigdig.at

We were ignoring stderr on all rpmsign tests with Sequoia because of very noisy error messages from gpg-connect-agent that were not relevant to the functionality at all. Turns out these errors were caused by missing ~/.gnupg directory, for whatever reason the agent doesn't create it automatically. Make sure it's present on the test-image root account.

Listen to stderr on Sequoia signing tests too

---

macros.in

GnuPG defaults to binary so there was no option to copy/translate to Sequoia-sq, so this behavior difference got missed. ASCII-armored would work just as well, but lets be consistent.

Tell sequoia-sq to create binary signatures too

---

rpmio/macro.cc
rpmio/rpmmacro_internal.hh

The initial round left a lot of const char * arguments around, and trying to use this stuff, you bang your head into them sooner than later. 
These are rather small and straightforward patches and could be probaby squashed into larger commits, but should be at least easy to review in this format.
One noteworthy exception (noted also in the commit message) is the parametric macro options that can't be converted to a string just like that because NULL and "" are two entirely different meanings there (NULL option is a non-parametric macro and "" is a parametric macro that takes no options)

Stringify the rest of the internal c++ macro API

---

macros.in
sign/rpmgensig.cc

It's not any less code, but gives us much better control over how they're called, eliminating the need for global temporary macros for passing what really are command arguments.
No functional change, but paves way for future programmatic switches such as perhaps binary/ascii signatures.
This is of course incompatible with folks who have their own custom %__gpg_sign_cmd from the past, recipes for these have unfortunately commonly floated around the internet as "necessary" for signing. These are double-underscore macros, people messing with those had better know what they're doing.

Make the signing macros parametric

---

include/rpm/rpmcrypto.h
include/rpm/rpmpgp.h
macros.in
rpmio/digest_libgcrypt.cc
rpmio/digest_openssl.cc
tests/rpmbuild.at

Sequoia doesn't yet support SHA3 so we need to skip it in the default CI tests. Tests verified locally with libgrypt and openssl builds.
Fixes: #3436

Add support for SHA3-256 and SHA3-512

---

lib/keystore.cc
lib/rpmte.cc
tests/rpmpython.at
tests/rpmsigdig.at

We had an exception for public key packages in rpmte. With those now being handled in the keystore without going through the transaction machinery this is no longer needed. This also prevents people from just contrsucting their own pubkey packages and install them.
Resolves: #3344

Don't allow installing packages without ARCH or OS

---

docs/manual/users_and_groups.md
macros.in
scripts/sysusers.sh
tests/data/SPECS/klang.spec
tests/rpmi.at

systemd 257 defines a new modifier ! for u entries that locks the account by setting it as expired.
See https://github.com/systemd/systemd/commit/2ec7977e1b100c1717d95417e6d825fbf939f7b3
Resolves: #3450

Support new u! command in sysusers files

---

lib/psm.cc
lib/rpminstall.cc
sign/rpmgensig.cc
tests/rpmdevel.at
tests/rpmi.at
tests/rpmsigdig.at

Don't add file signatures to source packages and if they happen to be present (i.e. built with an older rpm version), ignore them when unpacking (by not running plugins at all for source packages).
AC (taken from [original bug](https://bugzilla.redhat.com/show_bug.cgi?id=2316785)):
- IMA signature don't make any sense on src.rpm files - so Fedora shouldn't be signing them, and rpm shouldn't let them
- Even if the assertion above fails and you somehow end up with an src.rpm with IMA signatures on it, rpm should not barf up on it

Exempt src.rpm packages from file signature business

---

scripts/brp-strip
scripts/brp-strip-static-archive

By default, the build root contains NAME-VERSION-RELEASE.ARCH. Some of these may contain characters that are not taken as plain characters when interpreting a regex, such as "." or "+".
This may lead to a situation where files in /usr/lib/debug are stripped, making them useless for debugging. This is because the command to strip debug information interpreted part of the $RPM_BUILD_ROOT as part of a regex.
To fix this, first change to the build root directory, and run the find command relative to that directory, ensuring we don't have to make the build root part of the regex.

Fix brp-strip when using regex-unsafe build root

---

docs/man/index.md

Drop translations that are long gone (4df74a96).
Reorder alphabetically (mostly)
Add rpmlua.8.md, rpm-plugin-dbus-announce.8.md and rpm-plugin-unshare.8.md
Resolves: #3491

Update index of man pages

---

build/build.cc
macros.in
tests/rpmbuild.at
tools/rpmbuild.cc

There are a bunch of flaws here, kinda separate items but as they were all introduced in a single commit it probably makes sense to address the mess as one too:
There was a missing 'break' causing %mkbuilddir to use the templates of %prep, which masks the fact that the %__spec_builddir_* stuff all set to %{nil} doesn't work, which causes us to try to 'cd' to the build directory that we're about to create in that %mkbuilddir. It only happens to work because I forgot to update the rpmMkdirs() call in rpmbuild to create %_top_builddir instead of %_builddir. Oof.
The only obvious evidence of all that fubar was that rpmbuild -bs started leaving an empty build directory behind.
Reported-by: Fabio Valentini <decathorpe@gmail.com>
Fixes: #3382

Fix regression causing a build directory left behind on rpmbuild -bs

---

CMakeLists.txt
plugins/CMakeLists.txt

We have in macros.in:
%__plugindir          @RPM_PLUGINDIR@
This means, if RPM_PLUGINDIR is not set, %__plugindir will be empty. This in turn results in error message when running 'dnf'.
e.g.,
dnf --help >/dev/null
error: /usr/lib64/rpm/macros: line 1183: Macro %__plugindir has empty body error: /usr/lib64/rpm/macros: line 1183: Macro %__plugindir has empty body
So we should move this directory setting into the top level CMakeLists.txt.

Set RPM_PLUGINDIR in top level CMakeLists.txt

---

.github/workflows/linux.yml

We need to have control over our CI environment - we lock Fedora to a certain version without updates, yet the underlying Ubuntu image has been floating and causing trouble every now and then. Like just now, with ubuntu-latest moving from 22.04 to 24.04 where sudo is somehow broken inside our test-suite and causing totally unrelated PR's to fail with
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
Lock the version to Ubuntu 22.04 for now, we'll need to eventually figure what the issue is but these things need to happen on our terms.

Lock the GitHub CI runner to a specific Ubuntu version

---

docs/man/rpm-misc.8.md
docs/man/rpm.8.md
docs/man/rpmbuild.8.md
docs/man/rpmdb.8.md
docs/man/rpmsign.8.md
docs/man/rpmspec.8.md

The renderer of GitHub pages - that we use for the in-tree documentation
- gets confused if tripple asterix are used near white space or line breaks.
Fix the formatting by moving the spaces or line breaks inbetween.
Resolves: #3502

Fix formatting in man pages

---

rpmio/rpmfileutil.cc
rpmio/rpmio.cc

Fix race condition in rpmioMkpath
The previous implementation did stat the directory and created it if not
there. This allowed for a race condition where other rpm instances could
create the directory inbetween. This was observed in the wild for
%{_tmppath}.
Do create the directory unconditionally and if that fails see if the
directory is there already.
Not adding a test case as rpmioMkpath is heavily used all over the the
code base and tests for race conditions don't really fit in the test suite.
Resolves: https://github.com/rpm-software-management/rpm/issues/3508

Fix race condition in rpmioMkpath

---

docs/man/rpm-misc.8.md
docs/man/rpm-plugin-audit.8.md
docs/man/rpm-plugin-prioreset.8.md
docs/man/rpm-plugin-selinux.8.md
docs/man/rpm-plugin-syslog.8.md
docs/man/rpm-plugin-systemd-inhibit.8.md
docs/man/rpm-plugins.8.md
docs/man/rpm.8.md
docs/man/rpm2archive.8.md
docs/man/rpmbuild.8.md
docs/man/rpmdb.8.md
docs/man/rpmgraph.8.md
docs/man/rpmkeys.8.md
docs/man/rpmlua.8.md
docs/man/rpmsign.8.md
docs/man/rpmsort.8.md
docs/man/rpmspec.8.md

This is based on a list provided by the manpage-l10n project
(https://manpages-l10n-team.pages.debian.net/manpages-l10n/) in https://github.com/rpm-software-management/rpm/issues/3511.
This is mainly formatting and punctuation issues, referencing the proper
man pages and a few typos and minor re-wordings.
Resolves: https://github.com/rpm-software-management/rpm/issues/3511

Fix various issues with the man pages

---

docs/manual/spec.md

Fixes #3384 
This was written from the perspective of reference manual reader, i.e. trying to document how all the things actual work together. Since various combinations, while possible, do not make much sense, some "X is not recommended" clauses are included. Please instruct if those are not in line with actual recommendations from the RPM team.

Document ways to declare sources and patches

---

plugins/ima.c
tests/rpmsigdig.at

This lets installations succeed even if the ima plugin happens to be installed in a container, where IMA isn't supported. We don't know it failure was because of a container so this is far from ideal, but failing an install just because some package dragged in the ima plugin as a dependency is worse.
Counter-intuitively, the test verifies that the IMA xattr didn't get installed because that's the expected result, when inside a container.
Fixes: #3234
The first commits are tweaks to a couple of small issues I ran into when looking at this.

Ignore EPERM when setting IMA signature xattr

---

docs/manual/autosetup.md
docs/manual/index.md
docs/manual/spec.md

Add links to subtopics to Spec page in manual

---

macros.in
tests/Dockerfile.fedora
tests/rpmsigdig.at

There are quite a few changes in the CLI of sq 1.0 (this was expected) that we'll just need to adapt to now.
The cli update itself is straightforward enough, the tricky part is getting the update pulled in because we need to do it in a separate transaction and at that point, rpm-plugin-ima has been pulled in and breaks installs in a rootless container. Thankfully since ce7210d5841389f866f66ae700817bee7fb10e9d we can just blast the IMA plugin config file away for now.
Fixes: #3506

Update sequoia-sq to 1.0 for CLI switch stability

---

tests/data/macros.testenv
tests/mktree.common
tests/rpmdb.at
tests/rpmi.at
tests/rpmmacro.at
tests/rpmsigdig.at

This is the second half of #3524 rebased on top of #3525. It's all pretty straightforward now, the tricky part turned out to be #3525.
Fixes: #3521

Move test-suite configuration out of root's ~/.rpmmacros

---

tests/CMakeLists.txt
tests/mktree.common
tests/mktree.oci
tests/mktree.rootfs
tests/setup.sh

Commit c17cc691569040fdfd741c2a423e9efecde181b0 introduced an `rpmdb --initdb` call into test-suite make_install() but at that point, it's actually the rpm from the host, which is NOT what we want.
Split the image preparation to two stages: install, which runs from the outside and basically just copies data into the image, and setup which runs from inside the image. For this we need some extra container gymnastics.
Fixes: #3530

Run test-suite environment setup inside the image

---

.gitignore
tests/CMakeLists.txt
tests/README.md
tests/mktree.oci

* Use build-local "tags" instead of tagging all images as "rpm".
* Fix constant base image rebuilds when switching back and forth between branches
Details in commit messages.

Make test image caching saner

---

macros.in
tests/rpmsigdig.at

--homedir is a gnupg thing, sq uses --home. Change one of the tests to utilize %_sq_path to make sure it works and stays that way.

Fix sq signing using invalid cli switch if %_sq_path is defined

---

tests/README.md
tests/local.at
tests/rpmbrp.at
tests/rpmbuild.at
tests/rpmbuildid.at
tests/rpmconfig.at
tests/rpmconfig2.at
tests/rpmconfig3.at
tests/rpmconflict.at
tests/rpmdb.at
tests/rpmdeps.at
tests/rpmdevel.at
tests/rpme.at
tests/rpmgeneral.at
tests/rpmi.at
tests/rpmio.at
tests/rpmmacro.at
tests/rpmorder.at
tests/rpmpgp.at
tests/rpmpkgfmt.at
tests/rpmpython.at
tests/rpmquery.at
tests/rpmreplace.at
tests/rpmscript.at
tests/rpmsigdig.at
tests/rpmspec.at
tests/rpmvercmp.at
tests/rpmverify.at
tests/rpmvfylevel.at

More details in commits but addressing various items from #2773:
- rename RPMTEST_SETUP to RPMTEST_INIT to free the name
- introduce RPMTEST_SETUP as a wrapper to AT_SETUP and use it everywhere, to pair with RPMTEST_CLEANUP and gives a central place to control rpm-specifics of test setup
- remove now redundant rpmdb reinitializations from the test by making rpmdb reset explicitly called when absolutely needed
Besides making for more consistent names and allowing future consolidation, gives a nice speed boost (from 2m 50s to 2m 20s on my laptop)

Consistify and cleanup test-suite setup macros

---

tests/README.md
tests/local.at
tests/rpmbuild.at
tests/rpmbuildid.at
tests/rpmconfig.at
tests/rpmconfig2.at
tests/rpmconfig3.at
tests/rpmconflict.at
tests/rpmdb.at
tests/rpmdeps.at
tests/rpmdevel.at
tests/rpme.at
tests/rpmgeneral.at
tests/rpmi.at
tests/rpmio.at
tests/rpmmacro.at
tests/rpmorder.at
tests/rpmpgp.at
tests/rpmpkgfmt.at
tests/rpmpython.at
tests/rpmquery.at
tests/rpmreplace.at
tests/rpmscript.at
tests/rpmsigdig.at
tests/rpmspec.at
tests/rpmverify.at
tests/rpmvfylevel.at

See commits for details, but the main deal here is to reduce the boilerplate needed for tests and nudge test-authors towards not using (expensive) mutable snapshots unnecessarily.

Eliminate the need for explicit RPMTEST_INIT

---

tests/data/macros.testenv
tests/setup.sh

Somehow missed this opportunity in add3e0676b17840d088de221fee3bf9a721dbe92. With this and 78c21f4ed1e03cbf876247b1dcc6d4542d94d0c9, we really now have a central place to configure system-wide macros in a prefix independent manner.

Move test-suite dbpath setup to macros.testenv too

---

tests/README.md
tests/atlocal.in
tests/rpmdb.at
tests/rpmi.at

We don't need or want any of the sudo fanciness and privilege elevation here: we're already root inside the container and just want to run things as a different user. runuser is more than adequate for this purpose.
One such peculiarity is that apparently sudo re-expands its command, so \$PWD got evaluated to the PWD of the new shell. runuser does no such thing, but we can just as well hardcode a directory, $PWD is nothing special in this case.
Consolidate the lone runuser rpmdb export test to use runroot_user too now that it can.

Use runuser instead of sudo for test-suite user changes

---

.github/workflows/linux.yml

The newer environment would be welcome if we can use it now that our sudo usage is gone.
Related to: #3377

Bump CI runner to Ubuntu 24.04

---

tests/mktree.common
tests/setup.sh

This can do dangerous stuff, its better not to even pretend it can be run from outside the image. Add a safeguard and drop the pretense of $DESTDIR support. Makes it much nicer too.

Ensure tests/setup.sh is only ever run inside the test-image

---

lib/rpmte.cc

Get rid of requires_ hack to avoid collision with requires keyword.
Also the dependencies are looked up by tag anyway. No need for a case statements when we can use a container instead.
Related: #3537
Related: #3518

rpmte: Move dependencies into an unordered_map

---

lib/rpmte.cc

This is only over complicated as there is no common way to initialize them all.
Related: #3538
Rational: https://github.com/rpm-software-management/rpm/pull/3538#discussion_r1944258458

rpmte: Don't use list of tags

---

tests/rpmpython.at

This test failed when Python is set to show all warnings, e.g. with -Xdev option for debugging.
```
--- /dev/null	2025-02-06 08:39:24.294002404 +0000
+++ /srv/rpmtests.dir/at-groups/124/stderr	2025-02-13 12:36:33.848737564 +0000
@@ -0,0 +1 @@
+<sys>:0: PendingDeprecationWarning: use len(ds) instead
124. rpmpython.at:620: 124. dependency sets 2 (rpmpython.at:620): FAILED (rpmpython.at:620)
```
Also, it looks like `myprint` in Python tests isn't necessary anymore - it was needed in Python 2 era (Python's native `print` function has already been used in `archscore` test); but I haven't touched it here - if desired, I can send another patch with a rename of all the other tests.

Python tests: Check that ds.Count emits deprecation warning

---

build/CMakeLists.txt
build/pack.cc
tests/data/macros.testenv
tests/local.at
tests/pinned/common/buildrepr.sh
tests/rpmquery.at
tests/rpmsigdig.at
tests/setup.sh

This is obviously only an enabler for automatic signing. The other half of the equation is automatically setting it up, but that's another ticket (#3522). This lets us at least manually enable automatic signing in the test-suite, which in turn is a pre-requisite for enabling enforcing signature checking by default (#1573).
Set up auto-signing inside the test-suite throughout, using a freshly generated key for each run. With the exception of the reproducibility tests where this would be harmful.
This is a rather primitive thing in this state - ideally the signing would happen in parallel, but as the signing code relies heavily on macro manipulation, that's a much bigger task for some other time. Also I think we'd rather use an rpm specific keyring for the automatic signing,  but that …

Support automatic signing on build when %_openpgp_autosign_id is set

---

.github/workflows/artifact.yml

We want the official tarballs to be made in a hermetic environment (i.e. not on a developer's workstation) and have a stable checksum, and GitHub releases alone would only give us the former as the automatic download links aren't guaranteed to be stable [1].
Thus, define a workflow that runs when a GitHub release is published, makes a tarball, an accompanying checksum file, and attaches both to that release as additional assets.  This is also what GitHub recommends [1] if stability is desired.
Note that this YAML file needs to be on the branch we're releasing from, and we currently don't release from master, so the file doesn't have any effect there.  Yet, we want to keep a "canonical" version of the file on master and only cherry pick it (and any future changes) onto the stable branches. …

Generate release tarballs via GitHub Actions

---

macros.in
tests/pinned/common/rpmsigdig.sh
tests/rpmconflict.at
tests/rpmdb.at
tests/rpmdeps.at
tests/rpme.at
tests/rpmi.at
tests/rpmpython.at
tests/rpmquery.at
tests/rpmscript.at
tests/rpmsigdig.at
tests/rpmverify.at

This is all about tediously revising various tests to avoid certain assumptions, and the rest is updating test results to match the new expectations. Some --nosignature disablers added on tests where we know it's unsigned and the extra output from signature checking is not relevant for the tests.
Fixes: #1573

Enable enforcing signature checking by default

---

docs/man/gendiff.1.md
docs/man/rpm.8.md
docs/man/rpm2archive.8.md
docs/man/rpm2cpio.8.md
docs/man/rpmbuild.8.md
docs/man/rpmdb.8.md
docs/man/rpmdeps.8.md
docs/man/rpmgraph.8.md
docs/man/rpmkeys.8.md
docs/man/rpmlua.8.md
docs/man/rpmsign.8.md
docs/man/rpmsort.8.md
docs/man/rpmspec.8.md

Contact info 20-30 years out of date is useful to exactly nobody. Historians are better served by digging up the info from git anyhow.

Remove AUTHORS sections from man pages

---

.github/workflows/artifact.yml

Commit 3ff9f13b4644145083ded06b26cd874fe507f5cc didn't specify any permissions for the GITHUB_TOKEN so it used the project's default read-only permissions, preventing the "gh release upload" command from working.  Fix by specifying the right permissions (for modifying releases, see [1]).
[1] https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token

Fix missing GITHUB_TOKEN permission setting

---

lib/rpmrc.cc
tests/rpmgeneral.at

Commit 7be4b79581a451f750242485ec1923ca96df9e5b didn't account for the fact that there can be multiple source values for the same key, and that order matters: to honor the default < vendor < host < user override system, we need to use the last, not the first value we encounter. And .insert() on an STL map only inserts if the they doesn't already exist. Oops. Add a test as well.
Fixes: #3582

Fix regression on buildarchtranslate overrides

---

tools/elfdeps.cc

I ended up doing this to make dealing with #2197 saner. The multi-arch stuff itself is not ready for merging but moving to STL stuff is something we'll want to do anyway going forward, regardless of what/when happens with the multi-arch stuff, and this'll be easier to review separately anyhow.
Not adding any new tests here because elfdeps is reasonably covered already (as in, made itself known while working on this :sweat_smile: )

Convert main data structures in elfdeps to C++

---

docs/manual/users_and_groups.md

This flag was actually backported to 4.20.1.

Fix RPM version introducing u! in docs

---

docs/man/rpmkeys.8.scd
include/rpm/rpmts.h
lib/keystore.cc
lib/keystore.hh
lib/rpmts.cc
tests/rpmsigdig.at
tools/rpmkeys.cc

This rebuilds the public key storage.
The keys from a previously used key store can be added --from KEYSTORE
Keys are stored in the latest format.
Resolves: #3347
Simplified implementation of #3474. Currently does not do key verification. That's something we might want to consider to do an key loading instead of the actual rebuild.

Implement rpmkeys --rebuild

---

lib/rpmug.cc
tests/rpmi.at

strtok() only handles non-empty tokens. Says so on the first line of the description on the man page. Doh. So use our own argv splitting, this is actually more handy anyhow.
Fixes: #3594

Fix empty password field in passwd/group causing entry to be ignored

---

build/parsePreamble.cc
build/parseSpec.cc
tests/data/SPECS/test-exclusivearch.spec
tests/rpmbuild.at

fd32a43 moved the architecture check after building. This decision needs to me made beforehand to not build on unsupported architectures. 1296ea9 also made it impossible to change the supported / excluded architectures later.
Move this particular check back and add a test case using ExclusiveArch
Resolves: #3569

Check architecture before building

---

tests/rpmbuild.at

This is more readable and more reliable in the context of the test suite.

Use files instead of redirects in test case

---

docs/man/rpmkeys.8.scd

The actual standard still a work-in-progress but this is useful for showcasing the basic principles.

Reformat rpmkeys manual to show the new man-page standard

---

rpmio/macro.cc
tests/rpmmacro.at

439a601439 dropped the code using stderr if no file descriptor is passed. The %dump macro code doesn't pass a file descriptor ever. This led to a segfault.
Omit test case as it spits out a long list of macros that are susceptible the change.
Resolves: #3588

Use stderr for %dump

---

docs/manual/spec.md

While the section does not contain any content, it is better to link to an empty section instead of a nonexisting file

spec.md: fix changelog toc item to point to the anchor

---

include/rpm/rpmpgp.h
rpmio/rpmpgpval.hh

While most of the details are handled by rpm-sequoia, rpm needs to know at least the algorithm id's. Add the other tags while at it, it's not much anyhow.
Also add the SHA3 description texts that were missing from 9344367edf654fb41a136793b68cea9abb892fb9
There's no way to test this stuff at this point though, we need to wait until sequoia-pgp 2.0 and a compatible rpm-sequoia. OTOH some implementations might need these symbols in place.
Fixes: #3631

Add new tag and algorithm ID's and descriptions from RFC-9580

---

docs/man/rpmkeys.8.scd

"_keyring_path" was found only in this manual. All over the code was "_keyringpath". Wrong is this manual, I conlude. This patch corrects the manual.

rpmkeys(8): Correct a typo in _keyringpath macro name

---

macros.in

gpg may prompt for a password which will hold up any package from building

Never gpg sign git commits in macros

---

lib/rpmug.cc
macros.in
tests/rpmverify.at

Look up multiple files if they are listes in the macros separated by colons. This way multiple sources of user and group information can be used.
This is needed as RPM no longer honors nsswitch as it fails for chroots. This way one can at least configure where RPM should look for user/group information.
Related: https://issues.redhat.com/browse/RHEL-78693

Make %_passwd_path and %_group_path lists

---

CMakeLists.txt

Check_c_compiler_flag sets a cache variable, so CACHE needs to be passed
in order to reset it for the next use.

Fix check_c_compiler_flag cmake tests

---

docs/CMakeLists.txt

Commit fc7d9d95561a57ed836ace9d526760ed137efb10 started using the static cmake list of manual (.md) pages which, unsurprisingly, had been missing some later additions, causing them to not be rendered on the website at all, so add them.
Despite installing the manuals on "make install", we actually use a %doc entry that copies them from the source tree in Fedora's rpm.spec, so no wonder this was overlooked.

Add missing manual pages to cmake list

---

docs/man/CMakeLists.txt
docs/man/rpm-setup-autosign.1.scd
docs/man/rpmbuild.1.scd
scripts/CMakeLists.txt
scripts/rpm-setup-autosign
tests/atlocal.in
tests/rpmi.at
tests/rpmsigdig.at
tests/setup.sh

See commits for details, but short summary: split autosigning setup from our test-suite setup into a standalone script that generates a passwordless key, configures rpmbuild to use it for autosigning, exports the pubkey and emits a command to import it to rpm keystore.
I fully expect there to be corner cases this doesn't correctly handle yet, we just need to have a script that works for the majority of users for the alpha.
Fixes: #3522

Add an easy autosigning setup script

---

docs/manual/macros.md
rpmio/macro.cc
tests/data/macros.testfile
tests/rpmmacro.at

The sole purpose of the block macro is to make defining multiline macros nicer with the function-line %{} block syntax. A multiline %{expand:...} is commonly abused for this purpose but it has side-effects.
Lets add one that doesn't: %{block:...} does exactly nothing but insert the macro body as-is, without having to resort to ugly \-line continuations.

Introduce %{span:...} macro for multiline macro sanity

---

lib/backend/bdb_ro.cc
lib/backend/dbi.hh
lib/backend/ndb/glue.cc
lib/backend/sqlite.cc
tests/rpmdb.at
tests/rpmsigdig.at

Eliminates the remaining warnings when compiling with something like "-O2 -flto=auto" as CXXFLAGS.
This is not pretty C++, just seems the least disruptive way to remove the violation in time for the alpha. The rpmdb layer needs a much bigger overhaul to make it resemble something like C++
Technically bdb_ro.cc didn't require this as it was using explicit C-style casts to its own cursor struct, but might as well change update it as well.
No intended functional changes in any of this, and the test-suite passes with both sqlite and ndb (latter tested locally).
Fixes: #3692

Minimally fix C++ one definition rule violation in the rpmdb backends

---

docs/man/CMakeLists.txt
docs/man/rpm-common.8.scd
docs/man/rpm-config.5.scd
docs/man/rpm-man-template.scd
docs/man/rpm-rpmrc.5.scd
docs/man/rpm.8.scd
docs/man/rpmkeys.8.scd
macros.in

Turns out we need to add both rpm-rpmrc(5) and rpm-config(5) at once to explain the configuration adequately. Note that this differs from rpm-macrofile(5) which is a generic format usable for other purposes as well, but rpmrc is strictly tied to the path processing etc so there's no separating the format and how it gets processed.
Fixes: #3620
Fixes: #3614

Add man pages to explain rpm runtime macro configuration

---

include/rpm/rpmts.h
lib/rpmts.cc
tools/rpmkeys.cc

All the newer functions taking rpmtxn as the main argument are prefixed rpmtxn so this looks inconsistent. Missed that in the review of 6c4d979e3629b775e7b08eb44b4afd74dfef2a3a. Also move it closer to the other related functions in the header.
No functional changes.

Rename rpmtsRebuildKeystore to rpmtxnRebuildKeystore()

---

CMakeLists.txt
tests/pinned/rpmlibver.txt

Rpm 4.20.1 is at 10.2 now and we're expecting at least one more feature release that might warrant bumping to 10.3 and so we don't want to collide with that. Lets leave it some room to grow just in case, the last 4.x branch might be out there for a while.
That 6 is just a number that is somewhat bigger than 2 :innocent:

Bump library version to 10.6.0 in preparation of 6.0 alpha

---

CONTRIBUTING.md

The license of anything AI generated is questionable at best, as is the content itself. Poisoning this well with AI slop is just not acceptable.
The last straw driving us to add this is GitHub now advertising Copilot Agent in each and every ticket in "click here to fix this" style. The last thing we want is "helpful" folken submitting AI generated "fixes".
The times. Sigh.

Add an AI-policy to contributing guidelines

---

rpmio/rpmio.cc
sign/rpmgensig.cc

This first patch fixes <code> foo | rpmkeys --import -</code>.
The other patch handles fdSize() failure when signing a package. I found it when making sure that my first patch does not cause any regressions. fdSize() failures were handled on all places except this one.
The two patches are not depending on each other, I just find them topically connected. If it is a problem, I can split this pull request. I have prominent interest in the first patch as it would safe me from creating temporary files when importing keys.

Fix importing keys from a pipe

---

docs/man/CMakeLists.txt

Many projects like to show the installed version in the left footer in their man pages so do the same, it seems useful.
In scdoc(5), this is done by appending a quoted string to the preamble:
NAME(section) ["left_footer" ["center_header"]]
Do this while processing man pages with scdoc(1), instead of configuring each .scd file with cmake first, which would seem wasteful just for this purpose.
Note that scd2html(1) doesn't render the "left_footer" in any way so we need to add it manually there (already done in mkpage).

Add rpm version to man pages

---

tools/rpmspec.cc

The history(3) library allocates its own copy of the line string passed to add_history() so we need to free it ourselves.
Found by Coverity.
Fixes: RHEL-55284

Fix memory leak in rpmspec --shell

---

tests/rpmspec.at

This is also useful for detecting memory leaks (like the one fixed in commit 96fe0562712227c1764f2bae27f1b138dda7e032).

Add rudimentary rpmspec --shell test

---

docs/man/rpm-config.5.scd

Use a consistent style and fix the wrong plural (lists) in %_pkgverify_digests while at it.

Fix colon separated lists in rpm-config(5)

---

lib/transaction.cc
tests/CMakeLists.txt
tests/atlocal.in
tests/mktree.common
tests/prpm.py
tests/rpmpython2.at

Clients like yum/dnf like to do a test-transaction before the real thing, causing verification to run twice and thus duplicating package digests. Skip the header adding on a test transaction to avoid this.
We can now test this with prpm.py from the previous commit. It means this stuff gets tested twice. Oh well.
Fixes: #3735

Avoid duplicating package digests with yum/dnf

---

include/rpm/rpmte.h
lib/rpmte.cc
lib/transaction.cc
plugins/audit.c
python/rpmte-py.c
tests/prpm.py
tests/rpmpython2.at

When added in 4.14.2, the grand idea was that the enforcing signature policy would be something global that you just don't skip. But reality is more complicated than that, and forcing *all* signatures to be skipped if you need to install one that isn't signed (eg a freshly built package inside a build-system) does not improve security, it makes it so much worse.
So, add a minimal API for getting and setting the verify level per transaction element, in addition to the existing global control and update the main vereify loop and the audit plugin to log the enforcing state on per-element basis. Add a test utilizing the new prpm.py test program.
Fixes: #3604

Add an API for per-package verify level control + python bindings

---

rpmio/rpmkeyring.cc
tests/CMakeLists.txt
tests/readpkgnullts.c
tests/rpmapi.at

Commit 09510e413dbbdecfa6d65406a31517c79dd6c773 introduced unconditional dereferencing of the keyring during verification, and so segfaults on NULL keyring. That can't happen within rpm itself, so we need a new test program to trigger it: call rpmReadPackageFile() with NULL ts.
Start a new test group of API tests, we'll need to do more of these. I wasted an hour or two looking for a way to reproduce this by rpm or the python bindings when writing this tiny test-program took all of five minutes.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2362996

Fix a regression when calling rpmReadPackageFile() with NULL ts

---

docs/man/rpm.8.scd
docs/man/rpm2archive.1.scd
docs/man/rpmbuild.1.scd
docs/man/rpmkeys.8.scd
docs/man/rpmsort.1.scd

These have been reported by the manpage-l10n project (https://manpages-l10n-team.pages.debian.net/manpages-l10n/)
Thanks to https://github.com/hmartink for doing so!
These reported issues were fixed:
```
Man page: rpm2archive.8
Issue 1:  \\f[B]rpm2cpio\\f[R] → \\f[B]rpm2cpio\\f[R](8)
Issue 2:  \\f[B]cpio\\f[R] → \\f[B]cpio\\f[R](1)
"In opposite to \\f[B]rpm2cpio\\f[R] \\f[B]rpm2archive\\f[R] also works with " "RPM packages containing files greater than 4GB which are not supported by " "\\f[B]cpio\\f[R].\\fR"
--
Man page: rpm.8
Issue:    missingok? This is not present in the UI translation
"Installs or upgrades all the missingok files in the package, regardless if " "they exist."
Made missingok bold as it is a keyword.
--
Man page: rpm.8
Issue 2:  rpm → \\f[B]rpm\\f[R]
"Verifying a package …
```

Fix various minor issues in the man pages

---

build/files.cc
build/pack.cc
build/parseSpec.cc
build/rpmbuild_internal.hh
build/rpmfc.cc
build/spec.cc
tests/data/SPECS/subpkg-mini.spec
tests/rpmpkgfmt.at

Commit c1ee3881268f3cfed524d1802a0765e24b9b1b98 introduced the package format into the package structure because it seemed to be the path of least pain - the pkg structure was available in all the places that needed this. In retrospective, it's saner to have it centrally in the spec struct and pass around as needed. This avoids rpm's shenanigans with how and when exactly the package structures are initialized, causing inconsistent package versions across a set of packages coming from a single build.
This way we also detect and initialize the format exactly once, and thus avoid having to weed out duplicates from the log.
Add a test that all built packages are of the same version for both 4 and 6 regardless of the default.
Fixes: #3731

Rework the way rpm package format version is passed around

---

tests/rpmsigdig.at
tools/rpmkeys.cc

Both GnuPG and Sequoia use uppercase hex in all their key id / fingerprint output, but accept lowercase for input. Rpm uses and only accepts lowercase hex for these which makes life a PITA when copy-pasting key ids across. Make the key matching case insensitive.
Add test for all backends, although this is an overkill since the matching is done inside the rpmkeys tool rather than the backend. But in case that changes some day...
Fixes: #3721

Make rpmkeys key lookup case insensitive

---

docs/man/CMakeLists.txt
docs/man/rpm-payloadflags.5.scd
docs/manual/tags.md
include/rpm/rpmio.h
macros.in

Add a new rpm-payloadflags(5) man page update/add pointers where relevant so we don't need to carry the same info in multiple places.
Fixes: #3764

Consolidate payload flags documentation to rpm-payloadflags(5) man page

---

build/build.cc
tests/data/SPECS/minibr.spec
tests/rpmbuild.at

More fallout from the intermediate build directory in 4.20: since commit 5b2abeae2602dbb1052935a32b9009d618067b85 we no longer create an accidental build-directory for some cases, but still try to remove it in others. And fails.
Add test-cases rpmbuild -rs test-cases with and without %generate_buildrequires which adds its own spices to the mix.
Try to tackle this in a moderately generic way: if we didn't create a build directory, we shouldn't try to delete it either. The test-suite passes, but countless untested rpmbuild invocation cases remain.
That's the problem with all these strange build modes: somebody needs to test, maintain and debug them...
Fixes: #3682

Fix a regression on rpmbuild -rs failure on non-existent directory

---

.github/workflows/gh-pages.yml
docs/CMakeLists.txt
docs/_config.yml
docs/_config.yml.in
docs/index.md
docs/man/CMakeLists.txt
docs/man/index.md
docs/man/mkpage.in

The docs index page is currently only used as a "landing page" for local `make site` preview. With versioned docs (#3611), we'll link to it from https://rpm.org/documentation.html, so make it a bit more presentable and useful. This involves the following (details in the commit messages):
* Update the index page itself (fix API link, add RPM version, etc.)
* Use normal Jekyll pages for the HTML man pages (not a collection)
* Build API docs as part of `make pages`
Once this is merged, I'll backport some of it (mainly the index page) to the current stable branches (`rpm-4.20.x` and `rpm-4.19.x`) so that we can link to those from rpm.org as well.
Preview: https://dmnks.github.io/rpm/

Turn docs index into a publishable landing page

---

build/rpmfc.cc
scripts/find-provides
scripts/find-requires
tests/rpmbuild.at

The external dependency generator has been supposedly deprecated for two decades by now, and we've been issuing a deprecation warning on it for nine year by now. And, we'll continue to do so as long as we support v4 package generation, because we can't very well make something mandatory there at this point. Instead, error out if external dependency   generator is used for v6 packages. Add tests + make the package version explicit in them all.
Fixes: #2373
The first commit turned out to be necessary to test the external depgen at all, the second one is to just fleshen out the related v4 tests a bit.

Require use of internal dependency generator for v6 packages

---

tests/rpmbuild.at

Commit e0e43e93777701f5f2e6f7505b8e9b9e9681aee1 fixed a regression where RPMTAG_SOURCERPM would be missing from subpackage debuginfo but didn't include a test, so add one here.
Fixes: #3800

Add test to ensure RPMTAG_SOURCERPM on debuginfo

---

tests/rpmbuild.at

Older versions of find-debuginfo (or some tooling within) emit an extra "1 block" message on stderr that causes the test to unnecessarily fail on F41 and other older distros.

Ignore stderr on the sourcerpm test to avoid bogus failures

---

tests/atlocal.in
tests/rpmpython2.at

We ran into test issues when testing our changes with Python 3.14 which isn't yet a system Python in Fedora. These changes made tests run and pass as expected.

Enable running tests with a Python interpreter other than the system one

---

lib/poptALL.cc
tests/rpmbuild.at
tests/rpmmacro.at

The macro expansion of an --eval need not return anything (eg, it could be a lua script only run for its side effects). That --eval then prints an empty line. A silly example:
`$ rpm --eval '%{lua: a = 1}' --eval '%{lua: print( "Hi!" )}' --eval '%{lua: b = 2}' 
Hi!
`
This trivial commit skips printing if the macro expansion is an empty string. Tested lightly on rpm-4.20.1 (Fedora 42) and forward-ported to master.

Don't print empty return of --eval macro expansion

---

CMakeLists.txt

The previous log wasn't clear:
-- Performing Test found
-- Performing Test found - Success
-- Performing Test found
-- Performing Test found - Success
-- Performing Test found
-- Performing Test found - Failed
Use a new var SUPPORTS_${flag} will make it more clear:
-- Performing Test SUPPORTS_-fno-strict-overflow
-- Performing Test SUPPORTS_-fno-strict-overflow - Success
-- Performing Test SUPPORTS_-fno-delete-null-pointer-checks
-- Performing Test SUPPORTS_-fno-delete-null-pointer-checks - Success
-- Performing Test SUPPORTS_-fhardened
-- Performing Test SUPPORTS_-fhardened - Failed

CMakeLists.txt: Improve checking for CFLAGS

---

docs/man/rpm.8.scd

Drop table borders, they're jarring. Move the tables after the textual description and swap the tables around so they follow the actual output order: result first, then the optional marker. Drop the redundant "%files attribute" column from the table, that doesn't provide any real value and is easily enough embedded in the description.

Tidy up + improve the --verify output section of rpm(8)

---

macros.in
tests/rpmbuild.at
tests/rpmquery.at

With the SHA3 digests in, we're close enough to final v6 format to make it the default. Update the handful of tests that are affected and drop the experimental note from macros.in.
We fully expect distros to override this locally for a while, but upstream needs to make this change now.
Fixes: #3455

Default to v6 package format

---

lib/rpmts_internal.hh
lib/transaction.cc
tests/data/SPECS/ftrigfail.spec
tests/data/SPECS/triggers.spec
tests/rpmi.at
tests/rpmscript.at

The first commits are just prepwork for the actual change - add tests for all the possible scripts that can fail etc, the last one is the one with the actual change:
In rpm 4.4.x and earlier, scriptlet failures often caused duplicate packages to be left in the database: for example a %post scriptlet failing in an update would cause canceling the corresponding erasure element of the old version, but the files of the newer version are already on disk at this point. This caused all sorts of annoyances to the users, including missed security updates and having to periodically mop any failures out of the rpmdb. There was an entire ecosystem of tooling and documentation around this phenomena...
In 4.6.0 we started filtering out such "post" scriptlet errors in commit …

Reflect all scriptlet errors in rpmtsRun() return code

---

scripts/sysusers.sh

There's one call to usermod in the sysusers script to which we don't pass $ROOT. Let's fix that.

scripts/sysusers: Make sure $ROOT is passed to usermod

---

docs/man/CMakeLists.txt
docs/man/rpm-payloadflags.7.scd
docs/man/rpmbuild-config.5.scd
docs/manual/tags.md
include/rpm/rpmio.h
macros.in

This is neither a file format nor a configuration file, but more of this misc API thing that ... belongs to section 7.

Realize rpm-payloadflags is not section 5 material

---

INSTALL
include/rpm/rpmpgp.h
lib/rpmvs.cc
rpmio/CMakeLists.txt
rpmio/rpmpgp_sequoia.cc
tests/Dockerfile.fedora
tests/rpmbuild.at
tests/rpmsigdig.at

This has the necessary rpm-side bits to support v6 signature verification with the aid of rpm-sequoia + https://github.com/rpm-software-management/rpm-sequoia/pull/92
Draft for now as there's no rpm-sequoia release that we can use in CI.

Support OpenPGP v6 signature pre-salting

---

docs/man/rpmkeys.8.scd

rpmkeys program now has both --erase and --delete option doing the same thing. (See commit abb6ab1c43a946eb36a36227e39918580390a8e4 "Rename rpmkeys --delete to rpmkeys --erase".) According to Michal Domonkos and that commit, --delete is an deprecated alias.
This patch documents that so that users know which of the options to prefer.

doc: Deprecate rpmkeys --delete

---

tests/Dockerfile.fedora
tests/mktree.common
tests/mktree.oci

Enable `make check` to work from inside a [toolbox](https://containertoolbx.org/) container, and adjust Dockerfile so that it can be used to build a toolbox-ready image.
Fixes: #3850

Toolbox integration with `make check`

---

docs/man/rpm.8.md

This is the branch currently used by Fedora 42. The formatting is broken for a section that needed to be emboldened. This is corrected in my patch.

A boldening format fix

---

lib/rpmvs.cc
tests/rpmsigdig.at

Ensure the verification item is a signature before calling pgpDigParamsSalt(). Otherwise we can end up calling it with the character array of a digest instead, which may not end well.
The test relies on debug output from rpm-sequoia so it's a bit feeble, but it's the best we can do here.
Should've been in c36c717f41683953b9c23e447a8df0d0ac7c845c.

Only ever call pgpDigParamsSalt() on signatures

---

rpmio/rpmlua.cc
tests/rpmmacro.at

If "c" is not given in the a second parameter glob should not return any results if the pattern doesn't match any files.
Fix the condition that checks this parameter. Also don't error out if rpmGlob returns GLOB_NOMATCH which is expected in this case.
Add a test case.
Resolves: #3794

Lua: Return empty result for no matches for glob()

---

sign/rpmgensig.cc
tests/data/misc/rpmdump4-addsign-v6.txt
tests/data/misc/rpmdump6-addsign-v6.txt
tests/rpmsigdig.at

The signature reservation adjustment is one of those whack-a-mole bugs where fixes keep making new bugs appear: the signature reservation was broken by 1847fd6bea41f96ca545e744ee9ecc2896f6378a which came from be950eabb84a88e5773e096435c37b92e3d47ebb which came from 5c279fb149a44a1bc4d19e11c3c01942732b8486 and so on.
This seemingly simple thing is pretty tricksy, especially when needing to deal with 3rd party signed packages that don't always follow our expectations. What 1847fd6bea41f96ca545e744ee9ecc2896f6378a got wrong is that the header size before unloadImmutableRegion() will include the the region index and data entries, totalling 32 bytes, whereas the other calculations are lacking it. And without adjusting for it, the difference either causes the mechanism not to work or corrupted …

Fix regression on signature size reservation not being used

---

docs/manual/autosetup.md

I have no idea if this builds. I tried following the instructions in docs/README.md, but cmake insisted on more and more dependencies, I eventually gave up.

Docs: Link to %setup from %autosetup

---

docs/manual/tags.md

Commit 2a136bcf73204dd564a6ead975bd2934c684b9f0 accidentally removed the
top --- delimiter, causing jekyll to skip it when rendering the pages.

Fix missing delimiter in tags page

---

docs/man/rpm2archive.1.scd

Commit 427c05667eda2fad69a54c90e868a6689adfd74d messed up the cases where standard input is used.

Match rpm2archive man page to what it really does

---

tools/rpmbuild.cc

Also remove HEADERCONV_EXPANDFILELIST and expandFilelist() whihc are implementing it. Keeping the defines in comments to reserve the values.
Resolves: #3927

Drop support for rpmbuild --nodirtokens

---

lib/keystore.hh

[Virtual functions should specify exactly one of `virtual`, `override`, or `final`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final). In this case, they all could be marked as `final`, but this is a design decision and I do not want to take it here.

Specify overridden member functions as `override`

---

docs/man/rpm-lua.7.scd
docs/man/rpm-macros.7.scd
docs/man/rpm-payloadflags.7.scd
docs/man/rpm-plugin-prioreset.8.scd
docs/man/rpm-plugins.8.scd
docs/man/rpm-version.7.scd
docs/man/rpm2cpio.1.scd
docs/man/rpmdb.8.scd
docs/man/rpmuncompress.1.scd

After #3960 I got the idea of running aspell on the man folder, this is what I found when going through that output.

Fix typos in man pages

---

include/rpm/rpmpgp.h
rpmio/rpmpgp_dummy.cc

Commit c36c717f41683953b9c23e447a8df0d0ac7c845c neglected to add the stub for non-sequoia builds.
Fixes: #3970

Fix build regression on WITH_SEQUOIA=OFF

---

docs/man/rpmbuild.1.scd

NoSource and NoPatch are by their own declaration not sources, so it's logical they are not affected by --rmsource, but this wasn't explicitly documented anywhere.
Fixes: #3037

Document that --rmsource does not affect NoSource and NoPatch

---

docs/man/rpm-queryformat.7.scd

Use the same terms as we do in the new rpm-scriptlets(7) man page, and add references to it as well.

Update scriptlet terminology in rpm-queryformat(7)

---

docs/man/rpm-common.8.scd
docs/man/rpm-config.5.scd
docs/man/rpm-lua.7.scd
docs/man/rpmspec.1.scd

Saw a doubled word in the original man page text when checking the Swedish translation, so ran a script to find some more.

Fix doubled words in man pages
