rpm-software-management/rpm

scripts/pythondistdeps.py
=> Fix option parsing in pythondistdeps

scripts/pythondistdeps.py
Tomas Orsava from the Fedora Python SIG requested that the dependency generator support only using `pythonXdist(M)` format for both Provides and Requires, so now this capability exists.
=> pythondistdeps.py: Add --majorver-only dependency switch

rpmio/rpmio.c
Here's a new pull request with xz threading settings being set through %_{binary,source}_payload.
=> Improvements for xz support

rpmsign.c
=> rpmsign: don't create & free NULL pointer

ci/Dockerfile, tests/Makefile.am
=> Semaphore CI

mkinstalldirs
=> update mkinstalldirs to latest version (2009)

build/files.c, build/rpmbuild_internal.h, build/spec.c
=> Couple fixes for debuginfo subpackages

tests/Makefile.am, tests/data/SPECS/test-subpackages-exclude.spec, tests/data/SPECS/test-subpackages-pathpostfixes.spec, tests/data/SPECS/test-subpackages.spec, tests/rpmbuild.at
Those are from rpm-maint@ done by mjw (+fixed bad sentence in test description by me)
=> Add more debuginfo tests

macros.in, scripts/python-macro-helper
To limit environment and user home dir influence.
=> Invoke python-macro-helper with -Es python args

scripts/brp-compress
=> brp-compress: compress fish manpages

doc/rpm.8
Reported-by: Michal Jaegermann <michal.jnn@gmail.com>
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1543222
=> man: fix typo

tests/README
=> Add tests/README

doc/rpm.8
Signed-off-by: Miroslav Suchý <msuchy@redhat.com>
=> Add missing newlines to man page

.mailmap
=> mailmap: invert emails for Igor Gnatenko

build/build.c, build/files.c, build/misc.c, build/parsePreamble.c, build/parsePrep.c, build/rpmbuild_internal.h, build/rpmbuild_misc.h, build/spec.c
Slice up addSource() to saner pieces to make it both more readable and preparing for next steps.
=> Cleanup and refactor addSource() for next steps

rpmio/macro.c
Problem was in reading of the memory right after the end of the
allocated area. (Similar problem as in
commit 54f24ec5486bdacde9419466a2c27defaddf508e).
This is a good opportunity to reflector the corresponding code
(setting variables according to the number of exclamation marks and
interrogation marks after % an before the macro).
=> Fix memory reading in the expansion of an unfinished macro "{%!"

lib/rpmtriggers.c, plugins/systemd_inhibit.c
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1714657 and another one spotted while investigating that.
=> Plug a couple of memleaks

scripts/find-debuginfo.sh
Introduced in commit 1da9e83, spotted by covscan.
=> Fix bogus if-condition in find-debuginfo.sh (#735)

rpmio/rpmlua.h, tests/rpmbuild.at, tests/rpmscript.at
Submitted via ml: http://lists.rpm.org/pipermail/rpm-maint/2019-June/010247.html
=> --without-lua fixes from mjw

tests/data/SPECS/buildrequires.spec, tests/rpmbuild.at
=> Make dynamic buildrequires test arch independent

scripts/pythondistdeps.py
Fixes https://github.com/rpm-software-management/rpm/issues/639
=> Canonicalize Python versions and properly handle != spec

build/files.c
While technically legal in unix filesystems and easily handled in C code,
the sanity of using things like bell characters in filename is a whole
different matter, and hard to get right in our surrounding scripts.
One case in particular is our dependency generator which expects files
to be separated by newlines, so we couldn't fix that without breaking
the depgen "API" even if we wanted to.
Sanity demands banning the unprintable crap. This bans anything below
ASCII space character, and DEL. UTF-8 can contain other unprintable
material but lets not go there now...
=> Ban unprintable ASCII control characters in filenames

configure.ac, rpmio/Makefile.am, rpmio/digest_libgcrypt.c
=> Support libgrypt as crypto library

doc/manual/spec
- Improve description of conditionals in spec documentation
- Add description of comments in spec documentation
=> Improve description of conditionals + comments in spec documentation

rpmio/macro.c
The calculation of the slen parameter was not correct, as it didn't
account for already processed characters. The parameter itself was
also not used to limit the passed string, as the code assumed zero
termination. Thus we can as well simplify the code by using strlen()
on the passed string.
=> Drop slen from builtin macro parser function

build/parseSpec.c
That's the third loop of that form in the code...
=> Make copyNextLineFromOFI() aware of the new %[] syntax

lib/header.c
headerExport() is the only thing that needs offset sorting, there's no point messing up with the header itself for this when we can just sort a copy instead. No visible functional changes, but makes headerExport() a read-only operation to the header, as it should be.
=> Avoid modifying header on export

plugins/selinux.c
Misplaced parenthesis introduced in commit 148e82833a.
Fixes #872
=> Fix suspicious condition in selinux plugin

ci/Dockerfile, po/POTFILES.in
- Enable translations on all database backend sources
- Enable sqlite on CI
=> Misc rpmdb related fixes

rpmrc.in
We're seeing a few issues on Arm platforms [1], ARMv7 and aarch64, and review there's a few issues and clarifications needed around the way some of the Arm features work. This fixes up the issues seen and clarifies a few details of some of the Arm architecture quirks.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1562084
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
=> Fixes for some issues on Arm platforms

lib/backend/db3.c, lib/backend/dbi.h, lib/backend/lmdb.c, lib/backend/sqlite.c, lib/rpmdb.c
Fix a huge memory leak, cache prepared statements for improved performance.
Details in the commits.
=> Sqlite fixes

lib/backend/sqlite.c
=> Sqlite backend fixes and performance improvements

rpmio/rpmio.c
If zstd stream initialization fails, the opened fd and the stream
itself are leaked. Handle error exit in a central label.
=> Fix resource leaks on zstd open error paths

scripts/pythondistdeps.py
This branch was intended to address issue #881 but I also handled #612 and some other fixes.  Please let me know if you'd prefer these commits in individual PRs.
=> Fix compatible-release, versions with dot-star, semantically versioned deps, and python version

scripts/brp-compress
Handle zstd compressed man/info pages in brp-compress
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> brp-compress: Handle zstd compressed man/info pages

scripts/check-rpaths, tools/sepdebugcrcfix.c
This replaces PR #984 and #985 to get the commit messages to my liking - what they actually do is more important than where the patch file originates.
=> Upstream couple of Debian patches

lib/backend/ndb/glue.c
See also commit a429c99e13fbe9926243f29b78df8d64222c4469 for db3.
=> Permit ndb database queries on read-only media

tests/README
Update tests/README to describe howto use the test suite other than just
running everything.
=> Describe how to run single tests

rpmio/macro.c
Before this commit, there was an "escape" flag that made the macro
expansion keep '%%' escapes. But this did not work for macros
that returned an '%' character by other means.
Remove the old escape mechanism and instead double the '%' characters
when the body is split into argument.
Fixes: #1055
=> Double the '%' chars when splitting macro args

lib/fprint.c
Simplify the way the fingerprint cache is created.
=> Cleanup fingerprint cache creation

lib/backend/sqlite.c
The verify method on sqlite backend was buggy due to misunderstanding what and how "PRAGMA integrity_check" reports things. In addition, let sqlite do a foreign key check on our indexes on verify.
=> Sqlite --verifydb improvements

tests/atlocal.in, tests/local.at, tests/rpmbuild.at, tests/rpmbuildid.at
Details in commit messages, fixes #1102
=> Fix bogus failures from test-suite when host db_backend differs

lib/backend/dbi.c
Try the configured backend first, and only if that fails try autodetection.
The former logic did not anticipate multiple backends handling same
files and gets mightily confused when both bdb and bdb-ro are enabled,
causing half the test-suite failing in "make check".
Also emit a different message when database rebuild is in progress,
the old message is quite confusing in that case.
Loosely based on a similar patch by Michael Schroeder (first commit of #1012)
=> Rework and clarify database backend detection logic

lib/rpmdb.c
In some scenarios we previously only created some of the indexes only
lazy db init through query. Partially initialized databases don't make
sense and are only asking for trouble, in particular this was causing
issues with sqlite backend which is stricter about readonly-mode.
Except for the special case of reading a potentially damaged database
for rebuilding, always open all the indexes from openDatabase().
=> Always open (and initialize) the entire database at once

rpm.pc.in
Should've been in commit 7de982ac0957c42f228b43685d9f486e55eac331
=> Nuke leftover LMDB reference in rpm.pc.in

Makefile.am, ci/Dockerfile
Should've been in commit 7de982ac0957c42f228b43685d9f486e55eac331
=> Nuke leftover LMDB references in Makefile.am and Dockerfile

build/Makefile.am, build/rpmfc.c
Should've been in commit 3c061be6aeaec1be793b406fac9f667dc5d1429b.
=> Fix build when libelf is available but libdw is not

rpmio/digest_libgcrypt.c
For DSA2 we need to truncate the hash to the size of the pubkey's Q value.
=> Support DSA2 in digest_libgcrypt.c

scripts/pythondistdeps.py
This change handles a number of additional quirks in converting python packaging requirement expressions to rpm, including handling .* in various operators and handling pre and post releases.
For example, comparing the output of "pythondistdeps.py -R" for molecule before and after this patch:
```
--- /tmp/molecule-requires.1	2020-01-21 20:23:13.996776548 -0800
+++ /tmp/molecule-requires.2	2020-01-21 20:23:45.722900097 -0800
@@ -1,6 +1,6 @@
-python(abi) == 3.7
+python(abi) = 3.7
python3.7dist(ansible) >= 2.5
-(python3.7dist(ansible-lint) >= 4.1.1a2 with python3.7dist(ansible-lint) < 5)
+(python3.7dist(ansible-lint) < 5 with python3.7dist(ansible-lint) >= 4.1.1~a2)
python3.7dist(cerberus) >= 1.3.1
python3.7dist(click) >= 7
python3.7dist(click-completion) >= 0.5.1
@@ -20,7 +20,7 @@ …
```
=> scripts/pythondistdeps: Improved python version and operator handling.

doc/rpmdeps.8
This will update the man page in order to describe all rpmdeps options.
=> Document all of rpmdeps options

python/setup.py.in
=> Add license to Python distutils module description

scripts/pythondistdeps.py
This is a modification of PR https://github.com/rpm-software-management/rpm/pull/1195, where I've deleted all mentions of the test suite.
CC @pmatilai, @Conan-Kudo, @ffesti, @hroncok
=> scripts/pythondistdeps: Various updates and fixes (no test suite)

build/rpmfc.c
Hit merge just a little bit too quickly on this one...
=> Fix tag mixup in 32e2bc50cff9db05729349ff6645a0251d5719fb

lib/backend/sqlite.c
The prefix search was so wrong it's a small miracle it ever did anything
at all. What have I been thinking? Well, I do remember thinking this
prefix stuff looks kinda fishy but then it seems to work so...
The prefix search belongs to the keyed iterator fetch case of course,
not the case where we're otherwise iterating over all keys.
Fixes: #1260
=> Fix completely broken prefix search on sqlite backend

tests/Makefile.am, tests/rpmsigdig.at
Localize the setup/teardown to the only place needing it.
=> Cleanup gpg-agent handling in test-suite

lib/rpmrc.c
Should've been reverted as a part of reverting commits
0da3c50d1fa37945ba1b01975ecf2f62b51fb3cd and
8ab279ae6b3855fca5946dafd11c38e91adc9904 but got left behind and Fedora
has been carrying this reversion as a patch since then (and other
distros carrying others). This equally broken for everybody -state of
ARM is good for nobody. Lets revert back to pre 4.15 state and back to
the drawing board.
This reverts commit 8c3a7b8fa92b49a811fe36b60857b12f5d7db8a8.
=> Revert "Improve ARM detection"

rpmio/expression.c, tests/rpmmacro.at
Add stringification for versions and error out for arithmetic operations.
=> Improve version support in expressions

doc/manual/tags.md, lib/rpmtag.h
Organize the stuff a little and fill in blanks
=> Tag documentation updates

configure.ac
=> Really disable OpenMP if too old

scripts/pythondistdeps.py
Stop using the heavy-weight pkg_resources and switch to a subclass of
importlib.metadata. This does add a dependency on packaging as well for
requirement and version parsing. I have also removed the comments about
the attempted rewrite, since I have addressed many of the concerns.
=> pythondistdeps: Switch to importlib.metadata

rpm2archive.c
=> rpm2archive: Better error handling and better handling for URLs

doc/librpm/Doxyheader.h
=> Document rpm API thread (un-)safety

rpm.pc.in
=> Add popt to our pkgconfig dependencies

.mailmap, CREDITS
Lotsa new names, many from translations but otherwise too.
=> Update credits for a change

rpmio/rpmpgp.c
instead of recomputing it four places.
=> Use a variable for h + hlen

scripts/check-rpaths, scripts/check-rpaths-worker
=> Run rpath check in parallel

docs/man/Makefile.am
to avoid rebuilding the man pages over and over again
=> Create directories for man pages right away

scripts/check-rpaths-worker
=> Allow /usr/libexec/* rpaths

build/files.c, lib/backend/sqlite.c, lib/rpminstall.c, luaext/lrexlib.c, misc/fts.c, rpmio/rpmpgp.c
These were found by static analysis (Coverity).
=> Tiny memory leak fixes

lib/rpmtriggers.c
Resolves: #1636
Related: #1638
=> Don't segfault on missing priority tag

rpmio/macro.c
Some minor improvements, no functional changes.
=> Refactor macro handling

rpmio/macro.c, rpmio/rgetopt.c, rpmio/rpmlua.c, rpmio/rpmmacro_internal.h, tests/rpmmacro.at
This allows to manipulate an argument array from lua.
=> Support multiple args in %quote and make split/unsplit available to lua

rpmio/rpmlua.c
Doing the function lookup with calls to lua_getfield is dangerous
because the lookup might trigger an __index function that may
contain an error. This results in the lua library calling abort()
as no exception handler is set.
So change the code to do the lookup via a pcall(). Also do the
string conversion with a pcall() because tostring is also not
safe.
=> Make rpmluaCallStringFunction more robust

lib/rpmscript.c
Commit 717a3f7ecf0af7c453cd1bcb3f49b5ea4941817e changed Lua scriptlet
arguments from numbers to strings, and claimed that Lua will handle
this automatically so nobody will notice a thing. Not so, Lua only
converts automatically when doing so is unambiguous, such as doing
math. In comparison Lua cannot know which kind of comparison we want,
and rightly refuses to convert. Thus, the commit broke any Lua
scriptlets doing `if arg[2] > 1 then ... end` style comparisons.
As the whole rpmluav variable API is gone now, we can't just revert
the commit. Adding a preamble to the scriptlet to convert the args
to numbers may be hackish, but its a far lesser evil than bringing the
internal variable API back. Kudos to Michael Schroeder for the idea.
Fixes: #1790
=> Restore scriptlet arguments passed as numbers to Lua scriptlets

lib/rpmtriggers.c
If a package has multiple %transfiletriggerpostun triggers, any one
of them matching would cause all of them to run, due to disconnect
in the intel gathering stage: we'd gather all the headers with matching
files into a lump, and then add any postun triggers found in them,
but this loses the triggering file information and causes all postuns
to run.
The triggers need to be added while looping over the file matches,
like runFileTriggers() does. Doing so actually simplifies the code.
These should really be unified to use the same code, but leaving
that exercise to another rainy day.
=> Fix spurious %transfiletriggerpostun execution (RhBug:2023311)

build/parsePreamble.c, build/rpmbuild_internal.h, build/speclua.c, rpmio/rpmlua.c, rpmio/rpmlua.h
Get rid of unused functions, fix the indentation and make things a bit nicer.
=> Cleanup the lua code a bit

rpmio/rpmlua.c, tests/rpmmacro.at
Avoids having to manually "print()" everything, at the cost of requiring
a "return" which is not really less to type but more natural for
programming, and other benefits likely to follow.
=> Auto-print returned values from Lua macros

lib/header.c
This is mainly to place *some* limit on number of files a package may
have. It's unlikely that rpm scales to million files in a package but
that much may actually work, whereas closer to int32 limits we run into
all manner of issues with internal types mismatching and whatnot.
=> Limit maximum array size in the header to about one million

docs/man/Makefile.am
Let make figure the actual paths, it seems to handle this just fine
once we stop meddling with it's affairs.
Fixes: #1851
=> Fix out of tree build regression wrt man page generation

lib/backend/ndb/glue.c
=> Fix a memleak in ndb from opened but not closed dbis.

docs/manual/spec.md
Context: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/QYZYBWYFTXVOSXBR7JTFWMHQHGF4LAOZ/
See also #1855 about option to disable path stripping.
=> Document %doc relative path stripping

installplatform, lib/rpmrc.c, macros.in, rpmrc.in
Signed-off-by: Zhang Wenlong <zhangwenlong@loongson.cn>
=> add support for loongarch64

docs/manual/dependency_generators.md, docs/manual/tags.md
Mainly reformat and improve the Tags page.
=> More work on the Reference Manual

docs/manual/conditionalbuilds.md, macros.in, tests/Makefile.am, tests/data/SPECS/bcondtest.spec, tests/rpmbuild.at
Removed unnecessary %expands and squashed commits of #1520
=>  Open Add %bcond macro for defining build conditionals (reworked #1520)

docs/man/rpmbuild.8.md, rpmbuild.c, tests/rpmbuild.at
Fix for #876 and added man page entries.
Should be squashed while merging.
Resolves: #876
=>  Added option to rpmbuild to check the build dependencies (-bd,-td,-rd) #876 

build/rpmfc.c
The costs of libmagic is gigantic for packages with a lot of source
files (like the kernel sources or any -debugsource) and there is
little gain from running it, so spare it by skipping the calculcation
for .c and .h files.
=> Avoid libmagic calculation for source files

sign/rpmgensig.c, tests/data/keys/CVE-2021-3521-badbind.asc, tests/data/keys/CVE-2021-3521-nosubsig-last.asc, tests/data/keys/CVE-2021-3521-nosubsig.asc
=> Remove NSS references

CONTRIBUTING.md
=> Fix capitalization in CONTRIBUTING.md

build/parsePrep.c
Details in commit messages, but these are simply bad syntaxes for applying patches, and having to support them prevents other developments in this area. Both `%patch` and in particular, `%patchN` are widely used so these need a longish deprecation period, but it needs to start somewhere.
=> Deprecate numberless %patch meaning patch number zero

tests/rpmsigdig.at
=> Don't assert the version of rpm used to create the data

docs/manual/tags.md
in reference manual and define a format
=> Improve documentation for VCS tag

.gitignore, docs/Makefile.am, docs/_config.yml, docs/_layouts/default.html, docs/manual/devel_documentation.md, docs/manual/index.md
=> Doc on docs

lib/rpminstall.c, tests/rpmi.at
This allows to downgrade packages just as with --upgrade but limited to
already installed packages.
Also add basic tests for --freshen
Resolves: #652
=> Add support for --oldpackage to --freshen

tests/rpmdb.at
=> Testcases: Queries to rpmdb including ^~+

rpmio/rpmglob.c
Now that we directly use GLOB_NOMAGIC to implement a fallthrough for
non-glob patterns since commit 9e541c6a7da076bc1c1beb1ee45fd5fdd735358c,
we may ironically end up subjecting such patterns to the lstat(2) check
at the end if they're directories, and thus possibly not return them.
While the actual impact on our codebase seems to be minimal, mostly in
terms of pushing the point of failure elsewhere and possibly printing a
different error message, for the sake of consistency with the idea of
GLOB_NOMAGIC, fix this by bringing back the short-circuit check.
While at it, make it a bit simpler than the original rpmIsGlob() by
leaving out the well-formedness check (i.e. if a bracket/brace has a
closing counterpart) as that's not what GLOB_NOMAGIC does either.
Remove the now unused …
=> Fix non-glob fallthrough in rpmGlob()

configure.ac, lib/rpmts.c, tests/Makefile.am, tests/atlocal.in, tests/rpmsigdig.at
This is a back port of the fixes to the test suite for Sequoia.  These changes were applied to master in this context:  https://github.com/rpm-software-management/rpm/pull/2063
=> Fix 2071 for 4.18

plugins/fapolicyd.c
- switch to read only and non blocking mode for pipe
- add 1 minute loop to wait for pipe to reappear
Signed-off-by: Radovan Sroka <rsroka@redhat.com>
=> fapolicyd: Make write() nonblocking

ci/Dockerfile, include/rpm/rpmte.h, tests/rpmverify.at
...since it seems that we actually can now. Fingers crossed.
=> Bump CI to Fedora 36

plugins/selinux.c
libselinux logs to stderr by default, which up to now has been just fine with us. However somewhere around libselinux 3.2 it begun issuing log messages for events discovered in selinux_status_updated(). We only call that to see whether the status *was* updated behind our back and are not interested in these audit-style messages for our functionality, but to suppress them while preserving actually relevant errors and warnings, we need to have a log callback of our own. Might as well forward them to rpmlog then.
SELINUX_ERROR and SELINUX_WARNING are pretty obvious, of SELINUX_AVC selinux_set_callback(3) says it should be treated as SELINUX_ERROR if not audited. The rest we suppress to debug messages, they may be handy for diagnostics some day.
Note that this intentionally avoids explicit …
=> Add a handler for libselinux log messages (RhBug:2123719, RhBug:2050774)

docs/manual/format.md, include/rpm/rpmio.h
=> Add manual page for File Mode

build/files.c, tests/data/SPECS/globesctest.spec, tests/rpmbuild.at
=> Glob special files only once, internally

lib/header.c
Not a functional change, it just makes the code more clear and self-consistent.
=> Use unsigned integers more consistently in the handling of tag data

build/build.c, build/parsePreamble.c, build/parseScript.c, build/rpmfc.c
Fix some resource leaks in some cases when running rpmbuild.
=> Fix some resource leaks when running rpmbuild

rpm2archive.c
Fixes for the popt argument handling
=> Rpm2archive

lib/fsm.c, lib/rpminstall.c
Fix memory and file leak in some cases when running "rpm -i".
=> Fix memory and file leak in some cases when running "rpm -i"

build/parsePrep.c, tests/rpmspec.at
fix issue 2335:space handling in %setup
Signed-off-by: wangpeng <wangpengb@uniontech.com>
=> fix issue 2335:space handling in %setup

CMakeLists.txt, rpmio/CMakeLists.txt, rpmio/rpmio.c
Details in commits, but this is just cleanup, no functional changes.
=> Simplify + clean up rpmio thread enablement code

docs/manual/format.md
in the reference manual
Resolves: #2413
=> Describe the stripped down payload format

build/rpmfc.c, include/rpm/rpmds.h, lib/rpmds.c, lib/rpmte.c, lib/tagexts.c
=> rpmds related cleanups + sanity fixes

docs/manual/macros.md, tests/rpmmacro.at
See https://github.com/rpm-software-management/rpm/issues/2444
=> Add documentation and test case for shell like macro '%**'

docs/manual/macros.md
=> Added more details to the doc about what is returned by the macros '%-x' and '%-x*'

CMakeLists.txt, tests/rpmgeneral.at
We've removed a tonne of obsolete APIs in this release so...
=> Bump the soname in anticipation of the 4.19 alpha release

tests/rpmverify.at
Take advantage of root(less) aware $VERIFYOPTS added in commit fb040f16ec09a10c47f968d995c5bb770b8a7a64.
=> Verify user/group in tests when possible

docs/manual/macros.md
Use tables where they make sense, group builtins by category that can be linked to, add version introduced where relevant. In addition, some awkward/misleading wordings fixed.
=> Macro documentation improvements

macros.in
Based on downstream Fedora patch
=> Add RPM_LD_FLAGS to build environment

docs/manual/macros.md
=> Add doc notes related to option processing

python/CMakeLists.txt, python/examples/rpmls.py, python/examples/rpmunpack.py, python/examples/srpmspec.py
It's not whether these are particularly important examples or not (they're not), but adding more will be so much easier once the place to add them has been established.
Fixes: #2075
=> Add some Python binding examples

tests/local.at, tests/rpmbuild.at, tests/rpmbuildid.at, tests/rpmconfig.at, tests/rpmconfig2.at, tests/rpmconfig3.at, tests/rpmconflict.at, tests/rpmdb.at, tests/rpmdeps.at, tests/rpme.at, tests/rpmgeneral.at, tests/rpmi.at, tests/rpmio.at, tests/rpmmacro.at, tests/rpmorder.at, tests/rpmpgp.at, tests/rpmpython.at, tests/rpmquery.at, tests/rpmreplace.at, tests/rpmscript.at, tests/rpmsigdig.at, tests/rpmspec.at, tests/rpmvercmp.at, tests/rpmverify.at, tests/rpmvfylevel.at
We're going to do some stuff before and after these macros in the next commits/PRs so better do this beforehand.
=> Replace AT_CHECK and AT_CLEANUP with RPMTEST_*

tests/CMakeLists.txt, tests/rpmi.at
We're touching this stuff in #2559 so make it nicer to work with :smile:
=> Cosmetic test-related touch ups

tests/atlocal.in, tests/local.at
Despite the original claim of volume III being the last one before #2559., here's one another :smile: Just to keep things flowing.
=> Minor test-suite tweaks/fixes, volume IV

macros.in, scripts/CMakeLists.txt, scripts/sysusers.sh, tests/rpmi.at
for user and group generation.
This is currently failing in the test suite but works fine when rebased onto #2559 
Still needs --replace to be implemented
=> Add sysusers.sh script to replace systemd-sysusers

.github/workflows/linux.yml, tests/mktree.podman
Tweaked version of #2588 by @Conan-Kudo.
=> CI: Add initial GitHub Actions configuration

.gitignore, tests/CMakeLists.txt, tests/mktree.fedora
Please see the commit messages for details.
=> Mktree tweaks, volume I

tests/CMakeLists.txt, tests/Dockerfile, tests/README.md, tests/atlocal.in, tests/mktree.common, tests/mktree.fedora, tests/mktree.rootfs
These are mostly preparatory work for #2643.
=> Minor test-suite tweaks/fixes, volume V

rpmio/rpmlua.c, tests/rpmmacro.at
=> Return an error on macro expansion failure from Lua macros table too

build/parseSpec.c, rpmio/macro.c
Now that we can, just define __file_lineno as an auxiliary macro that only does any work in the rare case where an error or warning occurred. This saves an enormous amount of huffing and puffing defining and undefining macros that are not used at all in the normal paths, on every rpm startup and spec parse.
Technically we could use a common macro function for both but as they're in separate libraries, this doesn't seem worth the few lines of saving.
=> Refactor %__file_lineno management into an auxiliary macro

macros.in
Nothing defines RPMHOME, replace it with RPM_CONFIGDIR.
=> Fix a macro in the comment

tests/README.md
=> Extend test README

tests/rpmi.at, tests/rpmorder.at, tests/rpmscript.at, tests/rpmverify.at
Side-products from doing something else :sweat_smile:
=> Test-suite cleanups

docs/manual/users_and_groups.md
We now use our own script (sysuser.sh) instead of systemd's systemd-sysusers.
Resolves: #2857
=> Adjust User/Group handling Documentation

docs/manual/users_and_groups.md
Also fix some typos and add punctuation.
Follow-up for 44afd5b49c5375dee1892845c2ee873425728138.
=> docs: mention systemd-standalone-sysusers

CMakeLists.txt, lib/CMakeLists.txt, tests/atlocal.in
Please see the commit messages for details.
=> Awk detection fixes, volume II

docs/manual/users_and_groups.md, fileattrs/sysusers.attr, lib/psm.c, lib/tagexts.c, macros.in, scripts/sysusers.sh, tests/data/SPECS/klang.spec, tests/rpmi.at
Add support for sysusers group membership lines
m user group
Create Requires/Recommends for both the user and the group.
=> Add support for sysusers group membership lines

rpmio/lposix.c, rpmio/macro.c, rpmio/rpmfileutil.c, rpmio/rpmkeyring.c, rpmio/rpmlog.c
Here too, simply working towards reducing the number of raw mallocs.
=> Another bunch of misc C++ conversion/cleanups

rpmio/macro.c
Use an STL map for the macro entry table, this matches exactly the behavior we manually did with the C array.
The variable length array at end of macro entry structs is not really C++, use native strings for the storage. It's slower, but not tragically so. For now, keep name, opts and body as const char pointers though to the c_str() items to avoid having to change everything at once.
Popping macros is a bit clunky and repetitive, we'll clean it up later. findEntry() returns a pointer to the macro entry itself instead of pointer to pointer, which simplifies things a bit further.
This is a wee bit slower than the "raw C" counterpart, but by no means tragically so and moving to native structures opens up other opportunities in turn, both optimization and feature wise. Further work will be …
=> Convert macro table to STL containers + native strings

lib/rpmug.c
It may not make much difference for performance for our current use-cases, but since it's not really any more code now... Natively allocate the rpmug struct to enable this.
=> Implement proper user/group lookup caching with STL maps

lib/depends.c, lib/order.c, lib/package.c, lib/psm.c, lib/rpmdb.c, lib/rpmdb_internal.h, lib/rpmtriggers.c, lib/rpmts.c, lib/transaction.c
This was a particularly ugly case as it was defined in multiple places.
=> Convert packageHash to STL unordered_map

lib/headerfmt.c
A notable difference is that we're now storing the rpmtd structs themselves in the hash, rather than pointers to them.
A minor side-cleanup is that headerGet() does not return data on failure so there's no need to free anything in that case.
=> Replace rpmhash with STL unordered_map in headerformat cache

lib/rpmfi.c
rpmfi always internally stores 64bit sizes since 4.6.0, there's no reason to do anything else with replaced sizes either.
=> Simplify rpmfi replaced sized management

lib/package.c
It still needs to die, but there's less code that needs dying...
=> Replace the annoying keyid stash with an STL set

lib/depends.c, lib/order.c, lib/rpmte.c, lib/rpmts.c, lib/rpmts_internal.h, lib/transaction.c
=> Use an STL vector for the transaction main rpmte pointer storage

build/rpmfc.c
Apply the attributes in applyAttr() as per the name, and pass *that* index array to rpmfcHelper() which only needs to concern itself with generating the path arrays as per the used protocol.
No functional changes, doing this in "raw C" because this refactor is worth cherry-picking to 4.20 too, but also because doing this first makes converting to STL easier.
=> Clean up applyAttr() and rpmfcHelper() interaction

lib/depends.c
This isn't very idiomatic C++ but NULL pointers are used for logic so references wont do, and as for filedepHashFree() and depexistsHashFree(): deleting and NULL'ing all these pointers manually adds up.
=> Convert the various dependency checking hashes from rpmhash to STL

lib/formats.c, lib/headerfmt.c, lib/psm.c, lib/transaction.c
This time including string usages that speed up json and xml query formatting enormously.
=> Another bunch of STL conversions

lib/backend/dbiset.c, lib/backend/dbiset.h
An always-ordered data structure might make more sense here, but for now this is the lowest bar to entry.
=> Replace dbiset internals with STL vector + algorithms

rpmio/digest.c
Removes the arbitrary limit of ids we support. Not that rpm needs more, but arbitrary is arbitrary. Technically it's more efficient because we don't need to brute-force search and there are never inactive digests to skip when updating, but given the small number of elements it's unlikely to make any real-world difference.
Also remove the unused nbytes member, I don't recall why I added it but it hasn't been grown any uses in 10+ years so might as well drop.
=> Replace digest bundle static sized array with STL map

tests/rpmdb.at, tests/rpme.at, tests/rpmverify.at
=> Fix -Va usage in tests

docs/librpm/Doxyheader.h, include/rpm/rpmdb.h, include/rpm/rpmds.h, include/rpm/rpmfiles.h, include/rpm/rpmlib.h, tests/Dockerfile.fedora
Fix up stuff found by newer Doxygen + bump CI.
=> Bump CI to Fedora 40

rpmio/rpmkeyring.cc
This should be thread save as it still is in the public API. The internal use would be fine otherwise. So the lock can be removed if this gets made internal only.
Resolves: #3351
=> Lock key during rpmGetSubkeys()

include/rpm/rpmts.h, lib/misc.hh, lib/rpmts.cc, lib/rpmvs.cc, tests/rpmsigdig.at, tools/rpmkeys.cc
This turned out to be quite a pile.
=> Add + use a key deletion support

lib/keystore.cc
This is needlessly duplicated identical logic in two places so it's an obvious cleanup, but also lets #3350 proceed without having to worry about changing multiple places.
Related: #3350
=> Refactor the subkey handling to a keystore helper function

tests/README.md
This is part of M4, not specific to our test-suite, but it's a question that comes up often, and everyone (myself included) tends to forget how it's done.
=> Add note about square brackets to tests README

tests/rpmsigdig.at
=> Test reading openpgpg backend with sq

include/rpm/rpmkeyring.h, lib/rpmts.cc, rpmio/rpmkeyring.cc
Merge the keys directly in the keyring
=> Add support for RPMKEYRING_MERGE

tests/README.md
This came up while submitting #3540.
=> Add note on ASAN/UBSAN affecting test performance

docs/manual/conditionalbuilds.md
=> Demonstrate oneliner bcond syntax

tests/local.at, tests/rpmdepmatch.at, tests/rpmpython.at
myprint() has had its time in times of Python 2,
the print() function from Python's 3 stdlib does everything we need in the test suite.
=> Replace custom myprint() with print() from Python's stdlib in tests

docs/man/rpm-common.8.scd, docs/man/rpm-man-template.scd, docs/man/rpm2cpio.1.scd, docs/man/rpmdb.8.scd, docs/man/rpmlua.1.scd, docs/man/rpmsign.1.scd, docs/man/rpmsort.1.scd, docs/man/rpmspec.1.scd
rpmsign(1) contains many explanations for configuration that arguably belongs to rpm-config(5) but since we don't have that page yet...
=> Update rpmdb, rpmlua, rpmsign and rpmspec manuals to the new man style

build/parseSpec.cc, lib/backend/dbi.cc, lib/backend/dbiset.cc, lib/backend/dbiset.hh, lib/cpio.hh, lib/fsm.hh, lib/rpmchecksig.cc, lib/rpmchroot.hh, lib/rpmdb_internal.hh, lib/rpmfi_internal.hh, lib/tagname.cc, lib/transaction.cc, tools/cliutils.hh
Details in commits - mostly cleaning the ABI space but other misc tweaks I ran into as well.
Fixes: #3679
=> Misc ABI cleanups to hide "leaked" internal symbols etc

lib/rpminstall.cc, tests/data/SPECS/deptest.spec, tests/rpmdeps.at
Details in commits, fixes #3718
=> Fix a minor update failure error code regression

docs/man/CMakeLists.txt, docs/man/rpmbuild-config.5.scd, docs/man/rpmbuild.1.scd
=> Add a manual for build-side configurables

docs/manual/format_v6.md, docs/manual/signatures_digests.md
=> Document rpm v6 signatures in the format and signature summary docs

sign/rpmgensig.cc, tests/rpmsigdig.at
See the second commit for details.
=> Fail when adding legacy signature and one exists

docs/man/rpm.8.scd
This at least now covers all the major operations and the most common usages.
Fixes: #3628
=> Add a bunch of examples to the rpm(8) man page.

include/rpm/rpmds.h, lib/rpmds.cc, python/rpmds-py.c, tests/rpmpython.at
This is somehow both a mixed up bunch but still quite tightly related, so submitting as a single PR seems best.
=> Add a couple of rpmds tests + misc fixes discovered while looking at it
